### ISSUE TITLE
Best way to copy raw pixels

### ISSUE THREAD

**Issue by pleaseking** [Microsoft/Win2D#101]
Hi,

I need some advice regarding the most efficient way to copy pixels between an in-memory buffer and a `CanvasRenderTarget`. The background problem is as follows:
 - I have a GUI engine rendering in RGBA (now)
 - I need to use native Win2D text rendering
 - I have tried the following approaches:
    - Have a `CanvasRenderTarget` of the same size as buffer (i.e. screen), copy pixels from buffer into rendertarget, draw text, copy pixels back. Problem: slow to copy that many pixels.
    - Have same big `CanvasRenderTarget`, copy pixels for a rectangle surrounding text, draw text, copy pixels back (using a series of line-by-line `memcpy`'s and `GetPixelBytes(rect)` / `SetPixelBytes(rect)`). Problem: `GetPixelBytes(rect)` / `SetPixelBytes(rect)` are way slower than their counterparts for the full image - but overall this is faster than the first option.
    - Create a new small CanvasRenderTarget for each text block - then I can use `GetPixelBytes()` / `SetPixelBytes()` for the full image and they are faster, but creating/destroying `CanvasRenderTarget` takes time - however, this is the fastest for now.

My problem is that even the 3rd approach does not give acceptable performance on say Lumia 520. Any advice to optimize this even further? Maybe some D2D interop to read/write pixels of a CanvasRenderTarget directly, pixel-by-pixel, without `GetPixelBytes(rect)` / `SetPixelBytes(rect)` which seem to be quite inefficient?

**Comment by shawnhar** [comment]
By far the most efficient approach is to design your rendering so you never need to read back from the GPU to CPU at all!  This is always going to be a performance problem as it is just not what GPUs are designed for.  For efficient hardware accelerated rendering, you want all the data flow to be CPU -> GPU, with the CPU mostly passing across drawing commands rather than bulky pixel data, and the GPU doing all the creation and copying around of large bitmap images.

If you absolutely need to do this, the fastest version will likely be (as you have discovered) whatever copies the smallest number of pixels, but the fact that you are doing any copying at all is enough to flush the GPU pipeline and destroy all CPU/GPU parallelism, so it'll be quite expensive even if you just read back a single pixel.

Consider whether it is possible to flip your operations the other way around, send your CPU generated data into a Win2D GPU resource, then add the text and present keeping it all on the GPU side from then on?  Or possibly composite two separate layers, one for your existing content and the other drawn using Win2D, by stacking a partially transparent CanvasImageSource or CanvasControl on top of some other rendering?

**Comment by pleaseking** [comment]
Thanks for the quick reply, well of course you are right that best is to do all the rendering on GPU and avoid any CPU rendering at all. This is the intent, but it takes too much time to rewrite all bitmap operations - gonna take weeks. However, I actually thought of your last suggestion after I submitted the issue - draw the entire text into a transparent CanvasRenderTarget and then compose it on top of other rendering - and this sounds like the way to go. It has a drawback of not being possible to use ClearType (as it does not work over transparent background) - but I think I can live with that. 

Other than that, I can see something like "Read bitmap contents without memory allocation (GetPixelBytes overload that takes an IBuffer)" in win2d backlog - would that help much?

**Comment by shawnhar** [comment]
> I can see something like "Read bitmap contents without memory allocation (GetPixelBytes overload that takes an IBuffer)" in win2d backlog - would that help much? 

I don't think much, although it would probably make a small difference.  That feature would allow removing one CPU -> CPU copy of the data, but it doesn't remove the need for the initial GPU -> CPU copy, HW to SW format unswizzle, or the GPU pipeline stall which are the main things making any such readback slow.  These aspects are pretty much inherent to how GPUs work, not unique to Win2D or D2D.

**Comment by pleaseking** [comment]
Thanks, understand this CPU-GPU mechanics, just looking for an acceptable workarounds for now. Thanks a lot, I think I have some info to proceed..

**Comment by dumbledad** [comment]
How can I tell which methods "read back from the GPU to CPU"? Looking at the documentation for [CanvasBitmap.GetPixelBytes](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_GetPixelBytes.htm) it's not obvious to me that it's doing that.

**Comment by shawnhar** [comment]
Win2D is a hardware accelerated API, so the contents of CanvasBitmap are stored on the GPU.  Therefore any API which extracts those contents and returns a regular CPU array must perform a GPU -> CPU transfer.

**Comment by dumbledad** [comment]
Thanks - this thread is very useful for thinking through performance
