### ISSUE TITLE
Spaces render outside of the width of the CanvasTextLayout unlike regular characters

### ISSUE THREAD

**Issue by zhakopian** [Microsoft/Win2D#103]
I'm working on allowing users to input text and modify it in one of my applications. I've noticed that, while regular characters adhere to the boundaries of the CanvasTextLayout, spaces will not. If I press space, the cursor will move beyond the boundaries of the box until a regular character is outputted. You can see the results in the image below

![highlightissue](https://cloud.githubusercontent.com/assets/3682141/8070110/df3d04ea-0eb3-11e5-89e6-6b26c1bcb1cd.png)
![highlightissue2](https://cloud.githubusercontent.com/assets/3682141/8070111/df414582-0eb3-11e5-9a58-ba5c28ca64f5.png)

Is there any value I can set which will cause the space to act like every other character in this case?

**Comment by damyanp** [comment]
There's no option to make CanvasTextLayout behave differently here. 

One approach that may help you though would be to insert Unicode \u200c characters between each space.  For example, "str = str.replace(" ", " \u200c");".

Generally, CanvasTextLayout should be viewed as a building block rather than a complete text entry solution so it is not unreasonable to expect to massage the text you want to display in some way if you wish to customize the behavior.  A full-fledge text editor, for example, would expect to use multiple CanvasTextLayouts to display the text on the screen.

I'm going to close this issue, but feel free to reopen if you have further questions.

Thanks!
