### ISSUE TITLE
Doc request: Canvas.ClearColor vs Canvas.Background

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/Win2D#105]
What's the difference between `Canvas.ClearColor` and `Canvas.Background` ? When would I pick one over the other?

**Comment by shawnhar** [comment]
The short answer is you should always pick ClearColor.

The Background property is inherited from XAML UserControl, and not used by Win2D.  We would hide this if we had any way to do so.

We considered having Win2D reuse the existing XAML Background property rather than adding its own ClearColor, but that doesn't really work because Background can be any XAML brush object, and we have no way to render arbitrary XAML content onto a Win2D surface.

Leaving open to track that we should explain this in the Win2D docs.

**Comment by shawnhar** [comment]
Improved docs in Win2D 0.0.22  (released today):

http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_UI_Xaml_CanvasControl_ClearColor.htm
