### ISSUE TITLE
When does draw happen?

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/Win2D#107]
I'm working on an app within which users can correct the foreground segmentation of an object from a photo using their finger. Drawing the border around the segmented foreground is proving tricky. My algorithm to find segment border pixels is fast but then drawing a small white circle at each border pixel is slow. One solution I am exploring is to only redraw the region around the users touch so that the entire border does not need to be redrawn. I am doing this using [CanvasImageSource](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_UI_Xaml_CanvasImageSource.htm) following the [ImageSourceUpdateRegion](https://github.com/Microsoft/Win2D-Samples/blob/master/ExampleGallery/Shared/ImageSourceUpdateRegion.xaml.cs) sample in the ExampleGallery.

I call my `Draw(Rect region)` method in the `PointerMoved` and the `PointerReleased` event handlers, but the draw method's `CanvasDrawingSession` `FillCircle` and `FillGeometry` calls are only visible on screen in the final run from `PointerReleased` . Are these queued in some way before being executed?

**Comment by shawnhar** [comment]
How many circles are you drawing?   My instinct is that the circle drawing is itself likely to be the slow part (in which case we should look for ways to speed that up) rather than the relatively cheap screen update.

Are you sure you are calling Dispose on the CanvasDrawingSession (eg. via "using' statement) at the end of each draw operation?  That's the most likely reason for new drawing not appearing on the screen.

Doing drawing directly inside the pointer event isn't a great idea. though, because if input events are arriving faster than you can update the screen (which is likely) this just means you will get further and further behind on processing them.  It is usually for the pointer events to just store away the new state (so they can complete quickly and always keep up with new input) and then redraw the screen at periodic intervals, picking up all new input which could be merged from several different events each time you do so.  CanvasControl uses the CompositionTarget.Rendering event to trigger these periodic redraws.

**Comment by dumbledad** [comment]
About 1,500 circles, and the draw's taking about 200ms with this code in the draw method:

    foreach (var point in _BorderCircles)
    {
        args.DrawingSession.FillCircle((float)point.X, (float)point.Y, _BorderRadius, opaqueWhite);
    }

That code's not from the CanvasImageSource version. In that version the drawing *is* in a using block:

    using (var ds = _ImageSource.CreateDrawingSession(transparentBlack, (Rect)region))
    {
        DeriveBorderCirclesForRegion(region);

        var borderCircles = _BorderCircles.Where(point => region.IsIn(point));
        foreach (var point in borderCircles)
        {
            ds.FillCircle((float)point.X, (float)point.Y, _BorderRadius, opaqueWhite);
        }

        ds.FillGeometry(
            _DrawingRect,
            _InputImageBrush,
            _ForegroundMaskBrush);

        if (_PriorTouchPoint != null) ds.FillCircle((float)_PriorTouchPoint.Position.X, (float)_PriorTouchPoint.Position.Y, _TouchAdjustmentRadius, _TouchDiskColor);
    }

All that said I think you are spot on about queuing the changes from the pointer events. I'll investigate the CompositionTarget.Rendering event. Thank you.

**Comment by shawnhar** [comment]
200ms is slow enough that you'll definitely be falling behind on processing the input events.   Coalescing the draws should help a lot, but another thing to consider is if all your circles are the same size, try using a bitmap rather than rasterizing a vector circle shape each time.  That should be significantly faster.

**Comment by dumbledad** [comment]
You mention that CanvasControl uses the CompositionTarget.Rendering event to trigger periodic redraws. How frequent are they and do I need to do anything other than my usual subscription to the [CanvasControl.Draw](http://microsoft.github.io/Win2D/html/E_Microsoft_Graphics_Canvas_UI_Xaml_CanvasControl_Draw.htm) event?

**Comment by shawnhar** [comment]
Good to hear!
