### ISSUE TITLE
Issue concerning matrix columns and rows, possibly reversed?

### ISSUE THREAD

**Issue by zhakopian** [Microsoft/Win2D#108]
I'm using a 4x4 matrix in the Transform3DEffect function which has the translate values at M41 and M42. The translate values are typically at row1, column4 and row2,column4 for x and y translates, which according to the documentation, should be M14 and M24 instead. When I put these values into M14 and M24, I don't get the desired results, while I do if I'm at M41 and M42. 

Could somebody help clear this up for me? Is the documentation wrong or is there something going on in my program causing it to work when it shouldn't?

This is the documentation I'm referring to http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Numerics_Matrix4x4.htm

**Comment by shawnhar** [comment]
The documentation is correct, as is your code that is working - the problem is with your expectation of how the matrix data should be laid out.  There are many different conventions for how matrix data can be organized in memory.  The Windows Runtime uses row-major format both for notation and memory layout, with row vectors and pre-multiplication ordering.  It sounds like you are used to working with column-major matrices and/or column vector format, which uses a different notation (but produces equivalent end results).

If in doubt, check out for instance the code for the CreateTranslation method: 
https://github.com/Microsoft/Win2D/blob/master/numerics/DotNet/Matrix4x4.cs#L219
