### ISSUE TITLE
How to get default line spacing

### ISSUE THREAD

**Issue by zhakopian** [Microsoft/Win2D#111]
I want to be able to modify line spacing in the text in my program. When I use certain values, the text rendering will start above its bounding rectangle like so 

![issuespacing](https://cloud.githubusercontent.com/assets/3682141/8365019/55419146-1b3f-11e5-9d04-6cf1761359e0.png)

I wanted to get the default to use as a sort of minimum that one could have because i'm assuming everything beyond it will render properly, but the default LineSpacing that is found in CanvasTextLayout->LineSpacing is -1 which I can't really use to gauge off of.

What is the actual default LineSpacing that negative values find?

**Comment by damyanp** [comment]
http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Text_CanvasTextFormat_LineSpacing.htm

Negative values for line spacing say to use "default" line spacing.  This means that DWrite (the component that Win2D uses to layout the text) will calculate the appropriate line spacing based on the content of the text.  

Note that, in the case of CanvasTextLayout, this can't be calculated without examining the actual text involved and how it has wrapped (since multiple font sizes may be used in a single text layout).

Unfortunately we haven't yet exposed the parts of dwrite required to extract the font metrics that can be used to calculate the default LineSpacing in the same way that dwrite does, so this isn't currently possible in Win2D without writing C++ interop code.

We have an entire section on our [backlog](https://github.com/Microsoft/Win2D/wiki/Backlog) for "Richer text support", and exposing font metrics will be part of this.  I'm also going to add an item to capture adding a sample or documentation for performing the same calculation as dwrite.

(As this is now in the backlog I'm going to close this issue - please do feel free to reactivate if you have any more questions)
