### ISSUE TITLE
Recommended Diagnostic Tools?

### ISSUE THREAD

**Issue by hapdisney** [Microsoft/Win2D#117]
First of all: great job.  Win2D is giving us graphics/drawing options for our app that we never thought were possible!

I installed [Visual Studio Graphics Diagnostics](https://msdn.microsoft.com/en-us/library/hh873207(v=vs.140).aspx) and was able to capture frame/draw call information when I use an CanvasAnimatedControl but when I use a regular CanvasControl and capture a frame, I get "this frame has no events".  (Keep in mind that I'm running VS2015 RC and Win10 build 10162 and maybe this problem only occurs on one machine)

The documentation clearly indicates the tooling offers limited support for Direct2D.  Does the Win2D team have other diagnostic tools you could recommend?

Thanks for all the time/effort you are pouring into Win2D!

**Comment by shawnhar** [comment]
Unfortunately we don't have any diagnostic tools other than the Visual Studio Graphics Diagnostics, and as you have discovered those are currently geared up for D3D debugging rather than higher levels like D2D or Win2D.  In some cases this tooling can partially work with Win2D/D2D rendering, but it will only display the resulting D3D level calls rather than the original higher level things done by the app, which isn't as useful as it could be.

The problem with CanvasControl capture is that graphics diagnostics tries to capture one "frame" of rendering, and it defines a frame as being the interval between one Present call and the next.  This works for CanvasAnimatedControl, which draws to a swapchain and calls Present after every Draw, but CanvasControl never calls Present at all!  It just draws onto a shared surface which is then handed across to the XAML compositor, so the capture tools never see their "end of frame" event and thus never realize that the app is done drawing.

**Comment by shawnhar** [comment]
Sorry I don't have a better answer for you on this!   Closing the issue as we have no immediate plans to improve this area.
