### ISSUE TITLE
Why not to enhance Geometry API of WinRT?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/Win2D#130]
I don't understand why do you to this but still has not enhanced WinRT Geometry API to the level of WPF?
In WPF I could do with Geometry a lot of cool things in contrast to WinRT where Geometry can nothing.

**Comment by damyanp** [comment]
Are there any particular examples of things you're thinking of here?  Any specific requests we can track as a backlog suggestion.

**Comment by xperiandri** [comment]
Well, if you can affect WinRT API developers backlog it would be nice to bring all the stuff of WPF Geometry class into Windows Runtime.
If I use WFP I could perform my task from issue #129 with built in APIs of Geometry class without referencing any other assembly.

**Comment by shawnhar** [comment]
What specific APIs does the WPF geometry class provide that would make this task any easier than it is using Win2D?   WPF geometry API is actually very similar to what Win2D provides...

**Comment by xperiandri** [comment]
Yes, they are almost the same.
But they:
* use all double as a primary numeric type
* are portable (I could port my code to WPF and have desktop app with the same functionality)
* work natively with UI elements. In WPF I can create 2 geometries, combine them and put into a Path and all this can be done in XAML
* StreamGeometry which is very convenient for custom shapes building

**Comment by shawnhar** [comment]
I'm going to close this issue and ask that you please create a separate issue for each specific point that you want to discuss.  Having one issue with many different requests tangled up in it gets very confusing to keep track of the issue status and hard for us to know which parts we still need to respond to.

At first glance, it seems to me that some of the things you ask here are already in Win2D, some are broader platform strategy questions rather than API features, and some are good conversations that we would love to hear your feedback on.  But let's use a separate thread for each of these different conversations.
