### ISSUE TITLE
Convert InkStroke to true geometry

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/Win2D#133]
I want InkStroke to be converted to true geometry using pressure data.
Windows.UI.XAML.Media.Geometry would be greate
However Microsoft.Graphics.Canvas.Geometry.CanvasGeometry would be nice too.

**Comment by shawnhar** [comment]
I don't think there is any way to read the width of the ink segments back from the inking APIs, but you can convert the ink path to Win2D geometry by using InkStroke.GetRenderingSegments (and setting the FitToCurve property as described in InkStroke docs), then passing the resulting Bezier segments to CanvasPathBuilder.AddCubicBezier.

**Comment by xperiandri** [comment]
Actually I do this now.
But as we have pressure level in a stroke we can adjust every segment to it.

**Comment by shawnhar** [comment]
I can't see any way to do this with the inking APIs, but will follow up with the ink team to find out for sure.

**Comment by shawnhar** [comment]
It turns out there is a way to do this, but it will require you to interop to a bit of C++ code in order to access Direct2D interfaces that are not available in WinRT:

In WinRT:
- CanvasDrawingSession.DrawInk into a CanvasCommandList

Then in C++:
- Interop from the CanvasCommandList list to a native C++ ID2D1CommandList
- Call ID2D1CommandList::Stream, providing an ID2D1CommandSink2 implementation
- In your ID2D1CommandSink2.DrawInk handler, call StreamAsGeometry on the provided ID2D1Ink

**Comment by xperiandri** [comment]
Thanks for investigation.
It is great that this is possible.
I hope that you will include this into backlog.

**Comment by shawnhar** [comment]
Win2D 1.9.0 (released today) adds a CanvasGeometry.CreateInk method.

**Comment by xperiandri** [comment]
Cool! Thanks!
I will try it soon.
