### ISSUE TITLE
Zooming with CanvasVirtualImageSource

### ISSUE THREAD

**Issue by SebastianStehle** [Microsoft/Win2D#136]
Hi, I had a look to CanvasVirtualImageSource. Is there an option to support zooming with correctly scaled graphics? In the sample the text becomes very ugly ;)

**Comment by shawnhar** [comment]
Applying a scale transform to a virtual image source will perform bitmap scaling on its contents, the same as the other Win2D controls.  There is no built-in support for re-rendering at different zoom levels, but at some point we may add a sample showing how to do that.  The basic approach would be to cycle through two or more virtual surfaces, and resize/re-render the next one for each new zoom level that is selected.

**Comment by SebastianStehle** [comment]
The SwapChainPanel supports the CompositonScaleChanged (https://msdn.microsoft.com/en-us/library/windows.ui.xaml.controls.swapchainpanel.compositionscalechanged.aspx) event, I have no idea how to implement it with VirtualImageSource

**Comment by shawnhar** [comment]
When a XAML scroll view is zoomed, it applies a scale transform to its children.  When you put a virtual image source inside the scroll view, that transform results in bitmap scaling (because the virtual image source is a bitmap rather than vector type of object).

Sometimes that's the right behavior, but in other situations you may prefer to re-render the contents of the virtual image source (generating a new bitmap image) at the new zoom level.

_Disclaimer: I haven't actually tried this yet_ but I suspect a good approach would be:

- Listen for the ScrollViewer.ViewChanged event (likely only when !IsIntermediate to avoid constant resizing during a zoom interaction)
- Cancel out the automatic scaling applied by the scroll viewer by setting an inverse scale as the RenderTransform on your image source (you're going to scale the contents of the bitmap, so don't want the bitmap itself to get scaled a second time)
- Resize the image source to fit the new zoom level
- Redraw its contents at the new zoom level

This will probably not transition smoothly as the RenderTransform change, resize, and redraw may not all arrive on the display simultaneously.  To avoid visual glitches, it will probably need two image sources, so you can leave the old one (with contents drawn at the wrong zoom level and then bitmap scaled) on the display while preparing a new one at the new zoom level, and then only flip over (hiding the first and showing the second) after the new contents have been drawn.

**Comment by SebastianStehle** [comment]
The problem is that the sizes can become very large and therefore it is very slow. I have the same problem with my example.

E.g. when I have a render area of 1000x1000 pixels and the same window size I have to render it at 5000x5000 pixels just for zooming. Makes no sense.

**Comment by shawnhar** [comment]
You never need to render more pixels than are on your display.  If you zoom in a long way, your virtual surface gets very large, but you only have to actually render the part of it that is visible based on the current pan position (this is where virtual surfaces come in, unlike a regular CanvasImageSource where you do have to create the whole very large image in one go).   Or when you zoom out so the whole thing is visible, then you do need to render the entire image, but at the same time you can resize it to be physically smaller due to the lower zoom level.

**Comment by SebastianStehle** [comment]
Ah, you are right, this should work :)  ... You also have set the transformation matrix of your drawing session with the zoom factor, otherwise all your content becomes too small.

I tested your approach. In theory it works fine, but there happen a lot of strange things. It would be awesome, if you can prepare an example for it. I think this matches to the usage of the virtual surface, e.g. maps very well.

**Comment by axorth** [comment]
The zooming behavior works except for some reason the scrollview keeps moving to the top left soon as I release my finger. Am I missing something?

            <ScrollViewer Grid.Row="1" Grid.Column="0" ZoomMode="Enabled" MaxZoomFactor="30" IsDoubleTapEnabled="False" x:Name="scrollView" HorizontalScrollMode="Enabled" VerticalScrollMode="Enabled"  >
                <canvas:CanvasControl x:Name="gridCanvas"  Draw="canvas_Draw" Width="{Binding ActualWidth, ElementName=canvasColumn}" Height="{Binding ActualWidth, ElementName=canvasRow}" ScrollViewer.VerticalScrollMode="Enabled" ScrollViewer.HorizontalScrollMode="Enabled"/>
            </ScrollViewer>

**Comment by damyanp** [comment]
@axorth - I think that this is a different issue to #136?  Could you open a new issue, and post a more complete code sample please.  (I suspect that binding the width and the height may be interfering with the zoom)

**Comment by shawnhar** [comment]
See the Mandelbrot example (new in 1.9.0 version of Example Gallery) for a working example of how to zoom using ScrollViewer and CanvasVirtualControl.
