### ISSUE TITLE
Need CanvasGeometry.CreatePolyline method

### ISSUE THREAD

**Issue by t-sch** [Microsoft/Win2D#137]
Hi,
I just saw that the CreatePolygon method automatically closes the stroke. If I don't miss something there is no way to 'bulk add' a point array to an open polyline.
Thanks,
Thomas

**Comment by damyanp** [comment]
Yes, there isn't currently a way to do this.  I've added it to our backlog.

**Comment by damyanp** [comment]
Note that in the meantime you can easily add a helper method in your own code to use CanvasPathBuilder and AddLine to create a polyline from a point array.

**Comment by t-sch** [comment]
Thanks.
I didn't implement that yet because I wanted to get an idea of the final performance. I assume removing the last line won't change that as much as the workaround.

**Comment by damyanp** [comment]
I'd expect them to have the same performance.  CreatePolygon (and CreatePolyline when it is implemented) is a wrapper and would be virtually the same as implementing it yourself in C#.

**Comment by shawnhar** [comment]
The Win2D team discussed this suggestion during sprint planning this morning, and decided we would be happy to accept a CreatePolyline implementation into Win2D if someone wants to implement this and submit a pull request.  However, we do not think this meets the bar for us to spend time implementing ourselves, as it is already possible to get the same result using CanvasPathBuilder, which makes this issue lower priority than too many other things already on our backlog.

I'm going to close the issue since we don't plan on doing any work to address it, but we'd be happy to accept the feature if someone else wants to pick this up.
