### ISSUE TITLE
Low GPU usage rate?

### ISSUE THREAD

**Issue by sweetim** [Microsoft/Win2D#138]
I am developing a Universal Windows App on Windows 10, with Nvidia Geforce GT750M

I am trying to render 100000 circle in the `CanvasControl` each time the canvas changes size.

I found that my application is laggy whenever i resized, it about 2 second (~2s) before it could render all the circles.

I check using the diagnostic tool for the GPU usage, i found that the GPU usage is low, i have attached the screenshot here

![1](https://cloud.githubusercontent.com/assets/6851767/9424770/9b505808-4933-11e5-8175-3c5fd04ea48b.jpg)

and my code in the canvas_draw is below

XAML code
````XAML
 <canvas:CanvasControl x:Name="canvas_gpu" SizeChanged="canvas_gpu_SizeChanged" Draw="canvas_gpu_Draw"/>
````

C# code
````C#
//draw handler
private void canvas_gpu_Draw(CanvasControl sender, CanvasDrawEventArgs args)
        {
            foreach (var item in this.points) {
                args.DrawingSession.FillCircle((float)(item.X * this.width), (float)(item.Y * this.height), 1, Colors.Red);
            }
        }

//canvas size changed event handler
private void canvas_gpu_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            this.width = e.NewSize.Width;
            this.height = e.NewSize.Height;
        }
````

why the GPU usage is so low? and it takes such a long time to render those circles?

P.S  i know is pointless to render all 100000 circles in the canvas, i could optimise to render points that users could see only, but that is not the point of this question (i want to know why it takes that long to render just 100000 circles, i believe the current GPU could easily render them at ease)

**Comment by SebastianStehle** [comment]
Think about the following: The GPU can only render triangles. To render 100.000 circles you need a lot of them ;)

**Comment by clandrew** [comment]
SebastianStehle's point is correct. Although Win2D uses the GPU to draw geometry, tessellation is CPU-side most of the time. There is a significant CPU tessellation cost that an app would be paying in order to render 100000 circles, since the edges are very densely curved.

You'll find the cost to be lower for simpler geometry, like rectangles, and lower still if anti-aliasing is turned off. 

If there is some geometry that you know you'll draw frequently. Win2D exposes the CachedGeometry object, so you can exploit the fact that you know you'll be drawing the same thing many times. With CachedGeometry, you pay a tessellation cost once to create it, but zero tessellation cost to draw it.

**Comment by damyanp** [comment]
Another possibility would be to render the circle to a CanvasRenderTarget and then use DrawImage to draw the render target.

I'm closing the issue as I think it has been addressed - feel free to reopen if you have further questions on this subject.
