### ISSUE TITLE
HLSL pixel shader integration possible

### ISSUE THREAD

**Issue by ferzkopp** [Microsoft/Win2D#140]
Is it possible to integrate an external pixel shader definition? i.e. I’ve got a few .fx HLSL files from my XNA days kicking around that I'd like to reuse.

**Comment by shawnhar** [comment]
Using arbitrary pixel shaders is not currently a feature of Win2D.

The backlog item "custom imaging effects" will likely enable some version of this, although we don't know exactly what it will look like or what the capabilities will be.  In order to operate within an image effect graph, there may be some restrictions on how the shaders need to be authored compared to full Direct3D.

**Comment by shawnhar** [comment]
We added PixelShaderEffect in Win2D 1.6.0.
