### ISSUE TITLE
relationship between RichEditBox and CanvasTextLayout

### ISSUE THREAD

**Issue by omanuke** [Microsoft/Win2D#161]
I'm planning to use RichEditBox as input control and use CanvasTextLayout to render input result.
Now I can copy some format from RichEditBox to CanvasTextLayout, but both appearance are still different like below.
-I have to set about 35% bigger font size to CanvasTextlayout.
-Line spacing is little bit different.
-Rendering tab differently. I get the value of RichEditBox.Document.DefaultTabStop and set it to CanvasTextLayout.IncrementalTabStop.

Anyway I'm happy if I can make appearance of both rendering similar.

I'm not familiar with Text Object Model of RichEditBox. 
Is there relationship between Text Object Model of RichEditBox and CanvasTextLayout? Or both component are completely different one?

And If you have time ,I want some document or samples about RichText rendering.
Regards,

**Comment by shawnhar** [comment]
I also know very little about XAML rich text, but in general:

1. CanvasTextLayout is not designed to be identical to XAML RichEditBox.  Ultimately they both use DWrite to rasterize fonts, so at least the basic fonts and sizes will be the same, but CanvasTextLayout is built on top of IDWriteTextLayout, while I believe XAML uses its own layout system.  Therefore you cannot expect exact matches for things like line spacing or tabs.

2. Font sizes will be the same if both are operating in the same coordinate system. Telepathic guess: are you running on a high DPI display but created your Win2D rendering without accounting for DPI (either explicitly selecting pixel units or perhaps using the lower level CanasImageSource API instead of CanvasControl which will hook up DPI for you), so Win2D is treating the size in pixels while XAML works in dips?

**Comment by shawnhar** [comment]
Closing as I believe this question is addressed - please let us know if you have further questions!
