### ISSUE TITLE
CanvasBitmap implements IDisposable but doesn't expose an IsDisposed member

### ISSUE THREAD

**Issue by r2d2rigo** [Microsoft/Win2D#169]
I'm working on an app that loads big images and I need to unload the current one when a new one is selected. I wanted to just dispose the existing image in the service that takes care of this so the controls can check for an invalid image and trigger the reload of the new one lazily. However, I have just found that `CanvasBitmap` doesn't have an `IsDisposed` member!

**Comment by shawnhar** [comment]
IsDisposed is not part of the .NET IDisposable interface, and is not provided by the .NET projection of WinRT (which maps IClosable -> IDisposable).  This applies to all WinRT APIs, not just Win2D.

I suggest setting your object reference to null immediately after disposing it, so you can check for null rather than IsDisposed.   This approach has additional advantages of allowing earlier GC of the .NET wrapper instance, and usually ends up simplifying code as it makes the not-yet-loaded-on-startup case identical to has-been-unloaded.
