### ISSUE TITLE
Bug: ShowPrintUIAsync doesn't honor await and returns true right away.

### ISSUE THREAD

**Issue by RobMc1964** [Microsoft/Win2D#171]
public async void PrintDrawing()
        {
            if (_printDocument != null) _printDocument.Dispose();

            _printDocument = new CanvasPrintDocument();
            _printDocument.PrintTaskOptionsChanged += PrintDocument_PrintTaskOptionsChanged;
            _printDocument.Preview += Preview;
            _printDocument.Print += Print;

            var printManager = PrintManager.GetForCurrentView();
            printManager.PrintTaskRequested += PrintTaskRequested;
            try
            {
                bool print = await PrintManager.ShowPrintUIAsync();
                // Returns true right away.  Doesn't await like it is supposed to and return true if you printed something or false if you press cancel.
            }
            finally
            {
                printManager.PrintTaskRequested -= PrintTaskRequested;
            }
        }

**Comment by shawnhar** [comment]
I believe that is the intended design for this API - completion of the async operation just means that the UI has successfully been activated, not that printing is complete.

Can you point me to any documentation that suggests otherwise?  (the MSDN page for this API doesn't specify at what point the operation is marked complete).

Note that PrintManager is provided by the Windows platform - it's not part of Win2D.

**Comment by RobMc1964** [comment]
Hi Shawn,
i looked at the Print XAML CS sample and shows the same behavior as you have implemented so there is no bug here.  I believe in the Win8.0 days print would async and return Boolean whether the user pressed Print(true) or Cancel(false).  I will comment and say overall win2d rocks  and especially printing.  the only gap I can see is there is no way to know if the user pressed "Print" or "Cancel" from the print dialog.
regards,
rob

**Comment by damyanp** [comment]
I checked with the owners of the ShowPrintUIAsync() and the behavior hasn't changed since Windows 8.  However, they pointed me towards the events on (PrintTask)[https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.printing.printtask.aspx] - specifically the (PrintTask.Completed)[https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.printing.printtask.completed.aspx] event.  This looks like it has the hook you'd need to determine when printing has finished (and why).
