### ISSUE TITLE
is there a way to see documentation from visual studio?

### ISSUE THREAD

**Issue by bdpy** [Microsoft/Win2D#175]
for example, by pressing F1 on a certain element and seeing it's documentation within visual studio help viewer?

**Comment by shawnhar** [comment]
We don't publish Win2D documentation to MSDN or integrate it with Visual Studio mostly because the agile nature of this project (shipping new versions every two weeks) doesn't fit well with the processes that would require.

We do include Intellisense .xml files in the Win2D NuGet package, so you should see API summary text in Intellisense.  For the full documentation, you can either view it online in your browser, or clone it locally as a set of HTML files.
