### ISSUE TITLE
Font metrics

### ISSUE THREAD

**Issue by mcdirmid** [Microsoft/Win2D#178]
I'm trying to implement a rich code editor in Win2D and I'm really missing font metrics capabilities in WPF. The only solution seems to use a CanvasTextLayout, but in aggregate this abstraction is way too high level since I want to do my own token spacing and syntax-specific wrapping. I can only create a CanvasTextLayout for *each* token, but this seems very wasteful since they have dispose methods and I guess are considered heavyweight; I would have to dispose of hundreds on each line refresh! 

Ideally, it would be nice if I could just get the bounds of a CanvasTextFormat value for some specific text string (which is basically how it works in WPF) without having to allocate a CanvasTextLayout object. Or is it reasonable to just treat them as transient objects to be created and disposed of frequently?

**Comment by clandrew** [comment]
Thanks for this question. Expanding the ways you can enumerate font metrics and customize text layout is something that's on our backlog right now, and happens to be something we're actively working on.

A custom text layout (future Win2D feature) would be a way to avoid creating one layout per token- then, many tokens can share the same layout and get spaced correctly, making it unlikely that your app would actually need WPF-like semantics to do what it's doing.

In the meantime, trying it out with one text layout per- is a reasonable thing to try, it might not be prohibitively heavyweight. As for metrics, it may help to take advantage of the fact that there is built-in metrics and hit testing for any substring within a text layout. And the other in-the-meantime option is to use interop with DirectWrite, and organize your content into one custom layout.

**Comment by mcdirmid** [comment]
I'm going with one CanvasTextLayout per token now and will let you know how it works out. Anyways, it should be fine for small files. 

I can't aggregate token formatting into one CanvasTextLayout per line since I'm mixing graphics in with text and doing custom wrap based on syntactic features (e.g. "(hello world)" would wrap together as parsed). In fact, CanvasTextLayout seems to have a specific use case in writing a simple rich text word processor and that's about it! I can't see how any kind of custom text layout abstraction can cover all or even most use cases. It definitely isn't going to work for a code editor. 

An ideal low-level flexible API is basically CanvasTextFormat + a way to measure specific text with it. Anything fancy beyond that is probably going to have to avoid DirectWrite anyways since it encapsulates all the math needed to kearn and word wrap.

**Comment by clandrew** [comment]
Ok, sounds good. Besides custom layouts, there is also a 'custom inline objects' feature on our backlog, which is a way of inserting arbitrary graphics or any custom drawing behavior into any part of text layout. It sounds like this is something very well-suited to your app. 

DirectWrite, which Win2D is built on top of, is full-featured and rich enough for serious word processing tasks, and then some. We're aiming for Win2D text formats and layouts to expose that same richness, and we're part of the way there. 

If you are using plain old DirectWrite, there's a very deliberate reason why you can't simply measure text using a text format. That reason is font fallbacks. The font face that will ultimately get used when you draw text actually depends on the text string itself. Sounds surprising, right? If you ask for, say, a glyph that isn't in the font specified in the text format, DirectWrite will apply its fallback logic and actually switch the font to one that has the glyph. This is great for making apps that work well on a wide variety of environments, but it also means the info in that text format is really just a list of 'suggestions'. 

It's impossible to make guarantees about fonts- and therefore, about metrics- until you actually have the glyphs on hand that you're trying to measure, and the exact context in which you're going to measure it. And typically, this is where text layouts come in. Since Win2D sits on top of DirectWrite, and we don't want to break font fallbacks, its API takes on much of the same shape.

For apps that need to do interesting layouts or spacing, I don't think the answer is necessarily to avoid DirectWrite's features, but rather to use them to get the right thing. DirectWrite's layout engine is extremely customizable and so is its kerning behavior. Between its layout and rendering- apps are free to use one, without the other. With Win2D, we hope to make all of this available.

**Comment by mcdirmid** [comment]
This is a good explanation, thanks! My comment about CanvasTextFormat was to combine it with a string so you know exactly what is being rendered (CanvasTextFormat + string = FormattedTextToken?), then you could make accurate predictions about what is being drawn. I'm a heavy user of unicode operators that I replace automatically in the string (e.g. => to ⇒), which seems to often change the font from "Segoe UI" to "Cambria Math" for that character (in WPF's FormattedText abstraction), but since the string is known, I assume its not really a problem, right? 

Anyways, I'll keep hacking away with the CanvasTextLayout approach and not sweat the performance yet. It seems to be working anyways :)

**Comment by clandrew** [comment]
I appreciate that extra info, it provides a bit better context of what your app is doing. While  FormattedTextToken might work for some specific things, text layouts are a built-in way of supporting that formatting + string pairing, and providing metrics that are guaranteed to match your drawn output. When adding those nice-looking unicode operator glyphs, it's good that you know that, say, U+21D2 is not in Segoe UI. But you don't have to know that. The font fallbacks should take care of it and switch the font to a visually-similar one that does have the glyph. So no, it's not a problem.

I'll close this issue because this seems to have addressed everything. But, definitely feel free to re-open if you run into anything else and we'll be happy to help.
