### ISSUE TITLE
cannot create C# WPF project with .NET and include Nuget package.

### ISSUE THREAD

**Issue by erichfrazer** [Microsoft/Win2D#208]
Create C# WPF project, try to reference NUGET package, get this:

Could not install package 'Win2D.win81 1.10.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

disappointed that such an obvious test doesn't work. Figures.

**Comment by frogger3d** [comment]
This project targets the WinRT platform. To use this library you should create a UWP project and include the nuget.

That said I'm wondering why Win2D does not extend its support to desktop projects. The Direct2D and WinRT api can be used from desktop applications as well.

**Comment by shawnhar** [comment]
Correct, Win2D only supports UWP and 8.1 Store applications, not Windows desktop apps.

Mostly this is because the WinRT platform does not provide any way to use out-of-box WinRT components from a desktop app.  Only built-in-to-the-OS WinRT APIs are available from desktop.

Also, WPF and XAML are pretty different in implementation, and Win2D is tightly integrated with XAML.
