### ISSUE TITLE
Question: Glowing lines

### ISSUE THREAD

**Issue by BubblegumYeti** [Microsoft/Win2D#212]
Any idea if this could be added or is there a good way in Win2D to achieve this?

**Comment by shawnhar** [comment]
Win2D image effects are perfect for this kind of effect, in particular check out the ShadowEffect class.  Draw your lines into a command list or rendertarget, then feed that as input to a ShadowEffect.

See the Custom Controls demo in Example Gallery, for instance.

**Comment by BubblegumYeti** [comment]
Ok that seemed to work nice. I am using a command list now. The problem is that I have plenty of line (vector game) of different colors and applying a bright glow to all of them is not bad but I would like to tweak them a bit so I can mix and match colors. Multiple command lists? And a different colored shadow to each of them?

Also is there some best practises in c# on how to efficiently manage all this to prevent memory leaks and/or GC.Collect slowdowns in my game? It is very cool to port my old vector games to Win2D (finally... couldn't really do it in XAML) and have them running in a few hours.

**Comment by shawnhar** [comment]
If you want to pick up the color of the input line rather than applying a different color, you could use GaussianBlurEffect instead of ShadowEffect, followed by a CompositeEffect to combine the original unblurred image over the top of the glow.

ShadowEffect = replace the color of the input image with a specified value, then blur it.

**Comment by shawnhar** [comment]
Closing issue as I think this has been answered - please reactivate if you need further help with it.
