### ISSUE TITLE
a mount of background thread tasks cause CanvasAnimatedControl fps lower

### ISSUE THREAD

**Issue by PatrickSCLin** [Microsoft/Win2D#214]
is numbers of multi thread task will effect CanvasAnimatedControl ?

I did some tests, using CanvasAnimatedControl , set the TargetElapsedTime to 30 fps,

preload 64 of d3d surfaces (each of them are w:640, h:360) when CanvasAnimatedControl loaded, 
then draw 64 of them in the Draw method and record the fps, it works perfect in 30 fps.

then I create 20 of System.threading.Timer to simulate multi thread working and CPU busy status,
actually the fps really lower when I doing 64ch h264 decode in background (decoding is fine enough)

timer runs with this code 

```
private void timeTask(Object stateInfo)
{
            long j = 0;

            for (int i = 0; i < 2000000; i++)
            {
                j += 1;
            }

            this.taskTimer.Change(TimeSpan.FromTicks(333333), System.Threading.Timeout.InfiniteTimeSpan);
}
``` 

anyways, what I done is try to simulate an environment which runs about 20 multi threads in background but CPU not full loading, just about always 60%, and CanvasAnimatedControl fps will be about 22 fps, 
is anything I can make CanvasAnimatedControl keeps the fps in 30fps ?

**Comment by shawnhar** [comment]
You can't generally rely on OS level thread preemption for coordinating large numbers of individual work items while maintaining realtime (ms rather than 10s of ms level) performance.

The game loop runs on a dedicated thread, and explicitly yields CPU if it has idle time in between ticks.  When you saturate the CPU with other work (by submitting more tasks than you have CPU cores, all of which are relatively long running) one of these tasks will be scheduled onto the same core that was previously running the game loop thread.  When the time comes for the game loop to perform another tick, it is then dependent on:

a. whatever work is currently using that core to complete
b. the OS deciding to schedule the game thread tick next, rather than one of your other pending timer tasks
c. or if the timer task takes too long, the OS might eventually decide to preempt it and let the game thread run instead - but this happens at way too low a granularity to maintain a steady framerate

The Win2D animated control runs its game loop on a dedicated thread to minimize interference from UI thread or XAML rendering, but if you want to combine this with large amounts of other expensive work, you are going to have to take much more explicit control over your work scheduling and timings.  Consider multiplexing all your video decode work onto a single (or couple) of threads while taking care to undersubscribe CPU cores so as to leave the game loop thread alone?   Or you might want to run decodes directly on the game loop thread.  Or maybe use CanvasSwapChain directly and do your rendering+Present at the end of a decode task, bypassing the game loop architecture entirely?

I don't know for sure which approach will work best, but I am pretty confident that just firing this kind of work at a bunch of separate threadpool tasks plus the default game loop thread isn't going to give great results.  You are attempting something way outside the norm here (in fact something I've never seen an app do before, so am not 100% sure is even possible!) so you're going to need to carefully control every detail of how you schedule and coordinate this work.

**Comment by shawnhar** [comment]
It might be useful to read about how game engines typically handle this kind of thing:

http://www.gamasutra.com/view/feature/130873/threading_3d_game_engine_basics.php

http://www.gamasutra.com/view/feature/130247/multithreaded_game_engine_.php

**Comment by shawnhar** [comment]
Closing issue as I believe this has been answered.
