### ISSUE TITLE
how CanvasSpriteBatch interop wtih D2D ?

### ISSUE THREAD

**Issue by PatrickSCLin** [Microsoft/Win2D#215]
I'm doing a video application with the option 2 which in previous question https://github.com/Microsoft/Win2D/issues/198

got some performance issues with multi channel, I found CanvasSpriteBatch in the documentation

I think maybe it's a solution for me, but CanvasSpriteBatch doest not support  CanvasVirtualBitmap

is possible to interop CanvasSpriteBatch with D2D ?

would like to get bitmap by using NV12 from D3D surface, then using CanvasSpriteBatch draw those bitmaps.

**Comment by shawnhar** [comment]
There is no interop between Win2D and D2D sprite batches because these are quite different things - Win2D adds a bunch of policy and state that doesn't exist in the lower level D2D sprite batch API, so interop between the two doesn't make sense.

But more importantly, sprite batch won't help you here because it can only draw bitmaps, not the various richer types of image like command lists, virtual bitmaps, or image effect graphs.  That restricted feature set is one of the things that makes it able to perform better than the more powerful DrawImage API.

If you are drawing something other than a bitmap, DrawImage is the way to go.
