### ISSUE TITLE
interop flickering when windows is resized

### ISSUE THREAD

**Issue by reneherrero** [Microsoft/Win2D#220]
Hi guys,

I have an app that will work great with Win2D via C#, but has a piece that is way brutal and needs to work close to the metal.  The interop functionality seems like the perfect solution but I can't figure out how to eliminate an annoying flickering when the window is resized.  Sometimes, the image just disappears completely.

I wrote a mini app that isolates the problem and included it here.  Can anyone see where I'm going wrong?  I'm stomped...

Thanks,

Rene

PS: Awesome work!!!  Win2D is very sweet...

[FlickeringApp.zip](https://github.com/Microsoft/Win2D/files/76493/FlickeringApp.zip)

**Comment by reneherrero** [comment]
I created a GitHub repo with the FlickeringApp code in case you prefer viewing it there:
https://github.com/reneherrero/FlickeringApp

**Comment by shawnhar** [comment]
There are two problems in your Renderer::Render method:

1. When you call d2dContext->SetTransform, this is overwriting any previous transform (assuming the transform was initially identity) but that is not the case when drawing to an atlased XAML surface like CanvasControl.  Win2D has already set a transform to draw to the right part of the atlas, so you need to concatenate your matrix with that existing transform rather than just replacing it.  When you use Win2D to change the transform, that's handled for you automatically, but if you drop down to native D2D you have to handle these details yourself.

2. You are leaking the solid color brush - allocating a new one every time the method is called but never releasing it.

**Comment by reneherrero** [comment]
You are the man! :+1: 	

Adding this fixed the problem:
...
// get the current matrix
Matrix3x2F originalTransform;
d2dContext->GetTransform(&originalTransform);
d2dContext->SetTransform(translation * scaling * originalTransform);

// draw whatever here

// restore the original transform to not break Win2D
d2dContext->SetTransform(originalTransform);

From what I understand, this approach should not break anything?  Is that a safe assumption or do you recommend an alternate approach?

Thanks a million,

Rene

**Comment by shawnhar** [comment]
Glad to hear you got it working!  This approach looks fine to me.  

It might also be ok not to bother resetting the transform, if you don't have any other drawing code after this, or if the next piece of drawing code code sets its own transform before drawing anything  (Win2D automatically adds in the XAML translation, so you can just unconditionally set the transform without needing this kind of read/modify/write like native D2D).

**Comment by reneherrero** [comment]
Thanks a million for the insight!  I wish I could buy you a beer... getting this type of support without paying fells wrong.

By the way, thank whoever made the decision to open source this.  Being able to read/step through the Win2D code is a HUGE help when trying to understand how to use the library...

Cheers!

**Comment by shawnhar** [comment]
Happy to help!  (not to mention relieved I was able to figure this out - thanks for sharing such a clear repro app)
