### ISSUE TITLE
Question: Erasing from a CanvasRenderTarget

### ISSUE THREAD

**Issue by kellylawson** [Microsoft/Win2D#221]
I'm creating a custom drawing app that draws to a CanvasControl using pen movement events from an InkPresenter set to InkInputProcessingMode.None, then drawing to a CanvasRenderTarget and drawing that result to the CanvasControl.  I'm struggling with erasing pixels from the CanvasRenderTarget.  I'd like to be able to take a CanvasGeometry returned from CanvasGeometry.CreatePath(), and erase those points from the existing CanvasRenderTarget.

I realize that the InkPresenter provides free stroke management along with erasing, but I need to have more control over the ink I put down than the InkPresenter allows so I can't see a way to use the stroke erasing functionality and maintain that control.  If I could just erase the ink from the CanvasRenderTarget along a CanvasGeometry, it would solve my problem nicely.  

Is there a way to do this?

**Comment by shawnhar** [comment]
A rendertarget is fundamentally just an array of pixels, each of which has a color.  All the different things you can draw onto a rendertarget a just variants of changing some of these pixels to different colors.

So 'erase' doesn't really make sense as a concept for a rendertarget.  You can change the colors of the pixels that were previously changed by that drawing, but to what?

Do you have a fixed background color that you want to erase them to?  (in which case just draw the shape again using that color)

Or do you want to erase them to transparent?  (in which case draw the shape using transparent color and Copy rather than SourceOver blend mode)

Or do you want to erase them back to whatever color these pixels used to be before the shape you are now erasing got drawn?  (in which case you need to save a copy of those pixel colors before drawing the shape)

Or maybe erase actually just means clear the rendertarget and then re-draw all your shapes except the one you don't want any more onto it?

**Comment by kellylawson** [comment]
Right - that makes sense.  I am looking to erase them to transparent, that's kind of what I was trying do do with a CanvasLayer.  My thought was to draw a transparent shape then blend it down to the rendertarget.  I didn't even notice the Blend property on the CanvasDrawingSession, setting that to copy works perfectly.

Thanks again, this was hugely helpful for me!

**Comment by valdirSalgueiro** [comment]
Hello, is there any sample how to do this? I tried creating a transparent color in the win2d sample and drawing with colorblend Copy in the draw method, but its just paints white.. am I missing something?
thanks!

**Comment by shawnhar** [comment]
Copying a transparent color value into your rendertarget will fill that portion of the rendertarget with transparent colors (assuming your rendertarget format is one that includes an alpha channel).   What happens next will depend on what you then do with the rendertarget - presumably you must be drawing it or processing it in some way that causes transparent to produce white, but you didn't give any detail of what your next step is.

**Comment by valdirSalgueiro** [comment]
My application is for drawing inside a video. In "edit mode" we use only inkcanvas and the stroke are later saved for video reproduction as an win2d effect inside the processFrame. I think I will have to change so it has also canvasControl form win2d as well in edit mode.

**Comment by valdirSalgueiro** [comment]
Hello i was able to implement it successfully, thanks very much :) I have one problem though, there is no feedback while erasing since the ink is not yet "dry" only after mouse up when the stroke is copied to vthe win2d canvas. Is there some kind of "erasing" feeback i could give?
