### ISSUE TITLE
Version 1.13.0 fails certification

### ISSUE THREAD

**Issue by eadordzhiev** [Microsoft/Win2D#224]
I have just updated the Win2D NuGet package up to the version 1.13.0 and got my app rejected because of the supported API test. Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/8386271/12125422/44b832de-b3fc-11e5-951e-22ff3eb45ee5.png)
It is likely to be related to commit 1b25fae5eef3fc761f877089ab8b6dd92a359075

**Comment by shawnhar** [comment]
Thanks for the report - we are looking into this now.

**Comment by shawnhar** [comment]
We figured out the issue and are validating the fix now.  Going to publish a new version of Example Gallery to make 100% sure it is good - if that works out, will publish a new NuGet package probably tomorrow morning.

**Comment by shawnhar** [comment]
Update: my attempt to publish a fixed Example Gallery failed cert with the same error you saw, but I think this was due to me building it on a machine with a stale NuGet package cache, where I had previously been testing some unrelated changes using an identical package version number.  #elementarydeverror  :-(

Will try again using the right Win2D binaries tomorrow morning!
