### ISSUE TITLE
v1.12 broke session-created bitmap rendering

### ISSUE THREAD

**Issue by BillHenning** [Microsoft/Win2D#228]
I just tried updating to the newer Win2D builds for our drawing app and suddenly portions of it aren't rendering correctly any more.  Think of the app like Photoshop.  It first draws a transparency grid, then each bitmap layer, then grid lines over the pixels (when zoomed in).  With v1.11 and earlier, everything is peachy.  But with v1.12 and later, any bitmaps we create within a Canvas.Draw handler using the CanvasDrawingSession won't render most of the time.  I say "most" because I do see them occasionally flicker up briefly sometimes as the mouse is moving and repaints occur.

The bitmaps that have the problem are for the transparency grid and grid lines.  Both are created using this sort of logic:

    using (var image = session.CreateBitmap(scale, scale)) {
      // Logic to draw on the image goes here
      using (var brush = new CanvasImageBrush(session, image)) {
        session.FillRectangle(new Rect(0, 0, width, height), brush);
      }
    }

Bitmaps for the "layers" on the other hand continue to work fine and are made using CanvasBitmap.CreateFromBytes.

Is this sort of drawing no longer supported?  I wonder if it's related to this change in Win2D:
"Fixed CanvasDrawingSession.Close to release all resources it was holding"

**Comment by shawnhar** [comment]
More likely this is due to changes in the bitmap implementation, but I can't tell exactly what you are doing from the info in this post.

Please share a repro app that shows the incorrect rendering (ideally simplified as far as possible to remove unrelated parts of your app) and we'll take a look.

**Comment by BillHenning** [comment]
Sample project is attached.  Rename to .zip.  It renders a grid with a text counter on top that 1-ups as you mouse over.  If you use v1.11 or earlier, the grid is always visible over the text.  If you use v1.12 or later, the text is always visible while the grid will flicker, sometimes showing and sometimes not.  Let me know if you see the same.

[Win2DCanvas.zip.txt](https://github.com/Microsoft/Win2D/files/80493/Win2DCanvas.zip.txt)

**Comment by shawnhar** [comment]
Thanks for the repro!

I don't see any flickering running this on my dev PC.  It looks like this, completely steady as the text animates:

![untitled](https://cloud.githubusercontent.com/assets/8118468/12158292/92fa2d6c-b48d-11e5-9860-31cc86d361a1.png)

I will try on my laptop (which has a different GPU) when I get home this evening.

Your code looks fine to me, but the way you are updating the bitmap does hit a codepath that changed implementation in this version of Win2D.  I'm wondering if you could be seeing a driver bug - what hardware are you seeing the flicker on?

**Comment by BillHenning** [comment]
Hi Shawn,

Odd, if it's working for you then it does sound like a driver issue.  I'm on a desktop Windows 10 x64 box with a GeForce GTX 980 and the latest drivers from NVIDIA.  It happens every time I run the app where those grid lines don't render most of the time when using Win2D v1.12 or later.

As another test, I ran it on my Surface and it worked as expected there.  Thus its definitely something with NVIDIA drivers.

Any suggestions?  I wonder if you can repro it on a machine with a NVIDIA card.

**Comment by shawnhar** [comment]
FWIW this works fine on my laptop (with Intel GPU) as well as my desktop (with dual AMD and NVidia boards - I tried on both).   I've asked other Win2D team members to run this as well to collect more data.

The change in this version of Win2D is that SetPixelBytes and SetPixelColors used to reach around D2D to the underlying D3D objects, and do:

1. Create staging surface
2. Map staging surface
3. Copy new bits into the staging surface
4. Unmap staging surface
5. CopySubresourceRegion from the staging surface to the real bitmap surface

In the latest version, instead these operations are implemented as:

1. ID2D1Bitmap::CopyFromMemory

Internally, this boils down to a D3D UpdateSubresource call.  So from a driver point of view, the difference is between CopySubresourceRegion and UpdateSubresource.  Both of these are very common operations so it's quite surprising to me that such a thing could be failing!

The reason for this change is to fix some hazards where D2D didn't realize the bitmap contents had changed, so DrawImage followed by SetPixelColors could end up with the DrawImage picking up those new colors, even though it happened before the set call.  Nasty bug, so it's not feasible for us to just go back to the older implementation.

Does your real app create a fresh bitmap during every Draw event?  What happens if you do this in CreateResources instead?

(afraid this is going to be tough for us to investigate at least until I can figure out how to repro the issue to debug it in more detail)

**Comment by BillHenning** [comment]
Yes, the real app worked similar to the sample I sent.

I tried a test of creating a CanvasBitmap and a CanvasImageBrush based on it in CanvasControl.CreateResources and then storing the bitmap and the brush as fields in my page.  Then in CanvasControl.Draw, I fill the background with that brush.  It flickers at the same times that the grid in my sample does, so most of the time, it isn't rendering as I move the mouse around.  To sum up, a bitmap/brush created in CreateResources is having the same issue as when I create it in Draw.

Any other suggestions?

**Comment by BillHenning** [comment]
I have more info after additional testing in case it helps you, but it could be what you are thinking already.  In the code below, I render a Red background and then draw a Green background on top of it, and the White counter text on top of that:

		private void CanvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args) {
			var session = args.DrawingSession;

			// Red background
			using (var image = CanvasBitmap.CreateFromBytes(session, new byte[] { 0, 0, 255, 255 }, 1, 1, DirectXPixelFormat.B8G8R8A8UIntNormalized)) {
				using (var brush = new CanvasImageBrush(session, image)) {
					session.FillRectangle(new Rect(0, 0, sender.ActualWidth, sender.ActualHeight), brush);
				}
			}

			// Green background
			using (var image = CanvasBitmap.CreateFromBytes(session, new byte[4], 1, 1, DirectXPixelFormat.B8G8R8A8UIntNormalized)) {
				image.SetPixelColors(new Color[] { Colors.Green });
				using (var brush = new CanvasImageBrush(session, image)) {
					session.FillRectangle(new Rect(0, 0, sender.ActualWidth, sender.ActualHeight), brush);
				}
			}

			// White text
			var format = new CanvasTextFormat() { FontSize = 300, FontWeight = FontWeights.Black };
			session.DrawText(counter++.ToString(), 100f, 100f, Colors.White, format);
		}

With v1.11, I always see a Green background and Red never shows, which is expected.  With v1.12 and later, I see Red background most of the time, with Green occasionally flickering visible on top but less and less so, the more I move the mouse to refresh.

Per the code, the difference is the raw byte array passed in.  Basically any updates made using SetPixelBytes/SetPixelColors may or may not work, causing this problem scenario.  If the raw byte array is completely filled in prior to the CreateFromBytes call, it works as expected.

I also tried creating a Blue CanvasBitmap and CanvasImageBrush in CreateResources similar to how Green is created, and rendering it on top of the Red/Green in Draw.  But it suffers the same issue as Green where it flickers.

**Comment by shawnhar** [comment]
> To sum up, a bitmap/brush created in CreateResources is having the same issue as when I create it in Draw.

Whoah!   To make sure I'm understanding right:

1. CreateResources creates a bitmap and calls SetPixelColors on it
2. CreateResources also creates a brush using this bitmap
3. Draw fills a rectangle using that brush
4. Draw is called many times, but CreateResources only once
5. Flicker means that not every Draw is producing the same result (even though the bitmap is not changing)

Is this the sequence you are seeing?

**Comment by BillHenning** [comment]
Yes, what you said is exactly right.  I've included the full updated MainPage code below.  The background should be Red (always works), with Green drawn on top, with Blue on top of that.  When fully working such as with v1.11, it will always show up in UI as Blue since that's the top layer.  With v1.12, It will mostly show up as Red, but then flicker Blue periodically.

	public sealed partial class MainPage : Page {
		
		private int counter = 0;
		private CanvasBitmap blue;
		private CanvasImageBrush blueBrush;

		public MainPage() {
			this.InitializeComponent();
		}

		private void canvas_CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs args) {
			// This is only ever called once during the test
			blue = CanvasBitmap.CreateFromBytes(canvas, new byte[4], 1, 1, DirectXPixelFormat.B8G8R8A8UIntNormalized);
			blue.SetPixelColors(new Color[] { Colors.Blue });
			blueBrush = new CanvasImageBrush(canvas, blue);
		}

		private void CanvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args) {
			var session = args.DrawingSession;

			// Red background
			using (var image = CanvasBitmap.CreateFromBytes(session, new byte[] { 0, 0, 255, 255 }, 1, 1, DirectXPixelFormat.B8G8R8A8UIntNormalized)) {
				using (var brush = new CanvasImageBrush(session, image)) {
					session.FillRectangle(new Rect(0, 0, sender.ActualWidth, sender.ActualHeight), brush);
				}
			}

			// Green background (has issue)
			using (var image = CanvasBitmap.CreateFromBytes(session, new byte[4], 1, 1, DirectXPixelFormat.B8G8R8A8UIntNormalized)) {
				image.SetPixelColors(new Color[] { Colors.Green });
				using (var brush = new CanvasImageBrush(session, image)) {
					session.FillRectangle(new Rect(0, 0, sender.ActualWidth, sender.ActualHeight), brush);
				}
			}

			// Blue background (has issue)
			session.FillRectangle(new Rect(0, 0, sender.ActualWidth, sender.ActualHeight), blueBrush);

			// White text
			var format = new CanvasTextFormat() { FontSize = 300, FontWeight = FontWeights.Black };
			session.DrawText(counter++.ToString(), 100f, 100f, Colors.White, format);
		}

		protected override void OnPointerMoved(PointerRoutedEventArgs e) {
			base.OnPointerMoved(e);

			canvas.Invalidate();
		}

		private void Page_Unloaded(object sender, Windows.UI.Xaml.RoutedEventArgs e) {
			if (canvas != null) {
				canvas.RemoveFromVisualTree();
				canvas = null;
			}

			if (blueBrush != null) {
				blueBrush.Dispose();
				blueBrush = null;
			}
			if (blue != null) {
				blue.Dispose();
				blue = null;
			}
		}
	}

**Comment by shawnhar** [comment]
This version is still creating bitmaps and brushes on every draw.  What happens if you move all three bitmap create operations into CreateResources?

Also, could you check what happens if you set ForceSoftwareRenderer = true on the CanvasControl?  That will help to narrow down whether this is really a driver bug.

**Comment by BillHenning** [comment]
If I comment out the Red/Green parts and only leave Blue, I mostly see Black bg with Blue flickering.  Thus, the presence of Red/Green as-is doesn't change anything.  And when putting a breakpoint in the CreateResources, that is only ever called once.

It all works fine with ForceSoftwareRenderer = true.

**Comment by shawnhar** [comment]
Ok, we managed to repro on a different machine and can now see the flicker.  This does look like a driver bug, but it's quite a specific one: creating a bitmap with all zeros as the initial data, then copying new pixel data over subregions of the bitmap, does not leave the resource in a proper state.

Suggested workarounds:

1. Pass some non-zero data when initially creating the bitmap (you could specify the entire grid at creation time, which would be more efficient too)
2. Or use a CanvasRenderTarget instead of CanvasBitmap (that allocates the surface in a different way which does not trigger the driver bug)

**Comment by shawnhar** [comment]
I filed an internal bug for the relevant team to investigate this driver problem.  It's probably not something we will want to workaround in Win2D (although that may change depending on the details of what they discover) so for now I suggest you change your app code to avoid hitting this bad behavior.

**Comment by BillHenning** [comment]
Thanks for the updated info.  I will try and change our code to do workaround 1, but in testing workaround 2, I replaced the various CanvasBitmap.CreateFromBytes calls with CanvasRenderTarget.CreateFromBytes and didn't see a difference in behavior.  Is that what you meant by that?

**Comment by shawnhar** [comment]
I meant "new CanvasRenderTarget".    There is no CanvasRenderTarget.CreateFromBytes method - you are picking up the CanvasBitmap one since CanvasRenderTarget derives from CanvasBitmap  (and C# has unfortunate rules about inheritance of static methods).

**Comment by BillHenning** [comment]
Ahh yes, I just caught that too.  Thanks, the "new CanvasRenderTarget" does work around it.

**Comment by shawnhar** [comment]
We have an active internal bug tracking the underlying driver issue that is causing this.  Meanwhile we decided it does not meet the bar for something we would want to work around in Win2D, since:

1. The problem only happens on a fairly obscure codepath that most apps will not hit
2. There is a straightforward workaround

I'm going to close this issue as we don't plan to make any Win2D changes here.

Thanks for the report!
