### ISSUE TITLE
Calling Invalidate() RegionsInvalidated fails

### ISSUE THREAD

**Issue by SebastianStehle** [Microsoft/Win2D#237]
Hi,

I use CanvasVirtualControl to draw an animated scene. Inside my RegionsInvalidated method i hase code like this:

     bool isCompleted = Arrange();
     foreach (Rect region in args.InvalidatedRegions)
     {
           Draw(region);
     }
     if (!isCompleted)
     {
           control.Invalidate();
     }

The Invalidate() method fails here, I dont have the correct message at the moment, it is already fixed. I just remembered it and thought that I should report it.

The following works:
     Dispatcher.RunIdleAsync(x => control.Invalidate()).Forget();

**Comment by shawnhar** [comment]
Please share a (simplified as far as possible) repro app that shows the problem.

**Comment by SebastianStehle** [comment]
Sure: https://github.com/SebastianStehle/Win2DRepro ... i just realized that it depends on the position where you place the Invalidate() at.

**Comment by shawnhar** [comment]
Cool, I see the failure now too.  As you say the key is where the call to Invalidate occurs - this is not valid if you do this inside the CreateDrawingSession block.

I think this is by design.  It's a behavior that Win2D inherits from the underlying XAML virtual image source implementation, and although we could do work to change it by automatically deferring the invalidate operation, I don't see enough value in that to justify the complexity.

Thanks for the report, and excellent repro!  It's always good to check that there isn't anything more serious/unexpected going on.

**Comment by SebastianStehle** [comment]
But a nice exception would be awesome
