### ISSUE TITLE
Apply opacity mask to xaml control

### ISSUE THREAD

**Issue by bgulrich** [Microsoft/Win2D#243]
Is there a way to apply an opacity mask to a xaml control?  For example, I'd like to create a Win2d enabled custom control that could wrap a scrollviewer and fade the top and bottom edges of the scrollviewers content using an opacity mask so that as you scroll down through a list of items, they appear to fade out to the top and fade in from the bottom.

If this is possible, could you point me to some sample code?  Thanks!

**Comment by shawnhar** [comment]
I don't believe this is possible in any reasonable/efficient way.

These two pieces of software are connected the opposite way around.  First Win2D draws into surfaces, then its output is passed across to the XAML compositor (as a surface image source or swapchain) to be included in the XAML rendering process.  XAML can combine Win2D drawing output with its own graphics using any of the clipping and blending options that are supported by XAML, but because the Win2D drawing happens before the XAML part, there is no way to do this the other way around and feed XAML drawing output into Win2D as one of its inputs.

The unreasonable way to do this would be use XAML render to bitmap functionality, and transfer the resulting bytes across into Win2D.  This will be very expensive, though, and I think not a good option for realtime interactive UI.

**Comment by bgulrich** [comment]
Thanks so much for your quick response.  You saved me a lot of investigation time!

**Comment by shawnhar** [comment]
Closing issue as I believe the question has been answered.  Feel free to reactivate if you have further questions.
