### ISSUE TITLE
Concistancy in CanvasTextLayout

### ISSUE THREAD

**Issue by edauphin** [Microsoft/Win2D#244]
Hello,

I'm not sure the behavior I face is a bug, or a feature that I do not understand.

I'm using two different method to have glyphs:
`textLayout.DrawToTextRenderer(glyphRunsGetter, 0, 0);`
and 
`textLayout.ClusterMetric`

In the first method, I expected to have the method `DrawGlyphRun` callled the same number of time that the number of ClusterMetric.

I know some utf16 characters are not printable, in this case the method `DrawGlyphRun` is called with the parameters `CanvasGlyph[] glyphs` with the `null` value, but in some case the method is completly ignored.

I join some sample code, that make more senses that my not clear explanation.
[MainPage.xaml.cs.txt](https://github.com/Microsoft/Win2D/files/97158/MainPage.xaml.cs.txt)

So can I use the method `DrawGlyphRun` to count my glyphs ? It's a bug on the weird characters ?

Thanks in advance,
BR.

**Comment by clandrew** [comment]
Ok. In your example, it's comparing the number of glyph runs to the number of clusters. These are, in fact, different things, and they're expected to be different.

A cluster is usually thought of as "one caret position" in a piece of text. 
For example:
'A' is one cluster. It's one code point.
'AB' is two clusters.
'ö' is one cluster. Even though, it's two code points. (U+006F, U+0308). The two dots are a separate code point.
A cluster is best thought of as 'one caret position', since it can include a 'central' glyph plus any combining marks, like accents.

A glyph is part of a cluster. The font decides how to divide a piece of text up into glyphs.

A glyph run is a group of glyphs which all have the same formatting, and they're all drawn in a line. Adding a line break can mean your text is drawn in two glyph runs, instead of just one. Changing formatting options, such as font weight, can also cause text to be drawn in multiple glyph runs.

I haven't run your example, but I noticed it draws to a 5x5 sized layout box, making it likely that line breaks are being added. If not for that, it's very likely the text would all be drawn in one glyph run, and nmbGlyph would equal 1.

**Comment by edauphin** [comment]
Thanks for the answer, I quite more understand what is done by Win2D.
So the 5x5 layout box and the not taking in account the number of glyph in a glyph run was two mistakes I made in the sample I provide you.

For my problem, I do understand what happens if two not printable characters are followed in a single string. I have only one call to the `DrawGlyphRun` with the paramater `glyphs` to null and two clusters each with zero width size. 

Thanks for all
