### ISSUE TITLE
Just a question: Xamarin compatibility

### ISSUE THREAD

**Issue by FrancescoBonizzi** [Microsoft/Win2D#285]
Please forgive me if the question has already been asked, or if the answer is obvious.
Is there any possibility to get Win2D be compatible with Xamarin projects?

**Comment by shawnhar** [comment]
That would be a massive undertaking, because:

a)  Win2D is a WinRT API, but I do not think Xamarin has full support for WinRT  (I could be wrong about this, though - not my area of expertise)
b)  Win2D is a thin wrapper on top of Direct2D and DirectWrite, which are not available on most of the platforms that Xamarin targets.

**Comment by SebastianStehle** [comment]
You can try this project: https://github.com/praeclarum/NGraphics ... it has less features than WinRT but can be used for cross plattform development.

**Comment by FrancescoBonizzi** [comment]
Understood. Thanks a lot!
