### ISSUE TITLE
Guidance on accepting input over a large CanvasControl

### ISSUE THREAD

**Issue by BillHenning** [Microsoft/Win2D#29]
Hello, I know that for your current sprint you are working on some code related to swap chains.  I'm admittedly a newbie to DirectX so your Win2D wrapper has been great thus far in making it easier for us higher level people to use it.  I was hoping to get some guidance on how to handle scenarios of accepting input in a performant way over a large CanvasControl.

At the moment, I'm rendering several large screen-filling graphics in a CanvasControl in its Draw method.  I have the CanvasControl in a WinRT template control of my own that overrides its OnPointerPressed, OnPointerMoved, etc. methods.  Basically as the user holds the left mouse button down, i'm trying to update the backing bitmaps and then repaint the CanvasControl.  While this works if I move the mouse very slowly, when I zip it around, I see that most of the pointer move events seem to get skipped.  If I skip invalidating the CanvasControl in my OnPointerMoved method and only do it in OnPointerReleased, then all my input seems to be gathered but I have no real-time feedback to the end user.

I suspect that what I'm trying to do might not yet be supported in Win2D, but could you tell me if it is and if not, is something coming that will allow me to continue to get full-fidelity performant input so that I can update my backing bitmaps, while asynchronously repainting too?  Any feedback you have on this subject or plans for the future would be helpful.

**Comment by shawnhar** [comment]
We published the CanvasAnimatedControl today, as part of Win2D version 0.0.11.   This provides both Update and Draw events  (unlike CanvasControl which has only Draw) which run on a dedicated animation thread as opposed to the main UI thread.  You can use the CanvasAnimatedControl.Input property to subscribe to input events which will be delivered directly to this same animation thread.

I believe this will be the right solution for your application - please reactivate this issue if you find otherwise!
