### ISSUE TITLE
Error message for NullReferenceException inside TrackAsyncAction is not descriptive enough

### ISSUE THREAD

**Issue by r2d2rigo** [Microsoft/Win2D#297]
How to reproduce:
- Create any sample project with a Win2D `CanvasControl` in XAML.
- In its `CreateResources` even handler, call `args.TrackAsyncAction`.
- In the body of the `Task`/`IAsyncAction`, access a null/non-initialized object or property.
- The resulting unhandled exception is of type `Exception` and the errors message is `Invalid pointer`.

This seemed a bit confusing at first as I thought I was experiencing threading problems, but in the end it was tracked to accessing a non initialized object. Can we have a more descriptive error message for this (`NullReferenceException` would do the trick)?

Also, the docs say that `TrackAsyncAction` should handle exceptions - but in this case it's going straight to the `UnhandledException` handler and crashing the app.

**Comment by shawnhar** [comment]
I see the same behavior for this API as any other unhandled exception coming from an async operation in a XAML app.  It bubbles up to the unhandled exception handler, which receives an UnhandledExceptionEventArgs with its Exception property containing a NullReferenceException:

![untitled](https://cloud.githubusercontent.com/assets/8118468/13574095/8308def6-e437-11e5-85a6-771fb781bd89.png)

It's usually a good idea to turn on Break when Thrown in your Exception Settings while debugging this kind of issue - that way the debugger will break as soon as the problem occurs, rather than letting the exception bubble out through various layers of intermediate that can make it hard to figure out where things originally went wrong.


> Also, the docs say that TrackAsyncAction should handle exceptions 

TrackAsyncAction catches all exceptions, but can only handle the ones it understands (i.e. exceptions due to lost graphics devices).  Exceptions that Win2D does not recognize indicate an app problem, so must be handled by the app.

**Comment by r2d2rigo** [comment]
Weird - I can't reproduce it on this machine, maybe there's something wrong with my VS/debugger config. Will update later when I can test on the problematic machine.

**Comment by shawnhar** [comment]
Could your VS on that machine be set to native debugging mode rather than managed or mixed?

**Comment by shawnhar** [comment]
Closing issue due to lack of repro information.  Please reactivate if you're able to figure out what was different about the machine where this occurred.
