### ISSUE TITLE
Win2D 1.16 STOWED_EXCEPTION_DELEGATE Microsoft.Graphics.Canvas.dll

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#298]
My Application has experienced such exception:

STOWED_EXCEPTION_DELEGATE_8000ffff_Microsoft.Graphics.Canvas.dll!Unknown at
1 Microsoft_Graphics_Canvas  0x58C28 

This comes from the App Insights from Microsoft's Store..

I cannot reproduce any problems so far with Win2D on my dev and test devices..

Best Regards,
Carl

**Comment by shawnhar** [comment]
Postmortem debugging of crash dumps that contain stowed exceptions can be a little tricky.  Couple of good articles on this:

http://blogs.msdn.com/b/ntdebugging/archive/2014/05/28/debugging-a-windows-8-1-store-app-crash-dump-part-2.aspx

http://stackoverflow.com/questions/28412334/trying-to-debug-windows-store-app-from-dump-files

If you can extract details of what the original exception is and what callstack it was thrown from, that will hopefully be enough to either identify what your app is doing wrong, or understand something about where/why Win2D is failing if this turns out to be a Win2D issue.

Good luck!

**Comment by eriadel** [comment]
Thanks Shawn. I will try to load pdb files from Win2D into our App Package and then we will see, if we will get more information about this what happen.. (if the issue will be reproduced in the future)

Regarding the call stack from the store, there's nothing about our App activity(no call stack including our calls), just that crash mentioned with only one line regarding the STOWED_EXCEPTION_DELEGATE..

Unfortunately, we cannot reproduce the issue with the tests set we use..
I'm afraid there's no crash dump we could analyse in the MS store for the UWP. So I will close this topic and come back to you, when we will have more useful information..
