### ISSUE TITLE
CanvasImage.SaveAsync and CanvasVirtualImageSource

### ISSUE THREAD

**Issue by Petititi** [Microsoft/Win2D#309]
Hello,
I want to save a big image (stored in a CanvasVirtualImageSource object) but I don't know how to proceed.
I tried to create a CanvasCommandList but without success...

Any idea?

**Comment by shawnhar** [comment]
An image can never be stored in a CanvasVirtualImageSource.  That is a UI type responsible for displaying very large images, but it doesn't store them - pieces of the image are generated on demand by the RegionsInvalidated event handler, and it is the responsibility of the app to be able to generate any requested piece at any time.

To save out very large images, you can draw them into a command list and then use CanvasImage.SaveAsync.  But note this will only work if your drawing limits itself to operations that are not limited by maximum bitmap size.  Most drawing calls are fine, as are image effects, but you can't do things like draw an intermediate result onto a rendertarget sized the same as your large image (because that rendertarget would be too big for the GPU).

**Comment by shawnhar** [comment]
Closing issue as I believe the question has been answered.  Feel free to reactivate if you need further info.
