### ISSUE TITLE
Framerate issue

### ISSUE THREAD

**Issue by Gool** [Microsoft/Win2D#311]
Hi, I have made a simple test app, that draws only circles on screen and moves them. Every couple of seconds phone emulator or Windows phone device misses some frames and the movement is jerky. What is causing that framerate drop? (Same thing happens when drawing lines or other objects on screen.)

    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        float width, height;
        int count = 10;
        List<Vector2> arr = new List<Vector2>();
        Random r = new Random((int)DateTime.Today.Ticks);

        private void CanvasControl_Draw(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args)
        {
            for (int i = 0; i < count; i++)
            {
                args.DrawingSession.DrawCircle(arr[i], 10, Colors.Red);
            }
        }

        private void CanvasAnimatedControl_Update(ICanvasAnimatedControl sender, CanvasAnimatedUpdateEventArgs args)
        {
            float x, y;

            for (int i = 0; i < count; i++)
            {
                if (arr[i].X < width)
                { 
                    x = arr[i].X + 1;
                }
                else
                {
                    x = 0;
                }
                if (arr[i].Y < height)
                {
                    y = arr[i].Y;
                }
                else
                {
                    y = 0;
                }

                arr[i] = new Vector2(x, y);
            }
        }
        private void CanvasAnimatedControl_CreateResources(CanvasAnimatedControl sender, CanvasCreateResourcesEventArgs args)
        {
            width = (float)sender.ActualWidth;
            height = (float)sender.ActualHeight;

            for (int i = 0; i < count; i++)
            {
                arr.Add(new Vector2((float)r.NextDouble() * width,
                    (float)r.NextDouble() * height));
            }
        }
    }

**Comment by shawnhar** [comment]
The phone emulator is not at all representative of performance on an actual device, so I wouldn't worry about what you see there.

Regarding glitches on your real device, there are several possibilities:

- Having the debug channel back to Visual Studio active can be surprisingly expensive, so make sure you are running without the debugger (ctrl+F5 rather than just F5) when examining performance.
- Some phone devices have extremely high pixel density displays, which can tax the GPU to animate smoothly even just doing very basic animation. If you are using such a device, you can increase GPU headroom by adjusting DpiScale on your CanvasAnimatedControl to reduce the number of pixels being rendered/copied.
- Phones have a lot of other things going on at the same time as your app, so even when the app does everything right, it's not always possible to 100% avoid dropped frames. This kind of glitch tends to be very obvious when looking at simple tests like moving just a few shapes in one-pixel-per-frame steps, but less so when looking at more complete and complex game - so it may not be worth worrying about as much as this kind of simplified test would make you think.

**Comment by Gool** [comment]
Ok, thank you for your reply. It seems that turning off some background tasks on my phone improve frame rate and fewer frame drops are visible. I wonder how background tasks has so high priority that it affects on running application on windows 10 phone. You are right that in some scenes the frame drops are not an issue.

**Comment by BrianBergh** [comment]
I too experience that sometimes there is a steddy frequency of frame drops, and sometimes it runs smooth. I cant figure out if thats because of the phone background tasks, or if its the win2d. Funny thing is that when using the XAML Animation in comparison, no frames are dropped, and it seems to run smooth all the time. To prove my point i made a open source sample here https://github.com/BrianBergh/Win2dTest

**Comment by JohnnyWestlake** [comment]
@BrianBergh The composition thread (which XAML animation uses) tends to offload the work to the GPU if independent animations are running if I'm not mistaken, (as does the Windows Composition namespace which is well worth looking into), and hence avoids getting caught up in ways Win2D code will always do - as the high level draw calls for Win2D still take place on the CPU every call before being offloaded to the GPU so there's constant reliance on CPU availability, even if there's no user input or you're using CanvasAnimatedControl etc.

(Although, Windows 10 did downgrade the performance of the composition thread - animations and easing functions do choke up in ways they never used too in Windows 8, but still better than anything you can do with constant CPU).

Certainly on a devices like the Lumia 950 family however, you'll want to ensure you're changing the DPI scale. Ever simple animated scenes don't hit 60 FPS when running on those 1440 x 2560 displays with the available processing power.

**Comment by shawnhar** [comment]
To be pedantic, there is always some CPU as well as GPU involved whenever graphics are being updated.  The main difference when using independent animations (whether via XAML or Windows.UI.Composition) is that rendering work is submitted by the compositor process (dwm.exe) rather than directly by the app.  That has some advantages in terms of smoothness and latency, but greatly restricts the available rendering capabilities compared to a rich client side API like Win2D.  Which is of course why we include both options in the platform...

**Comment by shawnhar** [comment]
I'm going to close this issue as we don't think there is any Win2D work to be done here.

**Comment by BrianBergh** [comment]
I don’t understand 90% of whas being said in these threads.

But what I do understand is this:

 

The Win2D api’s animatedCanvas control, is lagging no matter what I do (believe me, I’ve tried all). Unless I go hare-core nerd mode, and fiddle around with threads, and compositions.

In that case, I’d rather just use DirectX directly instead of using the wrapping API (Win2D).

 

And what I also understand is this:

The Win2D AnimatedCanvas control is mimicking the way XAN worked, and XNA was made as a directx wrapper for C# just as Win2D is. And XNA is running 100% smooth on both WP 7, 7.1, 8, 8.1 and 10 on both Lumia 925 and 950.

 

Now, what I don’t understand is this:

Why is it suddenly rocket science to make a simple object render from a to b smooth?

-          In my opinion (not to be negative, don’t get me wrong , I love your work), this is useless, at least for me :(

 

Keep up the great work, and ignore me. I’ll always find alternative way of getting my work done, just sad I have to :(

 

Regards

Brian Bergh

 

 

Fra: Shawn Hargreaves [mailto:notifications@github.com] 
Sendt: 30. marts 2016 19:21
Til: Microsoft/Win2D <Win2D@noreply.github.com>
Cc: Brian Bergh <brian.bergh@outlook.dk>
Emne: Re: [Microsoft/Win2D] Framerate issue (#311)

 

To be pedantic, there is always some CPU as well as GPU involved whenever graphics are being updated. The main difference when using independent animations (whether via XAML or Windows.UI.Composition) is that rendering work is submitted by the compositor process (dwm.exe) rather than directly by the app. That has some advantages in terms of smoothness and latency, but greatly restricts the available rendering capabilities compared to a rich client side API like Win2D. Which is of course why we include both options in the platform...
