### ISSUE TITLE
2 Crashes in DllCanUnloadNow()

### ISSUE THREAD

**Issue by eriadel** [Microsoft/Win2D#317]
STDAPI DllCanUnloadNow()
{
    auto &module = ::Microsoft::WRL::Module< ::Microsoft::WRL::InProc >::GetModule();
    return module.Terminate() ? S_OK : S_FALSE;
}

Symbol name    Crashes   Average daily  
Microsoft_Graphics_Canvas!DllCanUnloadNow     2     0.67

We can even reproduce this problem, but as mentioned I cannot load for strange reasons precompiled pdb file and tell you what exactly crashes and why.

For me function looks not secured - no null checks etc.. my first guess you can get a null "module"

For some reasons symbol name has appeared in the MS Store. (we didn't change the package)

Best Regards,
Karol

**Comment by damyanp** [comment]
I'm not sure where you'd hope to see null checks in a method that has no pointers in it....

If you can reproduce this problem then you should be able to get a crash dump that you can share with us (of course if you do this, please make sure you let us know exactly which version of the Win2D nuget package you were using).

**Comment by eriadel** [comment]
1.But you can expect most likely null reference there..

Anyway you have evidence from Microsoft's App Insight there's a problem in that function, so for some reason Win2D crashes there. We always use latest Win2D (1.16).

As I know sooner or later, if the error pattern will happen again and again App Insights should deliver us a crash dump. If you're not able to recognize potential root cause without crash dump, then we can close this one and come back next time with the dump, but this take many weeks.. and we observe 90% of our App crashes in Win2D.

I agree we just give you a little light now. But maybe you've seen similar issues recently..

Just let me know, if you need always a crash dump..

2. False alert, problem with crash we've reproduced was not connected with Win2D, but with another UWP native code. We still cannot reproduce locally crashes we see in the Store.

Cheers!

**Comment by damyanp** [comment]
I'm unconvinced that the issue is in DllCanUnloadNow.  

What I expect is happening is that the symbol resolver is looking at the exported symbols from Microsoft.Graphics.Canvas.dll (of which there are only a few - see https://github.com/Microsoft/Win2D/blob/master/winrt/dll/module.def) and picking the one nearest to the one it's trying to look at, which just happens to be DllCanUnloadNow.  By any chance do you see this multiple times in the same callstack?  If so, that would confirm that this is what is happening.

See also https://blogs.msdn.microsoft.com/distributedservices/2010/07/03/eventid-4196-troubleshooting-crashes-in-com-applications/ for a discussion of this sort of issue.

**Comment by eriadel** [comment]
We only see 2x the same stack trace.. but it only contains only this function(nothing else):

Microsoft_Graphics_Canvas!DllCanUnloadNow

For me it makes a little sense, cause we use CanvasAnimatedControl dynamically and we use RemoveFromVisualTree() method quite often, so maybe then (just my impression, nothing certain) this method is called and DLL is no longer used and gets unloaded. But you probably have more information than me, if this is possible scenario or not.

But whatever happen, then Microsoft should do something with App Insight infrastructure, cause it looks not so well..

If you have doubts we can close this topic and re-open, if the same issue will come back.
I work as a developer and architect since 8 years, so I know how it is when you do not get enough information. But you have to understand we cannot invest another 50k of $ in another game with Win2D, until we are sure it's stable and we can overcome issues easily.

Cheers!

**Comment by shawnhar** [comment]
I think this is the same issue as #314.  Agree with Damyan that the report is only talking about DllCanUnloadNow because it doesn't have symbols to understand where the crash is really occurring.  It's not plausible that it would actually be crashing inside this tiny COM stub function.

Let's use #314 to track getting proper symbols for Win2D, then we can see what the real crash is once that is resolved.

**Comment by eriadel** [comment]
No problem, most likely you're right. I cannot say if App Insights is correct, as we have only 2 months of experience with it, but in our cases was usually correct. I was thinking about kind of a race condition and possible null reference. Appreciate your support with 314# and I hope we will be able to obtain more useful information.
