### ISSUE TITLE
Perf issue

### ISSUE THREAD

**Issue by Petititi** [Microsoft/Win2D#318]
Hi Win2D team!
I'm currently trying to optimize rendering performance so I activated the log info using `CanvasDevice.DebugLevel = CanvasDebugLevel.Information;`.

I then spotted a probably wrong usage of `CreateLayer` function. I'm trying to do some clipping while drawing on a `CanvasRenderTarget`:
```C#
using (CanvasDrawingSession session = _backBuffer.CreateDrawingSession())
{
    var clip = session.CreateLayer(1.0F, CanvasGeometry.CreateRectangle(session, regionFloat));
    ...Do my clipped drawing
    clip.Dispose()
}
```

But I get this warning message:
`D2D DEBUG INFO - PERF - A layer is being used with a NULL opacity mask, 1.0 opacity, and an axis aligned rectangular geometric mask. The Push/Pop Clip API should achieve the same results with higher performance.`

What should I do to optimize my rendering pipeline?

Thanks!

**Comment by Petititi** [comment]
Juste a small update: would it be possible to add a CreateDrawingSession with a Rect area in order to clip rendering inside this rect?

**Comment by shawnhar** [comment]
Layers are the correct way to do this kind of clipping.  The perf warning is because you are using the CreateLayer overload that takes an arbitrary CanvasGeometry object, rather than the much simpler and faster version that just directly takes a clip rectangle.  You don't need a geometry here - just pass your rectangle directly to CreateLayer.

**Comment by Petititi** [comment]
Thanks for the advise! Sorry I didn't try this myself before asking for help here!
Thanks for your reactiveness!
