### ISSUE TITLE
Clarify tint on batch draw operation

### ISSUE THREAD

**Issue by Thraka** [Microsoft/Win2D#324]
The tint on a batch draw is a Vector4, but a color type does not seem easily transformable. How do we use tint with a color?

**Comment by FrancescoBonizzi** [comment]
In my case, I did:
private static Vector4 ToVector4(Color color)
{
    return new Vector4(
        (float)Color.R / 255.0f,
        (float)Color.G / 255.0f,
        (float)Color.B / 255.0f,
        (float)Color.A / 255.0f);
}

Francesco Bonizzi

Date: Tue, 5 Apr 2016 23:03:28 -0700

**Comment by shawnhar** [comment]
Francesco is exactly right, that's the canonical way to convert a Windows.UI.Color to System.Numerics.Vector4.

Same thing can be done a little more concisely (and potentially slightly more efficiently) by doing the divide as a vector rather than scalar operation:

```
    new Vector4(Color.R, Color.G, Color.B, Color.A) / 255.0f

**Comment by Thraka** [comment]
OK, thanks. That makes sense. The thing that really confused me was the example in the API docs that used a `new Vector4(2, 1, 1, 1)`.

**Comment by shawnhar** [comment]
The important thing to understand (and the reason that this parameter is a Vector4 rather than a Windows.UI.Color) is that this value is a tint that will be combined with the color of the bitmap - it's not a color value that will be drawn directly itself.  That combination is done by multiplying the bitmap color and the tint value together.  Depending what value you use for the tint, this could brighten the bitmap, or darken it, or change its opacity, or differently adjust the intensities of each color channel.

**Comment by Thraka** [comment]
Didn't it work that way in XNA?

**Comment by shawnhar** [comment]
XNA SpriteBatch also did a multiply operation, but took its tint parameter as a Color value. That was needlessly restrictive as it prevented doing things like increasing brightness of the bitmap color.

**Comment by Thraka** [comment]
Roger that. Thanks! Where are the API docs held? I can update with the example you posted

**Comment by shawnhar** [comment]
Win2D docs are built from the source tree alongside the code itself.  Input files mostly live in winrt\docsrc folder.
