### ISSUE TITLE
 Win2D Gallery Direct3D Interop Hololens and C#

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Win2D#341]
I really enjoy the Win2D Gallery app, it would be great that the teapot example get all ported to C#.
My technical question here is: Does Hololens render the teapot in holographic 3D or what does it do a flat render?

**Comment by shawnhar** [comment]
The teapot example uses C++ because it relies on the DirectX Tool Kit (https://github.com/Microsoft/DirectXTK) to draw the teapot, and DirectXTK is a native C++ API.

Doing the same thing in pure C# would be significantly more work for two reasons:

1. We'd have to build the teapot geometry and shaders to render it directly into the sample, which would distract from the point we are trying to demonstrate. The goal is to show how to interop between Win2D and Direct3D, without getting distracted by the details of how to use Direct3D itself.  Using DirectXTK lets us easily draw an interesting 3D shape while minimizing the amount of Direct3D code not directly related to how this sort of interop works.

2. To do this in pure C#, we'd have to use some other C# Direct3D binding (eg. SharpDX or SlimDX) - but we didn't want Win2D to take such a big dependency just for this one sample.

**Comment by shawnhar** [comment]
On your other question, there are special APIs for holographic rendering.  See:

* https://www.microsoft.com/microsoft-hololens/en-us/developers
* https://developer.microsoft.com/en-us/windows/holographic/app_model
* https://developer.microsoft.com/en-us/windows/holographic/directx_development_overview
* https://developer.microsoft.com/en-us/windows/holographic/rendering_in_directx

**Comment by shawnhar** [comment]
Closing issue as I believe these questions have been answered.
