### ISSUE TITLE
Question: Win2D vNext?

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#345]
Just wanted to know what's coming up in the future versions of win2d.

It has been more than a month since the last blog was published.

It would be great if you could let us know about any updates regarding win2d.

**Comment by shawnhar** [comment]
Hi Ratish,

The info from [this post](https://blogs.msdn.microsoft.com/win2d/2016/01/21/stabilizing-win2d/) is still basically accurate, except that since it was written we finished removing "experimental" status from all of the Win2D APIs.

Now that Win2D has caught up with the capabilities of the underlying Windows graphics platform, we are no longer rapidly adding features like during early development of this project.  The team is continuing to fix bugs whenever any are reported, and answering support questions from people using the API.  Beyond that, we'll be exposing new features in Win2D at such time as future versions of Windows add relevant capabilities to the platform beneath us.  This means our future update rate will look more like that for Windows as a whole (except that being open source means we can usually turn around bugfixes more quickly), rather than the rapid pace you saw while Win2D was still unstable during early development.

**Comment by ratishphilip** [comment]
Thanks a lot for the reply.
