### ISSUE TITLE
Drag and Drop CanvasGeometry?

### ISSUE THREAD

**Issue by Karlitos2312** [Microsoft/Win2D#356]
Hi, 
Is it possible to drag and drop a canvasgeometry?

I have a circle geometry on the canvascontrol, that I want to be able to longpress and drag to a new position on the canvascontrol.
Regards,
Karl.

**Comment by shawnhar** [comment]
Sure, but you will have to write the code to do that.

Win2D is an immediate mode graphics API.  That means it just draws whatever you tell it to, whenever you tell it.  It is up to you to maintain whatever state you need about what things should be drawn, where these things should be positioned, to change that state whenever needed (for instance in response to input events), and to redraw with your objects in different positions.

**Comment by Karlitos2312** [comment]
Hi,
Thanks for your swift response - can you elaborate on how I can draw an object on the canvascontrol of which I can attach events to or point me in the right direction.

**Comment by shawnhar** [comment]
You could look at the various Example Gallery demos, many of which respond to input in different ways - but be aware these are mostly written to show how to use Win2D drawing APIs rather than broader application state management and input event handling, so they may not be the clearest place to learn that.

This topic is really outside the scope of Win2D.  Perhaps it would make a good stackoverflow question?

**Comment by shawnhar** [comment]
Closing issue as I believe this question has been answered.
