### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by mandalorianbob** [Microsoft/Win2D#358]
I'm using Win2D to create a progress bar that has various awards on it. The progress bar itself is animated, and has "paging" where you can slide the entire progress track left or right while the bar stays where it is. The awards also shift with the progress track, and that's sort of where my problem lies.

I'm uncertain of a good way to include tooltips for the awards. 

First thought is to make some kind of XAML object that sits over the award and is otherwise transparent but has a tooltip on it. The problem is that the awards move as the user pages back and forth, which I think would make it pretty complicated. I'd have to sync the animation with XAML and then collapse it at the right time, detecting when it "went off" the page. 

The second thought is basically the hard way - detect if the mouse is over the award and draw a box and draw some text at the mouse cursor location.

I mean, I call it the "hard" way, but really it seems like they'd be about the same amount of work, although the latter could be generalized. I thought I'd post and see if anyone else has any ideas about how to do this. 

Thanks!

**Comment by clandrew** [comment]
I'm not a XAML expert, but I think XAML tooltips are best suited to when
* the specific thing they're tooltipping is being drawn and fully controlled by with XAML, and 
* they're shown in response to pointer input. [See these guidelines](https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tooltips). 

If the thing you're tooltipping is say, a particular ever-changing region of a XAML element like a part of a CanvasControl, it can be painful to get that to work. There's also the fact that I don't think this tooltip is behaving in the "standard" way. Tooltips don't normally scroll with content- even if something tooltipped is scrolled inside a ScrollViewer, the tooltip stays in one place, and gets dismissed automatically. Because of these requirements, I would go with the "hard" way.

**Comment by clandrew** [comment]
Hope this was some help. While that second option is called the "hard" way because you're taking ownership of more stuff, I think it would actually be a lot easier to implement given you don't need to make your app fight against normal XAML behavior.

Since I don't see any more action for us, I'll close this issue, but definitely feel free to reopen if you need anything else.

**Comment by mandalorianbob** [comment]
No problem. I don't really know what to ask about implementing something like hover states in Win2D, because I don't yet know what I don't know. When I circle back around to this, would you like me to re-open this topic or start a new one?

**Comment by clandrew** [comment]
As far as input state goes, you may want to look at the PointerPressed/PointerMoved event as they're used in ExampleGallery. 

More generally, though, Win2D is a graphics API only- and it does immediate-mode graphics, no scene tracking or state tracking of that sort. If you're comparing it to XAML, it's different from XAML in this respect. So, it's safe to say any scene state  (e.g., which of your elements are being tooltipped) should just be tracked in your app, and then it's as simple as just telling Win2D what to draw.

Doesn't matter hugely. Opening a new issue can be a bit easier for searchability conciseness.
