### ISSUE TITLE
How to use InkSyncronizer.EndDry on AnimatedCanvasControl.Update event?

### ISSUE THREAD

**Issue by tgckpg** [Microsoft/Win2D#360]
Actually I was fiddling with the Win2D Example Gallery. Was trying to change the InkExample to use the AnimatedCanvasControl. I was able to add some simple effects and get the ink animated. But I can't seem to let the ink to dry.

It throws an exception with something something INoMarshal. I guess this is because the EndDry is accessing something in the UI thread.

Do I just use the Timer in the UI thread to periodically check and call the EndDry. Or it there a better way to do this?

PS: Currently I am using calling Dispatcher.RunIdleAsync under the Update event.

**Comment by shawnhar** [comment]
An important piece of info here is exactly what operation this exception is coming from.

Most Win2D APIs can be called from any thread, but the majority of XAML and Ink APIs have UI thread affinity.  That will make it challenging to use ink from a Win2D animated control, which runs on a dedicated game loop thread.  You may be able to split up your code so the key ink operations happen on the UI thread, then your Win2D drawing on the game loop thread.  Or you can use dispatchers to move key operations back and forth from one thread to the other.  Either way will require careful attention to which operations are happening on which thread.

In general I suspect it would be easier to stick with CanvasControl rather than CanvasAnimatedControl when working with ink. Incoming ink input is directly tied to the UI thread, so I don't really see much advantage (just increased complexity) in moving your custom dry operations off to a different thread.

**Comment by tgckpg** [comment]
Thanks, I agree. I just found that using the InkCanvas to get an animated ink is not a good idea. So I'd just decided get the AnimatedCavasControl to have the PointerEvents and manually catch the points then have them drawn on the DrawEvent. Manipulating the points are much easier than the strokes.

I've yet another question about the BlurFilterEffect. Referencing the CoreWindow example. The blur effect does not seem to completely *wear off* as the time goes. I can see the imageBrush.opacity is multiplying 0.99f on each frame. But from the resulting image the opacity doesn't seem to be multiplied to ~0 but still fairly visible.

This is especially conspicuous when viewing it on the phone. But changing the opacity multiplier to 0.8f / 0.7f just makes it fade quicker. But still have that leftover mark. How do I solve this?

**Comment by shawnhar** [comment]
The CoreWindow sample uses a feedback rendering technique, where the output of each frame is fed as an input into the next.  If a system like this was evaluated with perfect numerical precision, modifying opacity would never entirely remove a previous image.  Each time it gets multiplied by 0.99f, the value gets smaller, but no matter how many times you do that it will never arrive all the way at zero.

The artifacts you see are because GPU hardware does not actually evaluate anything with infinite precision.  On a desktop GPU you are likely getting shader intermediate values evaluated as 32 bit IEEE float, while rendertarget contents use an 8 bit fixed point format.  On a phone the precision may be even lower (for instance, shader computations may not support true IEEE denormals).

Limited precision produces color banding and clear boundaries where values get truncated, and feedback algorithms tend to magnify the effect of such artifacts.  This is expected - implementing feedback techniques without any color banding requires much more attention to numerical precision than we bothered with for that sample.

**Comment by tgckpg** [comment]
Hmmm, so it is feedback techniques and color banding. I should google that.
Anyway, that was very helpful. Thank you! I am gonna close this issue now:)
