### ISSUE TITLE
CanvasControl.Content UIElement does not compose with canvas drawing

### ISSUE THREAD

**Issue by dtaylorus** [Microsoft/Win2D#362]
If I set the Content property of CanvasControl, I expect to be able to compose the specified child UIElement layered above and/or below the Win2D drawing primitives.

For example, I expect to be able to compose a filled rectangle with the text "Hello, World!" using the following code:

    var canvas = new CanvasControl();
    canvas.Draw += CanvasControl_Draw;
    canvas.Content = new TextBlock() { Text = "Hello, World!" };
    
    void CanvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args)
    {
        args.DrawingSession.FillRectangle(0, 0, this.ActualWidth, this.ActualHeight, Colors.CornflowerBlue);
    }

Instead, the TextBlock completely replaces the filled rectangle drawing, which looks like it is drawn to an image that is no longer in the visual tree.

This view composition functionality is supported by the iOS UIView class and the Android View class, which both have a virtual Draw method that can be overridden to enable custom canvas drawing primitives to be composed with any view.

This is a simple and powerful method for customizing the look of an existing UI control that has been sorely missed on the Windows XAML platform and makes some cross-platform UI scenarios extremely difficult on Windows.

For example, the [NControl](https://github.com/chrfalch/NControl) library takes advantage of this composition functionality to enable cross-platform custom controls on Android and iOS using [NGraphics](https://github.com/praeclarum/NGraphics) and [Xamarin.Forms](https://www.xamarin.com/forms), but has to resort to extremely inefficient methods of layering, removing, and re-layering child controls for each Draw update on the Windows platform.

Ideally, Windows XAML would have this primitive canvas drawing functionality built-in to the UIElement base class like Android and iOS, but thanks to Win2D there is now at least the potential of using the CanvasControl as an alternative base class to finally have similar functionality on the Windows platform.

I may be able to create this functionality with the existing CanvasControl by implementing a UserControl subclass with a private Grid panel that sandwiches the control content UIElement between two CanvasControl instances (one each for background and foreground drawing), but this would essentially turn every control into five controls, which seems very inefficient.

Please consider enabling an efficient implementation of this custom control composition functionality in Win2D to allow Windows to become a first-class citizen in the world of cross-platform owner-drawn controls.

Thanks!

P.S. I'd also love some feedback on the impact of potentially having an entire UI composed of these CanvasControl objects. I have no idea how much overhead is introduced by each instance of this control.

**Comment by dtaylorus** [comment]
Note that if [Windows Bridge for iOS](https://developer.microsoft.com/en-us/windows/bridges/ios) has an accurate implemention of UIView on XAML, then that team must have figured out how to solve this problem efficiently. Maybe [here](https://github.com/Microsoft/WinObjC/tree/master/Frameworks/UIKit/StarboardXaml)?

**Comment by shawnhar** [comment]
The right way to compose XAML and Win2D content on top of each other is to layer one or more XAML controls on top of or behind your Win2D CanvasControl, using a Grid or other XAML layout to control their arrangement.

Changing the CanvasControl.Content property does not work because CanvasControl is itself already using that same Content setting to display the underlying CanvasImageSource which contains your Win2D rendering.  CanvasControl is just a helper that adds some policy around CanvasImageSource, making it a little easier to work with.  When you change its Content, you remove all the Win2D hookup that CanvasControl did for you, at which point you're left with a not-very-interesting UserControl.

The purpose of CanvasControl is to render onto and then display a single CanvasImageSource.  If you want to combine this with other XAML controls, you need to back up a level and use the XAML composition system (typically via a Grid).  XAML layout and composition are extremely rich and efficient - this isn't something we want to duplicate inside Win2D itself.


> I'd also love some feedback on the impact of potentially having an entire UI composed of these CanvasControl objects. I have no idea how much overhead is introduced by each instance of this control.

CanvasControl is reasonably efficient for what it is (a bridge between the radically different worlds of Direct2D vs. XAML graphics rendering) but the nature of bridging two such different worlds means this can never be as efficient as if you were able to stay entirely in one world or the other.

It is reasonable to implement custom UI controls via CanvasControl and then add many instances of these to a XAML page, but I would be wary of doing that for /every/ single element in your UI.  This really all depends on how many such elements your design calls for, though.

I would generally recommend either:

1. Keep most of your UI in regular XAML, and use Win2D only for the specific elements where you need its richer rendering capabilities.
2. Or use Win2D heavily for everything, but combine many different pieces of complex drawing within a smallish number of large CanvasControl instances.

The third approach of using Win2D for everything with many very fine grained small controls (the same as how you would design a typical pure XAML app), will be significantly less efficient.  It'll work, but jumping back and forth between immediate mode D2D and retained mode XAML/DComp rendering so many times will add overhead.

**Comment by dtaylorus** [comment]
Thanks for your thorough answer, Shawn! This is very helpful.

The scenario I have in mind is a cross-platform UX library that uses XAML on Windows for layout, input, and some complex controls like TextBox, but in general doesn't draw the UI.

Instead, I'd like to draw the UI from the cross-platform library and have it look essentially the same on every platform. None of those ugly native controls that require heavy visual customization on each platform.

On each platform, then, I need some kind of canvas that supports some basic drawing primitives. No problem on iOS and Android, as I can draw right on the same surface used by the native views. On Windows, though, no such luck.

So, I'm experimenting with using Win2D to provide that canvas on Windows.

Given this scenario, would there be a significant benefit to using a CanvasImageSource to create the layers inside my user control, rather than CanvasControl?

Is there much difference in overhead between the two?

**Comment by shawnhar** [comment]
There's no performance benefit from using CanvasImageSource over CanvasControl.  The difference is level of policy.  CanvasImageSource provides the raw mechanism to insert Win2D rendering into a XAML control graph, but you have to write quite a bit of code to make use of that.  CanvasControl wraps it with a bunch of higher level policy so you can get going in just a line or two of code.  It handles creating a device for you, recreating that device if it becomes lost, calling Draw at sensible times, not calling Draw before resources have been created, etc.  Using the lower level API directly gives you more flexibility if you want to handle this sort of policy in some other way, but would be wasted effort in the (common) case where the default CanvasControl policies are suitable.

I suspect (with big caveat that I have never actually tried anything like this :-) that using a separate CanvasControl for each of your controls would work reasonably well in a situation like this.  It really depends on the granularity of how many such controls you have.  One per button, totally fine.  One per item in a scrolling list containing 10,000 entries, probably not so much!

I do recommend only bothering to stack multiple controls in the specific cases where you really do need both XAML and Win2D rendering on top of each other.  Seems like with this design, a significant fraction of your items could be pure one or the other.

**Comment by dtaylorus** [comment]
Thank you again, Shawn! I really appreciate your help!
