### ISSUE TITLE
Allow CanvasControl to be subclassed

### ISSUE THREAD

**Issue by dtaylorus** [Microsoft/Win2D#363]
I much prefer subclassing user controls and overriding virtual methods, as opposed to dealing with the memory leak mess surrounding event delegates.

Please consider unsealing CanvasControl and adding the following methods:

protected virtual void CreateResources(CanvasCreateResourcesReason createResourcesReason)
protected virtual void Draw(CanvasDrawingSession canvasDrawingSession)

**Comment by shawnhar** [comment]
I'm afraid inheritance isn't an option here.  This is due to the nature of the technologies that Win2D is built on top of.  WinRT relies on interface inheritance and aggregation rather than class inheritance, and does not support class inheritance at all other than a couple of very specific cases for XAML.  CanvasControl is sealed because all non-XAML WinRT classes have to be this way - it's just the nature of the platform.
