### ISSUE TITLE
Setting Horizontal and Vertical alignment on CanvasControl does not call Draw event

### ISSUE THREAD

**Issue by painavin** [Microsoft/Win2D#364]
If I declare the following XML the draw event is called.
```
        <Canvas:CanvasControl
            ClearColor="Black"
            x:Name="CanvasControlChart"
            Draw="CanvasControlChart_Draw"/>
```
The draw event does not get called when I set the Horizontal and Vertical Alignment

```
        <Canvas:CanvasControl
            ClearColor="Black"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            x:Name="CanvasControlChart"
            Draw="CanvasControlChart_Draw"/>

```

**Comment by painavin** [comment]
Not only that infact, the following code will also not call the draw event
```
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Border
            HorizontalAlignment="Center"
            VerticalAlignment="Center">

            <Canvas:CanvasControl
                ClearColor="Black"
                x:Name="FinchControlDaily"
                Draw="FinchControlDaily_Draw"/>
            
        </Border>
    </Grid>
```

As long as any parent of CanvasControl has set the alignment to center, the draw event does not seem to trigger.

**Comment by shawnhar** [comment]
I suspect your control is getting sized all the way down to zero, since you don't set a size for it anywhere.  The Draw event is only raised if XAML layout produced a greater-than-zero size for Win2D to draw onto.

You need to either use a layout that auto stretches the control to fill some non-zero space, or if you use layout options like centering that depend on the original size of the control itself, you then need to specify what size you want this control to be.

**Comment by painavin** [comment]
I know for sure that it is getting sized all way down to zero. This is a bug. 
I do not set the size for the following piece of code and yet the size is auto calculated based on the layout.
```
        <Canvas:CanvasControl
            ClearColor="Black"
            x:Name="CanvasControlChart"
            Draw="CanvasControlChart_Draw"/>
```

If I have to set the size when the orientation is centered, that defeats the purpose of setting the orientation. Win2d CanvasControl should behave exactly like any other control when the orientation is set and not have the programmer set the size and position just because the orientation was changed.

**Comment by shawnhar** [comment]
You have to either set what size you want, or configure a XAML layout that will produce a sensible size.  This is necessary because CanvasControl otherwise has no idea how big you would like it to be.  Unlike retained mode XAML controls such as a button, which always know what their contents are, understand how to draw themselves, and thus can automatically work out how big they need to be, all CanvasControl drawing is done in immediate mode by you.  Therefore you are also responsible for providing size information for use by XAML layout.

Because CanvasControl has no automatic knowledge about size, it will happily accept any XAML layout request from zero to arbitrarily large.  Depending on how your XAML is configured, the result can either be a CanvasControl that stretches to fill its parent container, or a CanvasControl that shrinks down to zero.

When you tell XAML to center a control, that really means "leave some blank space, then the control, then some more blank space".  So layout asks the control how much space it needs.  CanvasControl says whatever, anything is fine - and you get a zero size control.

On the other hand when you don't enable centering, layout asks the control if it can stretch to fill the entire available space.  CanvasControl again says whatever, that's fine to - so you get a control filling its parent.

To get a different result, you need to provide the missing size information so CanvasControl can respond to these layout requests in a more sensible way.

**Comment by painavin** [comment]
Thanks for the explanation. That makes sense.
