### ISSUE TITLE
Add a tint parameter to DrawImage

### ISSUE THREAD

**Issue by dtaylorus** [Microsoft/Win2D#366]
I think it's fairly common practice to use white image resources and then tint them when drawing.

I read in the response to another issue that it's possible to do something similar in Win2D by applying a ColorMatrixEffect to an entire CanvasBitmap, but that's a lot of code to write for such a common scenario.

Please consider making life just a little bit nicer by adding a tint parameter to DrawImage. :)

Thanks!

**Comment by shawnhar** [comment]
Have you looked at CanvasSpriteBatch?  It provides an optimized and pretty straightforward path for doing this kind of bitmap tinting.

**Comment by dtaylorus** [comment]
Yes, I did see that, but I didn't want to create a CanvasSpriteBatch just to draw one image. I didn't actually try it, but at a glance it seemed like just about as much code as the color effect.

If CanvasSpriteBatch doesn't add significant overhead over DrawImage, I'll go that route, but I'd still appreciate being able to keep it simple with DrawImage. Thanks!

**Comment by dtaylorus** [comment]
Oh, now I remember why no CanvasSpriteBatch. I'd like the code to work on Win8, so that seems to rule out CanvasSpriteBatch.

**Comment by shawnhar** [comment]
CanvasSpriteBatch would be two lines of code, plus some curly braces:

    using (var spriteBatch = drawingSession.CreateSpriteBatch())
    {
        spriteBatch.DrawSprite(...);
    }

But yes, if you need to run on Windows 8.1, ColorMatrixEffect is your only option.  Taking advantage of newer Direct2D APIs requires a newer version of Windows.

**Comment by dtaylorus** [comment]
Ok, I get the impression you really don't want to add a tint parameter. :)

Can you comment on the performance impact of ColorMatrixEffect?

As far as CanvasSpriteBatch goes, I'd love to use the new API's, I really would. But the fact is that more than half of my Windows Store customers are still running Windows/Windows Phone 8.1. And a lot of them with unsupported (e.g., WinRT) devices will not run Windows 10 until they buy new devices. So the current reality is that I need to support Windows 8.1 or lose a significant percentage of my customers. This is simply the penalty we all pay for Microsoft choosing to introduce and obsolete so many frameworks in recent years.

(Btw, I use MonoGame for other projects that don't require forms input controls like TextBox. MonoGame supports sprite batches and the same tinting parameter that was in XNA back in the day on pretty much every Microsoft platform, including Windows/Windows Phone 8.1. So it's really odd to me that CanvasSpriteBatch is a "new" API for Windows 10 only. I mean, I'm sure there is some very real technical limitation internally, but from an outside developer perspective, it's a step backwards.)

My scenario is creating a cross-platform UI to bring my existing Android and iOS apps to Windows. The apps use tinting extensively to avoid having to create image resources in every possible color. Among many other XAML limitations, the Image control does not support tinting as do the iOS and Android equivalents. So... I'm trying to fill the gaps with Win2D. (What other option is there?)

There will be lots of these tinted images (mostly buttons) throughout my UI and I'm already concerned about the overhead of using Win2D for every control, thus my question about the performance impact of adding a ColorMatrixEffect to each one.

Thanks for your help!

**Comment by shawnhar** [comment]
Please understand that Win2D is just a thin wrapper on top of the Direct2D API, which is part of the Windows operating system.  Whenever we decide to add new functionality to our graphics platform, that happens first in Direct2D, after which Win2D wraps the new features to make them available in WinRT.  Because Win2D does not implement any rendering techniques directly itself, it has no way to make newer techniques available on older operating systems where Direct2D did not yet support them.  To get the latest features, you need to be on the latest OS.

You are absolutely right that tinting images used to be too hard.  This was one of our motivations for adding the spritebatch API to Direct2D and Win2D.  We are also considering adding a shortcut image effect that would apply tinting while requiring fewer lines of code than it takes to configure a general purpose color matrix.

It's not so much that I'm reluctant to add a tint parameter, but that I consider this unnecessary.  Understood that newer APIs are no use to you as long as you want to support older operating system versions, but this would be the case regardless of how or where we put such an API.  On Windows 8.1, ColorMatrixEffect is the best way to tint an image.

**Comment by dtaylorus** [comment]
True. It is unnecessary. Technically, it's all unnecessary given an array of pixels. :)

So, it looks like ColorMatrixEffect is my only option. An example of tinting with ColorMatrixEffect would be nice, as you can see from issue #344 that it's not so trivial for people who don't use matrices on a daily basis, but it looks like I have what I need from #344.

Maybe someday iOS bridge will eventually support C# and give us a more capable UI on Windows that simplifies all of this. We can only hope!

Thanks for your help!

**Comment by tgckpg** [comment]
Hello, I've just ran into this problem too.

In my case, I would like to add a `GaussianBlur` filter to my image. But I'd also need to use the tint in `CanvasSpriteBatch`.

`CanvasSpriteBatch` does not seem to support drawing from an effect source.

My question is, does the `CanvasDrawingSession.DrawImage` as efficient as `CanvasSpriteBatch.Draw`?

Referencing the  Particle System in Example Gallery. I've set the smoke plume particle to 1000~5000 and decrease the `DpiScale`.

By checking / unchecking UseCanvasSpriteBatch. Both didn't pose much different on CPU resources. But the UseCanvasSpriteBatch seemed to consume about 1GB of memories and DrawImage don't.

So does that mean the `DrawImage` is superior than `CanvasSpriteBatch`?

**Comment by shawnhar** [comment]
DrawImage is a very flexible, general purpose API.  It can draw from any type of image, including arbitrarily complicated effect graphs that can do pretty much whatever image processing you could imagine.  With this flexibility comes higher overheads, especially on the CPU side.

CanvasSpriteBatch is a very limited, simple API.  It can only draw bitmap images, with transform and optional tinting but no other processing.  This greater simplicity makes it far more efficient than DrawImage when drawing large numbers of sprites.

If you are applying a blur effect, CanvasSpriteBatch will be no use - you need the flexibility of DrawImage in order to use an image effect.  To combine blur with tinting, feed the output of GaussianBlurEffect into the Source of a ColorMatrixEffect  (or the other way around, use ColorMatrixEffect to tint the source image and feed that into GaussianBlurEffect - either way will produce the same result).

Blur is a fairly expensive image effect, so compared to the blur operation, CanvasSpriteBatch vs. DrawImage and the cost of the tint operation will be negligible.

**Comment by tgckpg** [comment]
Thanks for the info!

 In fact I just tested the DrawImage on my phone. Turns out that the DrawImage is very inefficient on drawing particles.( I could simulate only ~10 particle when using drawImage. )

Hmm, but I needed the effect:(
I think I'll try to use the spritesheet and see.

**Comment by shawnhar** [comment]
Is that DrawImage of a GaussianBlurEffect, or DrawImage of a regular bitmap?

DrawImage is always more expensive than CanvasSpriteBatch, but exactly how expensive depends on what type of image is being drawn, and what effects are involved (if any).  Even a lower end phone should be able to draw far more than 10 images with good performance, so if these are regular bitmaps, we should dig more into what else might be going wrong with your performance.  If these are blur effects, though, that sounds about what I'd expect.  Blur is quite expensive to compute - not something you can do large numbers of at the same time.

**Comment by tgckpg** [comment]
I was just adding a ColorMaxtrix effect. But the DrawImage is still far slower then SpriteBatch.

https://github.com/tgckpg/playground/blob/master/App1/ParticleField.xaml.cs#L103

I think it is related to the DpiScale. But setting the DpiScale to 0.2f still doesnt make any difference.

However the colored space on the dds itself seemed to deal a great impact on the performance too (say I am only having a single dot colored on the dds. transparent on every other pixel. )

**Comment by dwulive** [comment]
When using DrawSpriteSheet with a large source image (2400x2400) the UV's seem to have precision errors (i.e. the image wobbles quite noticably as you scroll or scale it.)
Is there a workaround for this?
I only need Tint and I would prefer to use the faster DrawSpriteSheet method over an image.
Thanks!
