### ISSUE TITLE
Save screenshot of a CanvasControl?

### ISSUE THREAD

**Issue by TomQv** [Microsoft/Win2D#371]
How would I capture the current content of a CanvasControl like a screenshot?
I was trying this, but this got stuck in RenderAsync:

var bitmap = new RenderTargetBitmap();
await bitmap.RenderAsync(canvascontrol);
var pixels = await bitmap.GetPixelsAsync();

**Comment by damyanp** [comment]
There's no way to directly do this using XAML APIs (since XAML cannot see the contents of a CanvasControl).

Instead what you need to do is to first render to an offscreen render target (see http://microsoft.github.io/Win2D/html/Offscreen.htm) and then save the contents of that render target (http://microsoft.github.io/Win2D/html/Overload_Microsoft_Graphics_Canvas_CanvasBitmap_SaveAsync.htm).

See also ExampleGallery's [CaptureThumbnail](https://github.com/Microsoft/Win2D/blob/master/samples/ExampleGallery/Shared/Infrastructure/ThumbnailGenerator.xaml.cs#L175) method for an approach that does this by creating the rendertarget and invoking the Draw event manually.

**Comment by TomQv** [comment]
Thanks for your quick answer
CanvasDevice device = CanvasDevice.GetSharedDevice();

Seems like, this is the right way?
```
var offscreen = new CanvasRenderTarget(device, (float)_canvasControl.ActualWidth, (float)_canvasControl.ActualHeight, 96);
using (CanvasDrawingSession ds = offscreen.CreateDrawingSession())
{
   ds.Clear(Colors.White);
  // ControlDraw(ds);
  ds.DrawRectangle(100, 200, 5, 6, Colors.Red);
}
```

But when I try so save this to a stream or file, SaveAsync freeses...
 ```
using (var stream = new InMemoryRandomAccessStream())
{
      await offscreen.SaveAsync(stream, CanvasBitmapFileFormat.Png);
}
```

**Comment by damyanp** [comment]
I'm not sure exactly what you mean by freezes?  When you run this in the debugger, do you see any messages about exceptions?  If you set the debugger to break on all exceptions do you see anything? If you try running this with native debugging enabled do you see any other exceptions?

**Comment by TomQv** [comment]
Freezing means, that SaveAsync is not returning. No exception.

**Comment by damyanp** [comment]
Can you share a project that reproduces the problem, with steps to reproduce please?

**Comment by TomQv** [comment]
I'm using Win2D in a Xamarin.Forms.UWP project in a ExportRenderer, so its a bit difficult to share that.
But if you are saying, that it should work like that, I will do more investigations tomorrow.
Thanks, Tom

**Comment by shawnhar** [comment]
Closing issue as we haven't heard back in a couple of weeks.  Feel free to reactivate if you have more questions or are able to provide a simplified repro app.
