### ISSUE TITLE
Per Vertex Fill?

### ISSUE THREAD

**Issue by JranZu** [Microsoft/Win2D#375]
I am currently doing this:

foreach (var v in Vector2Array)
{
    if (v.Length != 3)
        throw new ArgumentException();

    ds.DrawLine(v[0], v[1], new CanvasLinearGradientBrush(sender, Colors.Red, Colors.Green) { StartPoint=v[0], EndPoint=v[1] });
    ds.DrawLine(v[1], v[2], new CanvasLinearGradientBrush(sender, Colors.Green, Colors.Blue) { StartPoint = v[1], EndPoint = v[2] });
    ds.DrawLine(v[2], v[0], new CanvasLinearGradientBrush(sender, Colors.Blue, Colors.Red) { StartPoint = v[2], EndPoint = v[0] });
}

Which creates a triangle where each vertex is different color and the line is gradient between those colors.  I'd like to be able to do this with Geometry and have that geometry filled with a 3-point gradient. Is this something that can be done and I am just missing it? Seems like it should be easy enough.

Just as an FYI, I really want to be able to do this with a solid color (black) and then have the alpha change between each point (if that makes any difference).

Thanks!

**Comment by shawnhar** [comment]
There's no direct way to specify a different color for each vertex of a set of lines or geometry.

Depending on the details of what you are trying to draw, it might be possible to position a single gradient brush over the entire triangle to achieve the desired effect?

If you are drawing filled shapes, another option might be DrawGradientMesh.

Otherwise, the approach you are doing now looks reasonable.  Performance would be better if you hang onto and reuse brushes rather than creating new ones every time, though.

**Comment by JranZu** [comment]
The brush-reuse is just for the example. Ultimately I am trying to do something with shadow and triangles and was hoping that I could just create a triangular gradient instead of a linear or radial.

GradientMesh seems super complicated for what I want to do. Is there a way to easily create a GradientMesh from 3 vertices?

**Comment by shawnhar** [comment]
GradientMesh is complicated, yes, but quite powerful.

Perhaps simpler would be to create your 2D gradient pattern as a small bitmap, attach that to a CanvasImageBrush, then modify the brush transform to align the gradient appropriately so it fits over the triangle being drawn.

**Comment by shawnhar** [comment]
Closing issue as I believe this question has been answered.
