### ISSUE TITLE
Info needed. CanvasRenderTarget vs CanvasBitmap

### ISSUE THREAD

**Issue by tower120** [Microsoft/Win2D#378]
Why do you have both  `CanvasRenderTarget` and `CanvasBitmap` ? Why not only `CanvasRenderTarget`?

1. From documentation I may assume that `CanvasRenderTarget` holds Frame buffer object alongside with rendered texture. Is this correct?
2. Does `CanvasBitmap` store Image in GPU texture or it's just a raw bitmap stored in main memory?
3. Which one is faster to draw?
4. Is there a reason why I should copy `CanvasRenderTarget` to `CanvasBitmap`? For example if I do offscreen rendering of symbols (10-100 items) , should I have one `CanvasRenderTarget` and a few `CanvasBitmap`; or it is ok to have a bunch of `CanvasRenderTarget`?

**Comment by shawnhar** [comment]
CanvasBitmap = bitmap data that can be used as source for GPU operations.

CanvasRenderTarget = a bitmap that can also be drawn onto by the GPU.

All rendertargets are bitmaps, but not all bitmaps are rendertargets.  For instance there are some pixel formats (eg. block compressed pixel data) that can only be used as sources but not rendered onto by GPU hardware.  Rendertargets also typically have stricter alignment requirements than source-only bitmap data, so the driver may need to allocate more resource memory to ensure that.

Choosing between the two is simple: if you need to draw onto something, make it a rendertarget.  Otherwise use a bitmap.

**Comment by tower120** [comment]
> For instance there are some pixel formats (eg. block compressed pixel data) that can only be used as sources but not rendered onto by GPU hardware.

And this is the reason why rendertargets doesn't have LoadAsync?

> Rendertargets also typically have stricter alignment requirements than source-only bitmap data, so the driver may need to allocate more resource memory to ensure that.

Are you talking about pow2 alignment? Is there overhead on creation?

> Choosing between the two is simple: if you need to draw onto something, make it a rendertarget. Otherwise use a bitmap.

If I need to render EXACTLY once 100 images ( I want to cache vector graphic to texture ), should I use 100 rendertargets for this ?

**Comment by shawnhar** [comment]
Rendertargets don't have LoadAsync because if you are going to draw something using the GPU, there is no need to load bitmap data from a file into it first.  Conversely, bitmap data loaded from a file is typically immutable source material, which is more efficiently created as bitmap that cannot later be rendered onto.

Resource alignment occurs for various hardware and driver reasons.  The details aren't particularly important - thing to understand is don't ask for more flexibility than you actually intend to use - so only create a rendertarget if you actually do intend to render onto it.


> If I need to render EXACTLY once 100 images ( I want to cache vector graphic to texture ), should I use 100 rendertargets for this ?

Yes.  If you need to draw onto something, make it a rendertarget.

**Comment by tower120** [comment]
Ok, thank you.
