### ISSUE TITLE
Improve documentation about DpiCompensationEffect

### ISSUE THREAD

**Issue by cherepets** [Microsoft/Win2D#384]
I've applied TransfromEffect (with InterpolationMode = NearestNeighbor) to an image, then I'm passing this TransfromEffect to session.DrawImage() and I'm getting blurry (interpolated) image.
I've also tried specifying the InterpolationMode in session.DrawImage() parameters and it didn't help;

InterpolationMode works fine if I'm passing an image without effects to session.DrawImage().

**Comment by shawnhar** [comment]
Wild guess: is your source bitmap 96 DPI, but your destination CanvasDrawingSession at some other DPI?

**Comment by cherepets** [comment]
Yes, that's true. That's the reason why the image scales.

**Comment by shawnhar** [comment]
What's going on here is that the effect system internally always operates in pixel units rather than dips.  When a source image of different DPI is connected to an effect graph, a DpiCompensationEffect is used to convert it to the appropriate DPI for the output.  To make things easier, Win2D automatically inserts these compensation effects on your behalf, which is usually what people want - but doesn't give you the option to control filtering mode for that DPI compensation  (your setting on the transform effect is happening after DPI compensation scale already took place).

The easiest way to prevent this is to insert your own DpiCompensationEffect in place of the default one that Win2D provides for you.  So your effect graph goes bitmap -> DpiCompensationEffect -> whatever other effects -> DrawImage.  Now you can set nearest neighbor sampling mode on that DpiCompensationEffect.

Another option is to insert a null DpiCompensationEffect, by setting its SourceDpi property to the same value as your CanvasDrawingSession DPI.  This will do no scaling at all, but will prevent Win2D from inserting other DPI scaling of its own.  Your bitmap will appear the wrong size as a result, but you could then include the DPI scaling factor (outputDPI / sourceDPI) in your transform effect matrix.

**Comment by cherepets** [comment]
Yes, adding a DpiCompensationEffect with InterpolationMode solves my problem.
Thank you.

Maybe it would be great to mention that this effect is added by default somewhere in the documentation (in DpiCompensationEffect or ICanvasEffect or DrawImage page). Not sure about the suitable place.

**Comment by shawnhar** [comment]
> Maybe it would be great to mention that this effect is added by default somewhere in the documentation 

Good point - I have marked this issue as "suggestion" and changed its title.

**Comment by shawnhar** [comment]
These docs are improved in Win2D 1.19.0.
