### ISSUE TITLE
Documentation for c++

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/Win2D#387]
So far I couldn't find any documentation or examples that would show me how to use this API with C++ (Admittedly, I only searched for a couple of minutes). If this API is really supposed to be usable by c++ developers there should at least be some basic C++ examples to get people started.

**Comment by shawnhar** [comment]
WinRT uses automatic language projections to make the same API surfaces (class names, methods, properties, etc.) available across .NET and C++/CX.   If you are not familiar with C++/CX, [this is a good intro](https://msdn.microsoft.com/en-us/magazine/dn166929.aspx), and the [full language reference is here](https://msdn.microsoft.com/en-us/library/windows/apps/hh699871.aspx).

We concentrated on C# when writing the Win2D samples because a majority of Win2D customers are using C#, and we felt it unnecessary to provide samples in both languages since the API is the same in both places.  We'd be happy to accept contributions if someone wants to put the time into creating a dedicated C++/CX sample though.

Win2D does document a few places where we provide APIs that are unique to C+, eg. [numerics](http://microsoft.github.io/Win2D/html/WindowsNumerics.htm) and [interop](http://microsoft.github.io/Win2D/html/Interop.htm).

**Comment by MikeGitb** [comment]
Thanks for the quick feedback. My personal opinions about C++/CX aside (I really hope it will die in favor of Kenny Kerr's modern library some time soon) I think it would be helpful to have something that new programmers can download, open, compile, run and modify / play around with.

I might be able to contribute some of these, but as I haven't any significant experience with C++/CX or programming against WinRT in general, I'm probably not the best person to do this.

**Comment by shawnhar** [comment]
Win2D 1.19.0 adds some additional C++ information in the docs.
