### ISSUE TITLE
overloaded DrawLine method performance

### ISSUE THREAD

**Issue by tower120** [Microsoft/Win2D#389]
In my test (just drawing 100000 lines) I have this timings:

```
DrawSession.DrawLine(x0, y0, x1, y1, color, strokeWidth);               // 100ms
DrawSession.DrawLine(x0, y0, x1, y1, color, strokeWidth, null);         // 110ms
DrawSession.DrawLine(x0, y0, x1, y1, color, strokeWidth, strokeStyle);  // 130ms
```

Why so? Shouldn't they all be equivalent?  At least first two.
In the last case I use this strokeStyle:
```
self.strokeStyle.CustomDashStyle = null;
self.strokeStyle.DashCap = CanvasCapStyle.Flat;
self.strokeStyle.DashOffset = 0.0f;
self.strokeStyle.EndCap = CanvasCapStyle.Flat;
self.strokeStyle.LineJoin = CanvasLineJoin.Miter;
self.strokeStyle.MiterLimit = 0.0f;
self.strokeStyle.StartCap = CanvasCapStyle.Flat;
self.strokeStyle.TransformBehavior = CanvasStrokeTransformBehavior.Fixed;
```

**Comment by shawnhar** [comment]
I'd expect these operations to be similar in performance, but not quite identical since each measurement is calling a different overload that contains slightly different code.  And indeed that's what you are seeing - a small difference but all three are similar.  When you microbenchmark a single quick running method in isolation like this, even trivial differences will show up in the result.

One difference between these versions is that if you pass a stroke style, Win2D needs to unwrap that to look up the internal D2D stroke object.  If you pass a null stroke style, no unwrapping takes place but it must still examine the pointer to decide whether one was provided.  But if you call the overload that takes no stroke style at all, there is no need for such a test.  Similarly inside D2D, there is slightly more work to look up settings from inside a style interface if one was provided.

**Comment by tower120** [comment]
> If you pass a null stroke style, no unwrapping takes place but it must still examine the pointer to decide whether one was provided. 

Are you sure? I just tested with something like:
```
if (brush.strokeStyle == null)
{
  canvas.DrawSession.DrawLine(x0, y0, x1, y1, brush.color, brush.strokeWidth);
}
else
{
  canvas.DrawSession.DrawLine(x0, y0, x1, y1, brush.color, brush.strokeWidth, brush.strokeStyle);
}
```
And it still 10% faster than just
```
canvas.DrawSession.DrawLine(x0, y0, x1, y1, brush.color, brush.strokeWidth, brush.strokeStyle);
```

---
Should I expect similar 30% performance drop with DrawPath? And every other draw call method with brush-like overloading?

**Comment by shawnhar** [comment]
You can take a look at the Win2D implementation [here](https://github.com/Microsoft/Win2D/blob/master/winrt/lib/drawing/CanvasDrawingSession.cpp#L761) if you want to dig into exactly what each overload is doing.  Note in particular the ToD2DStrokeStyle helper, which has to do extra work if you pass a non-null stroke style.

> Should I expect similar 30% performance drop with DrawPath?

I wouldn't expect the ratio to remain constant when you add a fixed amount of brush marshalling overhead over the top of drawing operations that have different underlying performance.

**Comment by tower120** [comment]
> You can take a look at the Win2D implementation here if you want to dig into exactly what each overload is doing. Note in particular the ToD2DStrokeStyle helper, which has to do extra work if you pass a non-null stroke style.

Yes, but why performance drop in this case:
```
canvas.DrawSession.DrawLine(x0, y0, x1, y1, brush.color, brush.strokeWidth, null);
```

Could this be due to marshaling StrokeStyle between C# and C++ (Which becomes ICanvasStrokeStyle*) ? 
I can't see another source of overhead.

I can send you test project which describes problem.

**Comment by shawnhar** [comment]
C# to native marshaling will add some overhead, as does the method proxying within the Win2D implementation I pointed you to.  These are very tiny costs, though - you're only noticing them at all because you are running a microbenchmark on an operation that in itself is extremely cheap.

I don't see a problem here.

**Comment by tower120** [comment]
You could do check for null BEFORE C++ call (in C#), and then call appropriate native function (thus, avoiding CanvasStroke marshalling).

**Comment by shawnhar** [comment]
That's not something Win2D could do, because it is a WinRT component, which means interop is handled by the runtime - there is no C# code in Win2D.

I'm sure the runtime does sensible things to minimize marshaling cost for null values, which is why the performance difference between an overload that has no parameter vs. a null parameter value is so small.

**Comment by tower120** [comment]
>That's not something Win2D could do, because it is a WinRT component, which means interop is handled by the runtime - there is no C# code in Win2D.

Oh, now I see.
