### ISSUE TITLE
Referencing WinRT Win2D static lib in winmd

### ISSUE THREAD

**Issue by Cleverman87** [Microsoft/Win2D#398]
Hi I'm trying to reference the winrt win2d static library (winrt.lib.Windows.vcxproj) in my winmd library.
Just like winrt.dll.Windows.vcxproj

Now the difference when I build winrt.dll.Windows.vcxproj: I can use the Win2D from any C# code.

While from my winmd I can't.

Steps:
- Create a new empty C++ WinRT winmd project (Windows Runtime....).
- Add a reference to the static library in the project as the following:
<ItemGroup>
    <ProjectReference Include="..\..\Win2D\winrt\lib\winrt.lib.Windows.vcxproj">
      <Project>{8e9fef0d-edb6-4c76-9383-a070314e5ff4}</Project>
      <Private>false</Private>
      <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
      <CopyLocalSatelliteAssemblies>false</CopyLocalSatelliteAssemblies>
      <LinkLibraryDependencies>true</LinkLibraryDependencies>
      <UseLibraryDependencyInputs>true</UseLibraryDependencyInputs>
    </ProjectReference>
  </ItemGroup>
- The add the static library project to the same winmd solution.
- Build; It builds fine, and the size of the winmd indicates that Win2D is included.
- Try to use the winmd from any C# code, and try to call any of the Win2D, notice you can't.

What is the difference between winrt.dll.Windows.vcxproj and the project I'm trying to create.

**Comment by shawnhar** [comment]
Visual Studio project system doesn't fully understand how to build WRL WinRT components like Win2D, so you have to write a bunch of your own targets to generate the .winmd metadata.  See in particular the build customizations in https://github.com/Microsoft/Win2D/blob/master/winrt/dll/winrt.dll.Shared.vcxitems.

I'm curious what you are trying to do here though?  Note that the build steps will be significantly more complex if you are trying to merge Win2D API surface with other things of your own, rather than just exposing the API surface provided by the Win2D lib like our DLL project does.

Note also that WinRT requires API namespace and DLL name to match, so you won't be able to build this API into a binary named anything other than Microsoft.Graphics.Canvas.

**Comment by Cleverman87** [comment]
I see now...
Then is it possible to link to the static library from my Windows project.
In other words what are the needed steps to draw on canvasbitmap in my Windows using the static library... What is the needed headers order ..etc
If it's possible...thank you for your help

**Comment by shawnhar** [comment]
If your project is using WRL style C++, you could call into the static library the same way that Win2D test.internal does.  If you are using C++/CX or C#, you must build it into a standard WinRT DLL.

Can you explain what you are trying to achieve here?  Why can't you just use Win2D in the normal way?

**Comment by Cleverman87** [comment]
No problem, I will use the winmd directly, thank you for your help.
