### ISSUE TITLE
Wrong rendering if sprite batches are used back-to-back (OS bug)

### ISSUE THREAD

**Issue by tower120** [Microsoft/Win2D#407]
In the following sample code:

```
        void CanvasControl_Draw(CanvasControl sender, CanvasDrawEventArgs args)
        {
           var screen = new CanvasRenderTarget(CanvasDevice.GetSharedDevice(), 1000, 1000, canvas.Dpi);

            offscreen = new CanvasRenderTarget(canvasDevice, 1000, 1000, canvas.Dpi);
            using (var session = offscreen.CreateDrawingSession())
            {
                session.Clear(Colors.Red);
            }

                using (var session = screen.CreateDrawingSession())
                {
                    for (int i = 0; i < 10000; ++i)
                    {
                        using (var spriteBatch = session.CreateSpriteBatch())
                        {
                            spriteBatch.Draw(offscreen, new Vector2(100, 200));
                        }
                        //session.Flush();
                    }
                }

            args.DrawingSession.DrawImage(screen);
         }
```

I have undefined behavior without "session.Flush();" (It may draw, may not, may draw black instead of red, may draw some triangles instead) . Is it required to flush DrawSession after each  SpriteBatch draw block?

**Comment by shawnhar** [comment]
Your code example doesn't compile as-is, so I didn't run it, but my first thought is this could be the same as issue #326.   What OS are you running on?

**Comment by tower120** [comment]
Windows 10 (Not anniversary) with latest updates.

I attached sample project.

[ready.zip](https://github.com/Microsoft/Win2D/files/411661/ready.zip)

**Comment by shawnhar** [comment]
Thanks for the repro!  This still occurs with Anniversary Edition, so it's not the same problem as #326.

For my future reference, this is tracked by internal bug 8450720.

**Comment by tower120** [comment]
Actually "large number of sprite batches" is not correct. If you change "i" from 10000 to 2 - you'll get the same result.

**Comment by shawnhar** [comment]
We've confirmed this is a bug in Direct2D.  It will be fixed in the next version of Windows.

The problem only occurs when using multiple sprite batch sessions back to back, with no other drawing in between.  That's not usually a sensible thing to do, as the entire goal of sprite batch is to optimize drawing by putting as many sprites as possible inside a single batch.  You can both avoid the bug and get better perf by moving all your Draw calls inside the same batch.

An alternative workaround is to insert a no-op draw call (such as FillRectangle with a zero sized destination) in between the adjacent sprite batches.

**Comment by tower120** [comment]
What you mean saying "next version of Windows"? Next windows patch, or...?

**Comment by 13thsymphony** [comment]
The fix is targeted for the next release of Windows (i.e. the one after Anniversary Update).

**Comment by shawnhar** [comment]
This issue is fixed in the Win10 Creators Update release.
