### ISSUE TITLE
About the behaviour of DrawLine when CanvasImageBrush is used

### ISSUE THREAD

**Issue by laszlotall** [Microsoft/Win2D#413]
I try to use a CanvasImageBrush for drawing a line. It works fine when the CanvasEdgeBehavior is Wrap, but it is a little bit strange for me when it is Clamp.
It seems that only a part of the brush is used (even if the line is thick enough to contain the whole brush)
and the Transform property is ignored.

In the following example both lines are completely green. Is it the expected behaviour? It works as I expect when something is filled.

```csharp
using Microsoft.Graphics.Canvas;
using Microsoft.Graphics.Canvas.Brushes;
using Microsoft.Graphics.Canvas.UI.Xaml;

using System.Numerics;
using Windows.Foundation;
using Windows.UI;
using Windows.UI.Xaml.Controls;

namespace App
{
    public sealed partial class MainPage : Page
    {
        CanvasImageBrush fillBrush;

        public MainPage()
        {
            this.InitializeComponent();
        }

        void CreateBrushes(CanvasControl sender)
        {
            CanvasRenderTarget target = new CanvasRenderTarget(sender, new Size(10,10));
            using (var session = target.CreateDrawingSession())
            {
                session.FillRectangle(new Rect(0, 0, 10, 5), new CanvasSolidColorBrush(sender, Colors.Red));
                session.FillRectangle(new Rect(0, 5, 10, 5), new CanvasSolidColorBrush(sender, Colors.Green));
            }

            fillBrush = new CanvasImageBrush(sender, target);
            fillBrush.ExtendX = CanvasEdgeBehavior.Clamp;
            fillBrush.ExtendY = CanvasEdgeBehavior.Clamp;
        }

        private void canvasControl_CreateResource(CanvasControl sender, Microsoft.Graphics.Canvas.UI.CanvasCreateResourcesEventArgs args)
        {
            CreateBrushes(sender);
        }

        private void canvasControl_Draw(CanvasControl sender, Microsoft.Graphics.Canvas.UI.Xaml.CanvasDrawEventArgs args)
        {
            fillBrush.Transform = Matrix3x2.Identity;
            args.DrawingSession.DrawLine(new Vector2(0, 200), new Vector2(200, 200), fillBrush, 20);

            fillBrush.Transform = Matrix3x2.CreateTranslation(0, 5);
            args.DrawingSession.DrawLine(new Vector2(0, 250), new Vector2(200, 250), fillBrush, 20);
        }
    }
}

```

**Comment by shawnhar** [comment]
This is expected behavior.  Your image is sized 10x10, and using identity transform means it will be positioned at the origin, so you only actually have image data for pixels in the region (0,0) to (10,10).  But your lines are drawn at much larger y coordinates, so you are sampling from outside the image.  If you specify clamp addressing mode, the result is clamped to the bottom of the image, which is solid green.  Whereas if you specify wrap addressing, the sample location wraps so your 10x10 image is repeated many times to cover whatever location the lines may be drawn at.

If you want to use clamp addressing but not just get a clamped edge of the image, you must make sure your image actually covers the same location where the line is being drawn.
