### ISSUE TITLE
Crash using DrawImage with certain CanvasImageInterpolation types and transformations

### ISSUE THREAD

**Issue by CMay** [Microsoft/Win2D#414]
**Scale transformations crash reliably:**
```
for (int i = 0; i < 500; ++i) {
                    session.DrawImage(someCanvasBitmap, 0.0f, 0.0f, new Rect(0, 0, 500, 500), 1.0f, CanvasImageInterpolation.Anisotropic, Matrix4x4.CreateScale((float)rand.NextDouble()));
}

```

**X/Y rotations crash reliably:**

```
for (int i = 0; i < 500; ++i) {
                    session.DrawImage(someCanvasBitmap, 0.0f, 0.0f, new Rect(0, 0, 500, 500), 1.0f, CanvasImageInterpolation.Anisotropic, Matrix4x4.CreateRotationY((float)rand.NextDouble*(float)(Math.PI*2)));
}

```

**Z rotations don't crash reliably, if at all:**

```
for (int i = 0; i < 500; ++i) {
                    session.DrawImage(someCanvasBitmap, 0.0f, 0.0f, new Rect(0, 0, 500, 500), 1.0f, CanvasImageInterpolation.Anisotropic, Matrix4x4.CreateRotationZ((float)rand.NextDouble*(float)(Math.PI*2)));
}

```

These all work fine indefinitely if the CanvasImageInterpolation is set to something other than Anisotropic or HighQualityCubic.

This also occurs with ForceSoftwareRenderer enabled.

This was repeatable in my own project (CanvasAnimatedControl) and in the Win2D sample (CanvasControl), both debug and release.

**Comment by shawnhar** [comment]
These errors occur because the transform you are requesting would require DirectImage to allocate an excessive amount of intermediate image memory.  The image effects runtime has caps on how much working space it is willing to consume, so will fail if it cannot work out how to evaluate a transform within these limits.

The exception message from this code is the clue to understand this is what is happening:  "*The graph could not be rendered with the context's current tiling settings.*"

You will notice the scaling operation fails when you request a very small (near zero) scaling factor.  This is because you are specifying a fixed 0-500 source rectangle.  Combined with a tiny scale, this means you are requesting the effect runtime to evaluate a very, very large area of the source bitmap.  When using one of the simpler image interpolation modes the GPU hardware can do this without actually expanding out such a large intermediate, but the more advanced filter modes that are implemented by DirectImage rather than natively supported by GPU hardware have to do things the hard way, which runs out of memory.

You can avoid this by adjusting your source rectangle to match the scale.  If the image is scaled down to a tiny size, also specify a correspondingly smaller size for the portion of the image being drawn.  Or you can use one of the DrawImage overloads where you don't specify a source size at all, in which case the effect runtime will work out sensible dimensions for you automatically.

**Comment by CMay** [comment]
Hey Shawn, thanks for the quick response.

- The exception message wasn't very useful, but the define for the message is better than the message itself: D2DERR_INTERMEDIATE_TOO_LARGE.  It's still a bit arcane when you aren't sure what's happening under the hood.  It doesn't help that I was feeding in random values rather than walking up them to get a map of which values it's more likely to fail at, but I incorrectly expected it not to fail at any value.

- I was not seeing abnormal CPU, RAM, VRAM or GPU usage from the app or the overall system which is part of why it was curious to me.  I expected that it should need to allocate more memory for the interpolation, but seeing it throw an exception immediately was a surprise.  Your explanation that it is an intentional artificial cap makes sense.

- I tossed a try-catch around it to just eat the exception and ran it for a while with seemingly no consequences, so I assume the underlying implementation is handling this gracefully-enough aside from throwing the exception.

- Not sure I follow the relationship in memory usage between the source rect and a smaller transform scale.  Is it because it needs to sample a larger area per result pixel?  Can't it just set a valid range and default to safe intermediate sizes in those cases?  Either way, it was occurring with rotations as well.  I had already tried passing in the actual size of the bitmap, but it was still happening.

- The source rect there is not important to me really, I threw in some values to fill it out and did test smaller dimensions.  I would have used DrawImage without a source rect, but there is no DrawImage overload which takes a transformation and not a source rect.

- Is this an issue with it wanting to allocate an intermediate that's larger than the maximum texture size, or is it simply that too many large intermediates have been created recently and it doesn't free the memory fast enough to make room for new ones within its pre-determined limit?

- I'd prefer not to eat exceptions if I can help it.  Is there any way to predict that this will happen and reliably avoid it or is it recommended to never use interpolation modes 4 and 5?  I know Direct2D is built on top of Direct3D 11, but I'm not aware of a page which lists the resource limits defined in Direct2D like this: https://msdn.microsoft.com/en-us/library/windows/desktop/ff819065(v=vs.85).aspx

- It might be worth adding notes to http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasImageInterpolation.htm which make it clear which ones are handled on the GPU along with which one is the default when none is specified.  I assume Linear.

Thanks for your time!

**Comment by shawnhar** [comment]
Indeed, this aspect of how image effects work can be quite arcane :-)

You don't see abnormal memory usage because the budget is evaluated up front.  No rendering actually takes place if the resource usage is going to be too high.  You can adjust this limit via CanvasDevice.MaximumCacheSize.

The limit isn't based on max texture size.  Image effects aren't limited by that - they can split up arbitrary large images into some number of smaller GPU rendering operations.  The challenge is that in order to do this splitting up, each effect must understand the exact mapping between source and destination pixel regions.  In a theoretical sense, all images are infinite in extent.  When you request to draw a particular sized region, the effect runtime will attempt to backproject the requested region through whatever transforms are used by the effect graph, in order to compute what portion of each source is required to be present.  If any step along the way gets too big for GPU HW, it will split up the image, then repeat the attempt.  Ability to do an accurate backprojection depends very much on what effects are in use: for some this is trivial, but in other cases it can be very hard so some effects may end up requesting larger than strictly necessary portions of the source data.

In this case your problem is a result of three factors in combination:

1. Specifying a reasonably but largish region to be evaluated
2. Specifying a very tiny scale factor - when largish region being evaluated is backprojected through the inverse of a tiny scale, the result is a very huge required source region
3. Using a complex filtering mode that only has limited backprojection support - this prevents the imaging runtime from realizing "aha, but I don't actually need to evaluate so much of the giant source region given that most of what I've been asked for is outside the actual bitmap"

My recommendation is to use linear filtering mode for most purposes.  The more advanced filter types like HighQualityCubic are intended mostly for photo viewer type applications which want the highest possible quality of scaling, but are usually only doing quite basic transforms (zooming to display at different size etc.)

**Comment by CMay** [comment]
Thanks for your thorough responses!

I set the MaximumCacheSize to 18446744073709551615 and it managed to run for longer than usual, so that did have some effect.

As for the effect runtime splitting up the work, I guess that means CanvasDrawingSession.EffectTileSize is relevant, but probably wouldn't make a difference in this case.

Since it was crashing at small scale values as you suggested, clipping the X scale and Y scale to 0.01 at minimum did solve it at least for this size of image.

For rotation it was happening occasionally at all manner of values, so that may be more related to the frequency and number of transformations it's trying to process.  Not sure.

For most of these basic transforms, it's probably reasonable to use the 3x2 DrawingSession.Transform instead of passing in a 4x4 to DrawImage when using interpolation modes 4 and 5, since the results seemed the same yet without exceptions.

As you said, it makes more sense to stick to Linear, but it's nice to know some of the gotchas involved when using the other modes.
