### ISSUE TITLE
CanvasBitmap::SaveAsAsync to png produces black image.

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Win2D#417]
I have the following snippet:
```C++
void MainPage::ScreenshotButton_Click(Platform::Object^ sender, RoutedEventArgs^ e)
{
    create_task(KnownFolders::PicturesLibrary->CreateFileAsync("screenshot.bmp", CreationCollisionOption::ReplaceExisting)).then([this](StorageFile^ file)
    {
        return create_task(file->OpenAsync(FileAccessMode::ReadWrite));
    }).then([this](IRandomAccessStream^ stream) {
        canvas->RunOnGameLoopThreadAsync(ref new DispatchedHandler([this, stream]() {
            create_task(screenshotBitmap->SaveAsync(stream, CanvasBitmapFileFormat::Bmp)).wait();
        }));
    });
}
```

`screenshotBitmap` was created from `CanvasBitmap::CreateFromBytes(...)` with `DirectXPixelFormat::B8G8R8A8UIntNormalized` and `CanvasAlphaMode::Ignore`. 

Saving as a Bmp works fine, but if I changed to `CanvasBitmapFileFormat::Png` the file that is saved is just a black image.

**Comment by shawnhar** [comment]
What data do you have in the alpha channel of the bitmap?  Even though you tell Win2D to ignore this, I don't think .png format has such an option so it will expect non-zero alpha.

**Comment by chuckries** [comment]
:+1: 
That's it, thanks! I had 0x00 for the alpha on every pixel. Changing it to 0xFF on every pixel made it work. Is this behavior documented anywhere?

**Comment by 13thsymphony** [comment]
Rendering pixel data with fully transparent 0x00 alpha is going to show up as black (or whatever the background of the renderer is), unless you've told the renderer to ignore alpha data or the data is stripped out.

The PNG format supports alpha:
https://en.wikipedia.org/wiki/Portable_Network_Graphics
and therefore the rendering is "by design".

While, by default, BMP does not:
https://en.wikipedia.org/wiki/BMP_file_format
(for compatibility purposes, Windows doesn't produce v5 BMP's that contain alpha by default)
and therefore the alpha data is stripped out and you will see your pixel values again.
