### ISSUE TITLE
TileEffect and DPI change has unexpected results

### ISSUE THREAD

**Issue by apollyonbob** [Microsoft/Win2D#429]
I've got a 96 DPI Bitmap image that is 1 x 64 pixels. It's used to create a background of arbitrary length on a progress bar. I used the TileEffect to stack a bunch of them together, as so:
`TileEffect middleBackgroundTile = new TileEffect() { Source = _barBaseMiddle, SourceRectangle = new Rect(0,0, _barBaseMiddle.Size.Width, _barBaseMiddle.Size.Height) };`

where _barBaseMiddle is a CanvasBitmap at 96 DPI.

So the problem is, on a 144 DPI system, this tiling has huge gaps between it. (Which seem based on screen size)

One way to fix it was as follows:
`TileEffect middleBackgroundTile = new TileEffect() { Source = _barBaseMiddle, SourceRectangle = new Rect(0,0, args.DrawingSession.ConvertPixelsToDips((int)_barBaseMiddle.SizeInPixels.Width), _barBaseMiddle.Size.Height) };`

But this seems very clunky - everywhere I reference the size of the bitmap I have to call ConvertPixelsToDips? Isn't the point of everything using Dips that I don't have to do this? 

Also, I'm not certain I understand why I have to do this. From my understanding, TileEffect should be taking Pixels, not Dips, so shouldn't the opposite be happening? Instead I'm passing a rect with a width of 0.66667 and a height of 64. 

Just looking for some clarification. Thanks for the help!

**Comment by shawnhar** [comment]
The behavior you are seeing is due to DPI compensation and rounding behavior applied to a very small (just 1 pixel wide) image.

When the effect system sees this 96 DPI bitmap connected to an effect graph that is being drawn at 144 DPI, it automatically inserts a DpiCompensationEffect in between the bitmap and the rest of your effects.  This scales up the image data to match the 144 DPI destination, which is normally exactly what you want.  But when you scale up a 1 pixel wide image by a factor of 1.5, the result has to be significantly rounded up or down, so now there is a weird mismatch where rounded pixel units and not-rounded dip units are out of sync.

The easiest solution is to do your tiling before rather than after the DPI compensation, so tiling will always happen in pixel rather than dip units.  To control this, insert your own DpiCompensationEffect after the tile effect, so instead of "TileEffect -> {auto DPI compenstation goes here if needed} -> bitmap" you have "DpiCompensationEffect -> TileEffect -> bitmap".

See the CreateCheckeredBackground helper from Example Gallery EffectsExample.xaml.cs for one place we did something similar.

**Comment by apollyonbob** [comment]
So I tried this: 
`            TileEffect uncompensatedTile = new TileEffect() { Source = _barBaseMiddle, SourceRectangle = new Rect(new Point(0,0), _barBaseMiddle.Size) };
            DpiCompensationEffect middleBackgroundTile = new DpiCompensationEffect() { Source = uncompensatedTile };`

And it still doesn't work. I get 
![barsample](https://cloud.githubusercontent.com/assets/3664956/18603287/18d6dd90-7c25-11e6-8857-8f8e520547a9.PNG) but only at 150%+ DPI scaling. At 100%, and 125% DPI scaling it's fine.
I also tried putting a DpiCompensationEffect with a SourceDPI of 144 (matching the screen DPI) to ensure that I disabled DPI compensation on the source, and that didn't work either. Am I doing the Source Rectangle wrong?

**Comment by shawnhar** [comment]
Please share a repro app (simplified as far as possible) so I can run and debug this.

**Comment by apollyonbob** [comment]
I am not gonna be able to get this repro this week, but I will get to it first thing Monday.

**Comment by apollyonbob** [comment]
Okay maybe not _first_ thing, haha. But here's a small repo project of the code I referenced above causing the issue.
[Win2DReproProject.zip](https://github.com/Microsoft/Win2D/files/496079/Win2DReproProject.zip)

**Comment by shawnhar** [comment]
Thanks for the repro!

I think what is going on here is that numerical precision leads to the tiling effect sampling slightly outside the limit of your 1-pixel wide bitmap.  By default when that happens, the effect system will insert zero transparency padding regions, which leads to the gaps you see here.

An easy fix is to insert a BorderEffect, which defaults to clamp behavior (rather than zero transparency) at the edges of the image:

                uncompensatedTile = new TileEffect()
                {
                    Source = new BorderEffect
                    {
                        Source = _barBaseMiddle,
                    },
                    SourceRectangle = new Rect(new Point(0, 0), _barBaseMiddle.Size)
                };

**Comment by apollyonbob** [comment]
Thanks, that worked!
