### ISSUE TITLE
CanvasControl draw only on part of it

### ISSUE THREAD

**Issue by gaminn** [Microsoft/Win2D#436]
Hi,
I want to draw on one part of CanvasControl and I want the other part to retain what was drawn on it previously. How to do it?

**Comment by shawnhar** [comment]
The best way to do this depends on whether you absolutely need the other parts of the image to retain previously drawn contents, or just want to skip unnecessary redrawing as a performance optimization.

If the latter, use CanvasVirtualControl instead of CanvasControl.  That allows you to specify just specific regions to be invalidated and redrawn.  Note however that other system interactions may cause more or even all of the control to be invalidated, so you must be prepared to handle RegionsInvalidated events for any of the control surface at any time.

If you absolutely need your previously drawn data to be retained at all times, draw it to a rendertarget instead of directly to the control, then draw the rendertarget onto the CanvasControl.  Now you can redraw whatever pieces of the rendertarget you like whenever you like (then copy the whole thing to the CanvasControl each time it changes).

**Comment by gaminn** [comment]
Thanks for the explanation, very useful!
