### ISSUE TITLE
Invalidate on HighContrastChanged

### ISSUE THREAD

**Issue by mtaron** [Microsoft/Win2D#447]
I'd like to support the [high contrast theme ](https://msdn.microsoft.com/en-us/windows/uwp/accessibility/high-contrast-themes) in my app and I find myself having to repeat a pattern over and over that might be useful to have in Win2D itself.

In order to redraw when HighContrast mode is triggered, I do this in every UserControl that contains a Canvas*Control:

``` csharp
private AccessibilitySettings accessibilitySettings;

private void OnLoaded(object sender, RoutedEventArgs e)
{
    // The docs say this constructor must be called "from a scope where the app
    // is initialized and is already displaying content."
    this.accessibilitySettings = new AccessibilitySettings();
    this.accessibilitySettings.HighContrastChanged += this.HighContrastChanged;
}

private void OnUnloaded(object sender, RoutedEventArgs e)
{
    if (this.accessibilitySettings != null)
    {
        this.accessibilitySettings.HighContrastChanged -= this.HighContrastChanged;
        this.accessibilitySettings = null;
     }
}

private void HighContrastChanged(AccessibilitySettings sender, object args)
{
    this.Canvas.Invalidate();
}
```

I think it would also make sense for `CanvasCreateResourcesReason` to include a HightContrastChanged reason and for the `CreateResources` event to be triggered on HightContrast changes as well in case folks want to load different resources.

What do you think?

**Comment by shawnhar** [comment]
I don't think it would be a good idea for theme changes to invoke CreateResources.  That is a very big/expensive hammer, typically leading to recreation of all resources rather than just a redraw.  (DPI change is a partial exception as that doesn't always require full recreation of everything, but we felt it best for that to default to the aggressive solution that's most likely to work for developers who haven't thought about the DPI change case, while providing an opt-in for those who want to handle this more carefully by only doing partial recreation).

Contrast change, though, typically only needs a redraw rather than any actual recreation of resources.  And many apps don't need to handle it at all, which makes doing nothing a reasonable default.

**Comment by mtaron** [comment]
Kinda sad that supporting high contrast is seen as a thing few apps need to do. :(

**Comment by shawnhar** [comment]
Many apps use XAML for all their UI elements, often in ways where high contrast "just works" automatically, while drawing other non-UI things with Win2D.  For instance if they're using Win2D to process a photo, that photo rendering doesn't change in response to UI contrast settings.

A low level graphics rendering API like Win2D does not know the intent of what it is being asked to draw, so it's not appropriate for it to provide the same kind of automatic high policy behaviors that something like XAML would.

**Comment by mtaron** [comment]
There are of course non-UI uses of Win2D, but the Canvas Controls are the intersection of Win2D and XAML, right? I think they should "just work" in the same way that other Windows XAML controls do, i.e. update themselves on theme changes. They should be accessible by default instead of requiring additional work in every app (and for every control instance) to make accessible.

For example, here is the Font Metrics sample in the base theme:
<img width="828" alt="black" src="https://cloud.githubusercontent.com/assets/7683976/19868337/d9b3ca5c-9f64-11e6-8b3b-bff67d35aa35.PNG">

And here it is in High Contrast White:
<img width="911" alt="white" src="https://cloud.githubusercontent.com/assets/7683976/19868361/f4689c38-9f64-11e6-9f29-ded0c77819af.PNG">

**Comment by shawnhar** [comment]
Example Gallery is definitely not themed correctly (along with many other flaws: we didn't put in the time to make this 100% correct robust UI).

But I think the right place to fix that is in the example source code.  This isn't something Win2D can handle automatically because it doesn't know the purpose of the things that being drawn.  A Win2D app may choose to read colors from the current UI theme, or have its own color management system, or it might be something like a game where that whole concept just doesn't apply.
