### ISSUE TITLE
CanvasDrawingSession.DrawInk() doesn't draw Highlighter ink in CanvasCommandList

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/Win2D#462]
Ink that has InkDrawingAttributes.DrawAsHighlighter=true will draw fine when used directly like this
session.DrawInk(ink);

but will not draw when used in a command list session:
using (var list = new CanvasCommandList(session))
{
    using (var listSession = list.CreateDrawingSession())
    {
        listSession.DrawInk(ink);
    }

    session.DrawImage(list);
}

**Comment by shawnhar** [comment]
The problem is not with the command list itself, but with the blend mode you are using when later drawing the command list image.  Highlighter ink uses a min blend mode, but by default your DrawImage call will be using standard sourceover blend.  You'll need to configure that DrawImage call to match the blend operations used by the highlighter rendering, which as far as I know are not documented anywhere :-(

In general, highlighter ink is best drawn directly over whatever image you want it to highlight.  Trying to cache this kind of ink in intermediate surfaces gets surprisingly complex.

See issue #428 and http://stackoverflow.com/questions/36397638/win2d-uwp-wont-save-a-highlight-stroke-in-an-inkcanvas/36509014#36509014 for discussion of similar issues.

**Comment by christianrr** [comment]
Found a possible solution to this bug:

1) Create a separate canvas control for the highlighter strokes and one for the normal "pen" strokes (the important thing is to set the CompositionMode of the highlighter's texture to **MinBlend** to blend the highlighter strokes with underlying background):

`<xaml:CanvasControl x:Name="UxHighlighterInkTexture" Draw="OnRepaintHighlighterInkTexture" CompositeMode="MinBlend" />`
`<xaml:CanvasControl x:Name="UxInkTexture" Draw="OnRepaintInkTexture" SizeChanged="OnInkTextureSizeChanged"/>`

2) In the second stage, draw the highlighter strokes on the highlighter canvas control in a two-step approach: First, draw the strokes as non-highlighter strokes into the texure to form the background to make highlighter strokes appear and then in a second stage draw the highlighter strokes on top of the non-highlighter strokes to blend all the strokes into each other.

```
// render highlighter strokes
var highlighterStrokes = strokesToRender.Where(stroke => stroke.DrawingAttributes.DrawAsHighlighter).ToList();

// set DrawAsHighlighter to false temporary
foreach (var stroke in highlighterStrokes)
{
	var attributes = stroke.DrawingAttributes.Clone();
	attributes.DrawAsHighlighter = false;
	stroke.DrawingAttributes = attributes;
}

// draw highlighter strokes (1st pass) - background to make texture blending work
session.DrawInk(highlighterStrokes);

// restore attributes
foreach (var stroke in highlighterStrokes)
{
	var attributes = stroke.DrawingAttributes.Clone();
	attributes.DrawAsHighlighter = true;
	stroke.DrawingAttributes = attributes;
}

// draw highlighter strokes (2nd pass) - adds blending of strokes
session.DrawInk(highlighterStrokes);
```

With that solution, I was able to reproduce the normal InkCanvas behavior. The first step blends your highlighter strokes with any underlying content, while the two-step approach in the second stage blends the internal highlighter strokes against each other.
