### ISSUE TITLE
Hit Testing CanvasGradientMesh?

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/Win2D#472]
How do you hit test a CanvasGradientMesh?  I need to figure out if a point is inside or outside the mesh

**Comment by clandrew** [comment]
Unfortunately, it's not currently possible to hit-test gradient meshes in the same way as other geometries, because it's not exposed that way in Direct2D (which Win2D is built on top of). In Direct2D, ID2D1GradientMesh isn't exposed to us as an ID2D1Geometry.

As a workaround, it's possible to get from a gradient mesh to the geometry for its patches, and hit test against that.
For example:
```
        CanvasGeometry GetFillGeometry(CanvasGradientMeshPatch patch)
        {
            CanvasPathBuilder pathBuilder = new CanvasPathBuilder(canvasControl);
            pathBuilder.BeginFigure(patch.Point00);
            pathBuilder.AddCubicBezier(patch.Point01, patch.Point02, patch.Point03);
            pathBuilder.AddCubicBezier(patch.Point13, patch.Point23, patch.Point33);
            pathBuilder.AddCubicBezier(patch.Point32, patch.Point31, patch.Point30);
            pathBuilder.AddCubicBezier(patch.Point20, patch.Point10, patch.Point00);

            pathBuilder.EndFigure(CanvasFigureLoop.Closed);

            CanvasGeometry geometry = CanvasGeometry.CreatePath(pathBuilder);

            return geometry;
        }

        bool HitTest(CanvasGradientMesh gradientMesh, Vector2 point)
        {
            foreach(var patch in gradientMesh.Patches)
            {
                if (GetFillGeometry(patch).FillContainsPoint(point))
                {
                    return true;
                }
            }

            return false;
        }
```

The limitation of this workaround, is doesn't cover all cases. It covers the cases where the fill you want lies within the geometry whose contour is the four bezier edges of the patch. To put this in more visual terms, for example the magenta area would work:
![gradientmesh](https://cloud.githubusercontent.com/assets/8118775/21298743/910f688c-c549-11e6-9120-175f75d2317c.png)
So the suitability of that workaround depends on what type of gradient meshes you're dealing with.

**Comment by mscherotter** [comment]
OK - that's helpful - on the [FillContainsPoint()](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_FillContainsPoint_1.htm) API that takes a Matrix3x2 - is that the transform to apply to the point before doing the hit testing or the transform to apply to the geometry?

**Comment by clandrew** [comment]
The transform is applied to the geometry, not the point. Thanks for raising that question- I'll make a note to update our docs to say that.

For flattening tolerance- many geometry operations, including FillContainsPoint, will internally do an operation called "flattening" which is a conversion of curves into very short line segments. The choice of how short to make the line segments is controlled by the flattening tolerance. The ideal choice will depend on how your geometry is scaled. 

For most situations, especially if you're not scaling anything, you can just use [CanvasGeometry.DefaultFlatteningTolerance](http://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_DefaultFlatteningTolerance.htm). If you want to cover your bases, then you'd use [CanvasGeometry.ComputeFlatteningTolerance](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_Geometry_CanvasGeometry_ComputeFlatteningTolerance_1.htm), which takes in some scaling information and gives you back a flattening tolerance.

**Comment by clandrew** [comment]
Additionally, as another workaround option, you could consider using a [CanvasRenderTarget](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasRenderTarget.htm) intermediate. You'd clear it to black, say, and draw a gradient mesh with all its patch corners set to white, say- and do a readback using [CanvasRenderTarget.GetPixelColors.](https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasBitmap_GetPixelColors_1.htm) Then test whether the color read back is black or white to determine a hit. The advantage of this workaround is it'll work in a far larger majority of cases, compared to the other one. The disadvantage is it has significant performance and memory costs.

Separately, I've mentioned the missing feature support to the Direct2D folks so that it's something they know about.

**Comment by clandrew** [comment]
Since I don't see any additional action for us, I'm going to close this issue. But, feel free to re-open it if you need anything else.
