### ISSUE TITLE
CanvasGeometry.CreateRoundedRectangle with negative radiusX and radiusY

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/Win2D#483]
If I call the **CanvasGeometry.CreateRoundedRectangle()** method with negative RadiusX and RadiusY then resulting geometry is the same as the rounded rectangle with positive RadiusX and RadiusY  values.

Is the sign of RadiusX and RadiusY simply ignored?

**Comment by ratishphilip** [comment]
I have noticed the same behavior for **CanvasGeometry.CreateCircle()** and **CanvasGeometry.CreateEllipse()** methods too. It seems only the absolute values of the radii are taken and the sign is ignored.

Is this the correct behavior?

**Comment by clandrew** [comment]
Yes, that's correct, and by design- this is a carried-over behavior from Direct2D, which always takes the absolute value of RadiusX/RadiusY for ellipses and rounded rectangles. 

A negative radius hardly seems valid for these, so perhaps another option for Direct2D would have been to fail the call. However, as a convention, Direct2D tends to avoid floating-point comparisons and failing API calls based on that. Floating-point-comparisons are a tricky thing and can lead to problems. So, it sanitizes these inputs by taking the absolute value (ignoring the sign).

**Comment by ratishphilip** [comment]
Thanks for the clarification.

**Comment by clandrew** [comment]
No problem!
