### ISSUE TITLE
[Question] Creating a new CanvasBitmap every frame vs. CanvasBitmap.SetPixelBytes

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Win2D#525]
I am using a CanvasAnimatedControl and I need to update the bytes of a CanvasBitmap on every frame. Is there a major difference between calling CanvasBitamp.CreateFromSoftwareBitmap() every frame vs creating the bitmap up front and calling CanvasBitmap.SetPixelBytes() every frame?

**Comment by shawnhar** [comment]
Changing the contents of an existing bitmap is much more efficient than creating an entirely new one.

But backing up a level, sending new bytes to the GPU every time you draw is not usually a good approach for performance.  For really efficient GPU rendering, think about if there's some way to preload all the texture data you will need so the different images can then be generated entirely using GPU drawing operations rather than CPU -> GPU data transfers.

**Comment by chuckries** [comment]
In my scenario I am calculating the bitmap bytes on every frame in response to user input, so it is impossible to not reset the bytes of the bitmap on every frame.

**Comment by shawnhar** [comment]
I'll need more info about what you are doing to give more accurate advice. Keeping to generalities, though, generating bitmap data on the CPU every frame before uploading this to the GPU is not usually the best way to go about things if you care about performance.  Uploading a smaller set of input data and doing the heavy lifting of generating pixel values on the GPU itself will almost always be faster.

**Comment by chuckries** [comment]
I am working on an emulator for 8-bit/16-bit video game systems. So far I have been using a CanvasAnimatedControl. On Update I calculate the next emulated frame and on Draw I simply set the bytes of a CanvasBitmap and draw it. I'm not sure if there is a more efficient way to do this.

**Comment by shawnhar** [comment]
Ok, that's definitely a special case!  The graphics programmer in me still says that offloading work to the GPU is better than uploading bitmaps all the time (eg. you could upload just whatever memory controls the display state of the original HW, and have the GPU do the emulation work to generate an actual bitmap image from that state) but for an emulator it's probably reasonable to leave all that on the CPU.  Not really the typical kind of usage that Win2D is designed for :-)

**Comment by chuckries** [comment]
>Not really the typical kind of usage that Win2D is designed for :-)
This is what I've realized more as I've worked with it, but the CanvasAnimatedControl is so helpful for what I need. It's awesome to have such a simple drop in game loop. 

Thanks for the help!

**Comment by chuckries** [comment]
One last question along these lines: In this scenario, where I would be sending new bytes to the GPU on every frame, could it be more efficient to force software rendering?

**Comment by shawnhar** [comment]
> could it be more efficient to force software rendering?

I doubt it.  The data has to end up on the GPU at some point in order to be displayed, so using a software rasterization device would just defer when that upload happens from your own rendering code to dcomp/dwm.

If in doubt, though, try it and see.  I haven't spent much time thinking about this type of workload, so am just making (hopefully somewhat informed!) guesses here.
