### ISSUE TITLE
Win2D and Fluent Design

### ISSUE THREAD

**Issue by CMay** [Microsoft/Win2D#527]
I'm curious if any of the changes coming for the Fluent Design System are going to influence the Win2D API, since I recall that parts of Win2D are used for the XAML UI stuff.  One thing in particular is that for FDS one of the new focuses is on depth and obviously that sounds like more of a D3D thing unless the plan is to do faux 3D using layers and scaling.

Just wanted to get a read on how Win2D is positioned relative to these improvements.  Thanks!

**Comment by shawnhar** [comment]
Win2D doesn't need any new features to accommodate the latest UI design language, as it is already more than capable of doing all the effects you've seen people talking about.  The Win2D/D2D effects system focuses on general purpose building blocks that can be assembled to create a huge range of different image manipulations etc, so new design styles are typically just a matter of configuring these blocks in different ways rather than needing to add new ones.

I believe the composition APIs will be enhanced to enable some of these new interaction models, but Win2D will not be affected.

**Comment by CMay** [comment]
Yeah, I know Win2D can technically do everything I've seen of Fluent Design, I just thought it was possible they might have wanted to optimize even further by extending Win2D a bit.  Thanks for the clarification, Shawn.
