### ISSUE TITLE
Usage within user controls and per instance memory usage

### ISSUE THREAD

**Issue by jcmm33** [Microsoft/Win2D#53]
We are looking to utilise Win2D in a few of our user controls on Windows Phone, but we've noticed that the per instance memory usage can be quite high, approx 1.5MB according to the profiler. 

Given that one of the controls we are looking at using Win2D for is related to textual effects and there could quite easily be quite a few instances are they any ways which we can reduce the memory footprint? 

It should be noted that these controls don't utilise any animations but rather utilise the GPU for speedier rendering of effects.

**Comment by shawnhar** [comment]
The high memory use is because every instance of CanvasControl currently uses a separate CanvasDevice, which basically means firing up its own separate copy of the entire graphics stack.

This will be addressed by the [backlog](https://github.com/Microsoft/Win2D/wiki/Backlog) item "*Multiple controls should share a single CanvasDevice*".

A possible workaround before we get to that item would be to use CanvasImageSource instead of CanvasControl, and manage the shared device yourself.  You can either just directly new up a CanvasDevice, or use a hidden CanvasControl to create it for you (the latter has the advantage that the CanvasControl will still handle things like lost devices and DPI change for you).  Then for each control that wants to use Win2D, create a separate CanvasImageSource using this single shared CanvasDevice.   Place an Image object in your XAML tree, assign the CanvasImageSource to its Source property, and use CanvasImageSource.CreateDrawingSession whenever you want to redraw the image.

**Comment by shawnhar** [comment]
This is fixed in Win2D 0.0.21, which was released today.   CanvasControl instances now default to all sharing a single CanvasDevice.
