### ISSUE TITLE
Get bytearray from ICanvasImage

### ISSUE THREAD

**Issue by SeriousGeorge** [Microsoft/Win2D#537]
Is there currently a way to get the bytearray from ICanvasImage?

Reason:
I want to copy the content of an edited image (with win2d effects, like exposure etc) to a traditional xaml image.

If not possible, alternativley to writeablebitmap or even to Windows.UI.Composition.Visual?

**Comment by shawnhar** [comment]
You can get pixel data bytes from a CanvasBitmap or CanvasRenderTarget, but not directly from an arbitrary image (because not all image types are represented by concrete pixels at all).

If your image is not already a bitmap, either draw it onto a rendertarget, or use CanvasImage.SaveAsync to rasterize it into an encoded format such as .png or .jpg.

**Comment by shawnhar** [comment]
Closing issue as this question has been answered.
