### ISSUE TITLE
DrawLine "strokeWidth" parameter not working as expected

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/Win2D#542]
Hello, I'm using a `CanvasControl` in my app to render some parts of the UI and I'm having some issues with the `DrawLine` method. I'm working on a code editor and one of the IDE features is the ability to display the column guides (just like VS2017 does by default).

At first I implemented this by using XAML `Line`s objects in a `Canvas` and then moving everything to the right coordinates by editing the offset of the `Visual` of each `Line`, but that of course isn't efficient at all.
Each `Line` has a width of 1 pixel (1 DIP), and on my screen at 100% scaling I get a nice 1-pixel wide line.

Then I decided to switch to a `CanvasControl` to draw all the various text overlays in there.
But, I'm having some trouble with the `DrawLine` method I'm using, as this line:

```csharp
// Assume I'm inside the Draw event handler here and I already have my
// x, y0 and height values for each line ready
CanvasStrokeStyle style = new CanvasStrokeStyle { CustomDashStyle = new[] { 4f, 4f } };
args.DrawingSession.DrawLine(x, y0, x, y0 + height, stroke, 1f, style);
```

**This is the result of both approaches**:
![Comparison](http://i.pi.gy/GLzo.png)

As you can see, each XAML `Line` has crisp 1\*4-pixel dashes, while each Win2D line is basically 2\*8, and moreover the initial and ending 2\*1-pixel area is blurred (it has a lower opacity).
I've also tried to set the Win2D line stroke to 0.5 (I though, if 1 gives me a 2-pixel wide line, maybe 0.5 will do it), but that was quite a naïve try and it failed, I still got my 2-pixel wide lines.

Am I missing something here? I couldn't find anything related to this issue in the official docs.
Thank you in advance for your help!
Sergio

**Edit**: using the `FillRectangle` method with a 1-pixel wide `Rect` draws a 1-pixel wide line as expected, even though there isn't an overload for this method to support a custom `CanvasStrokeStyle`, so I can't use this over the `DrawLine` method.

**Edit 2**: as a temporary workaround, I wrote this small snippet to be able to draw a dashed line using the `FillRectangle` method. It works fine and this way [I manage to get a 1-pixel wide line](http://i.pi.gy/YdgO.png), but of course it's not even as close to the efficiency of the built in `DrawLine` method.

```csharp
foreach (LineCoordinates line in lines) // Assume I already have my lines coordinates ready here
{
    double y = 0;
    while (y <= line.Height)
    {
        args.DrawingSession.FillRectangle(new Rect
        {
            Width = 1,
            Height = y <= line.Height - dash ? dash : line.Height - y,
            X = line.X,
            Y = line.Y + y
        }, Colors.DimGray);
        y += dash * 2;
    }
}
```

**Comment by shawnhar** [comment]
This is probably caused by antialiasing, if the lines are positioned in between two texels.  Try adding 0.5 to your x and y coordinates, to center in the middle of a single texel.

Another possibility is if your DPI is not 96, so you might be getting some DIP to pixel scaling going on?

CanvasStrokeTransformBehavior.Hairline can be useful if you want to force single pixel lines regardless of DPI or antialiasing.

**Comment by Sergio0694** [comment]
Hello @shawnhar - thank you for your  quick reply!
I'm doing these tests on a 23" 1920*1080 screen at 100% scaling, so it shouldn't be a scaling issue.
I've tried using the `CanvasStrokeTransformBehavior.Hairline` option but that didn't help, then I've tried shifting the coordinates by 0.5 as you suggested and that worked, I'm now getting a 1-pixel wide line as expected 😄 

I have a couple of questions:
1) Why does the `DrawLine` have this issue, while the `FillRectangle` doesn't seem to be affected by the antialiasing problem at all, even when drawing a 1-pixel wide rectangle at the same coordinates (so that it's basically a line)?
2) I managed to get a 1-pixel wide line with 3-pixel dashes and 3-pixel spaces with this code:
```csharp
CanvasStrokeStyle style = new CanvasStrokeStyle { CustomDashStyle = new[] { 2f, 4f } };
args.DrawingSession.DrawLine((float)line.X + 0.5f, (float)line.Y - 0.5f, (float)line.X + 0.5f, (float)(line.Y + line.Height + 0.5f), Colors.DarkGray, 1, style);
```
But I mean, I found those `{ 2f, 4f }` values for the dash style manually, and I don't even understand why even if they're two different values (2 and 4) I end up with evenly sized dashes and spaces (3-pixel each).
Is there a general way to calculate this? Can I be sure that after these tweaks, the rendering will keep being fine and crisp even on devices with a different DPI setting?
Or, is there a way to disable the antialiasing, since that appears to be the cause of the issue?

Thanks again!

**Comment by clandrew** [comment]
If you always want "crisp" rendering (where in this case, "crisp" means "locked to pixel boundaries") then you definitely want to disable antialiasing- you'll get a performance boost as an added bonus. To disable antialiasing, set the drawing session's [Antialiasing](https://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_CanvasDrawingSession_Antialiasing.htm) property to Aliased.

Answering your questions-
1. When you stroke a piece of geometry, Win2D will generate a line that exactly straddles the geometry, right down its middle. Whereas when you fill a geometry, Win2D will fill that geometry's interior. 
So when you fill a rectangle, nothing will go outside the rectangle. But when you stroke a rectangle, you'll be creating a line that straddles the actual rectangle you specify.

2. With the custom dash style of {2, 4}, your dash length should indeed be of length 2 but you might be seeing some extra part due to a square cap. Do you still see this behavior if you set the stroke style's DashCap to Flat?

The way to guarantee pixel-locked rendering at weird DPIs is to use aliased rendering, for sure. And avoid very small geometry that could be <0.5 pixels in size on some devices, since of course those pixels would be dropped out.

The idea of how lines are stroked in Win2D is touched upon more in this issue, here:
[CanvasDrawingSession.DrawRectangle bug #28](https://github.com/Microsoft/Win2D/issues/28#issuecomment-313973108)
