### ISSUE TITLE
Cannot create screen-size CanvasRenderTarget for Windows Phone

### ISSUE THREAD

**Issue by pleaseking** [Microsoft/Win2D#55]
I have just met a problem: I am trying to create a Screen-sized CanvasRenderTarget on my Windows Phone (Lumia 1520, WP 8.1). I am getting 'Invalid arguments' exception, and my code is:

    m_renderTarget = ref new CanvasRenderTarget(canvasControl, (float)m_nWidth, (float)m_nHeight,
      DirectX::DirectXPixelFormat::B8G8R8A8UIntNormalized, CanvasAlphaMode::Premultiplied);
where `m_nWidth == 1080` and `m_nHeight == 1864`.

The most weird for me is that CanvasBitmap of the same size just got created one line above without any issues. 
Same code on Windows works fine too - CanvasRenderTarget gets created without issues.

**Comment by shawnhar** [comment]
Where do these values of m_nWidth and m_nHeight come from?   It looks to me like they are in pixel units rather than dips, but that overload of CanvasRenderTarget specifies its size in dips.   Since Luma 1520 is a high DPI device, that means the size will get scaled up further when converting dips to pixels, so my guess is it's going past the maximum GPU texture size.

If I'm right, you can fix this by specifying your render target in dips (such as you get from CanvasControl.Size), or if you prefer to work in pixel units, use the CanvasRenderTarget constructor that takes a dpi parameter and pass 96 to specify 1:1 dip <-> pixel mapping.

**Comment by pleaseking** [comment]
Thanks a lot - this helped (the second option). Closing then.
