### ISSUE TITLE
How to draw a single line in a word wrapped CanvasTextLayout

### ISSUE THREAD

**Issue by BillHenning** [Microsoft/Win2D#553]
Hello, I have a word-wrapped CanvasTextLayout, and for example purposes, let's say it has three total lines in it.  I want to be able to get the size of each line, and also be able to render a single specific line such as the middle one.  

Right now it seems like I can only render all of them at once, which causes problems for my needs.  Is there any way to do this?

**Comment by shawnhar** [comment]
You could query line metrics to see which characters word wrapped into each line, then make a new text layout containing only the characters for the specific line that you want to draw.

Another approach would be to implement a custom text renderer, and have it discard all glyph runs except the ones on the line you want.

**Comment by BillHenning** [comment]
Thanks for the quick reply.  I'd prefer to avoid having to duplicate all the work of constructing duplicate CanvasTextLayouts as a workaround.  

Do you have any examples on the custom text renderer approach too?  But that sounds complex.

Is it possible for you to add overloads of layout.DrawToTextRenderer (or similar) to be able to specify the zero-based index of the single line to draw?  This API for example:

`layout.DrawToTextRenderer(textRenderer, x, y, 1);  // 1 means the second line in a word-wrap scenario`

That's my ideal solution and would prevent tedious workarounds because we could use the same object. 

While I'm writing, it would be handy if the layout.LineMetrics entries also included X, Width, and Y properties.  Right now, Y can probably be calculated by adding up the Height of entries before it.

**Comment by clandrew** [comment]
Another option could be to use a [CanvasActiveLayer overload](https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasDrawingSession_CreateLayer_8.htm) which takes a clip rect, and just clip out the text you don't want to draw.

**Comment by BillHenning** [comment]
@shawnhar - I was still hoping to get your feedback on my suggestion for API addition mentioned above.  I wouldn't think it would be too hard for you to add that, and it would prevent having to do the clip workaround, which while works, probably wastes extra rendering cycles.

**Comment by shawnhar** [comment]
This wouldn't be a simple thing to add to Win2D, because Win2D is just a wrapper on top of Direct2D which also has no direct way to do what you are wanting.  Win2D sometimes add convenience helpers on top of the underlying Direct2D functionality, where a commonly used operation can be expressed in terms of multiple D2D operation strung together.  That's not the case here, though - firstly because this is not something that can easily be expressed by combining existing D2D operations (the cost of adding something new to D2D is much higher than just adding a helper to the Win2D layer), and secondly because it's not that commonly used an operation.  Sorry!
