### ISSUE TITLE
Using straight alpha for effects which will not be rendered

### ISSUE THREAD

**Issue by CMay** [Microsoft/Win2D#557]
I've been looking through the supported pixel formats for Win2D along with the documentation for effects and I'm not sure if there's some other way around this issue.

There doesn't seem to be a full R8G8B8A8 straight alpha pixel format supported both in a CanvasBitmap and for an Effect sampler input.  It sounded like you can work with this in an effect, but you have to pass your CanvasBitmap through an unpremultiply and premultiply effect causing it to be processed 3 times.  I understand if you use shader linking then it's more like prepending and appending some code to your Effect while maintaining a single pass, but it's still extra processing which adds up.

The bitmaps I want to process are 4K+ and multiple will be processed at once, so processing each 3 times is undesirable.  Is the only option to drop down to D3D just to run Effects there, then only pass the result to Win2D when I have something to render?

It seems like it would be much cleaner to just be able to use a straight alpha pixel format that Win2D won't accept when rendering.  I understand there might be performance concerns in adding a check for the pixel format each time or complexity issues in having to add more overloads.

Am I mistaken in some way about this limitation?

**Comment by shawnhar** [comment]
D2D (and thus Win2D) basically only supports premultiplied alpha.   There is some very limited support for straight alpha formats in a few narrow places, but the vast majority of the rendering implementations assume premultiplied data.  There are all kinds of reasons for this choice (in short: premultiplied alpha format is really the Right Thing to use for almost all purposes in computer graphics...)

Converting is generally not that expensive if you need to manipulate straight alpha data for some reason.  I'd start, though, by asking if there's any way you can switch your bitmaps over to premultiplied format?

**Comment by CMay** [comment]
Hey Shawn, thanks for the response.

My problem is that in these shaders I'm not doing "computer graphics" and no alpha blending will occur.  None of the values will ever be rendered to the screen.  I'm using GPU acceleration to do data transformation and afterwards a shader will interpret that result visually.  The final result will be premultiplied, but everything inbetween will be straight.

These values might be touched multiple times in the same frame, so suddenly the seemingly low cost of premultiplication increases rapidly.  It's not only a matter of the format they're loaded as on the GPU either, but on unified memory architectures there's more value in feeding a result back for the CPU to work on as well.


To me it looks like I have a few options:

- Take the performance hit and un/premultiply every shader input.

- Do delayed unpremultiply by only unpremultiplying specific values as they are used.

- Only use formats which don't have alpha and split the data up into multiple bitmaps, but this means having to do a second pass to process the other bitmap too if all 4 values need to be written to.  The overhead of this is probably worse than just unpremultiplying.

- Increase the size of the bitmap to store the 4th value in the R G or B of an adjacent texel.

- Try to pack the 4th value into one of the other 3.  Bit packing in a single value may or may not be a win relative to just doing the multiplication.

- Fall back on Direct3D.


I don't think that most methods in Win2D or Direct2D would need to support straight alpha considering an RGBA straight format will never need to be passed into them.  So long as using it is explicit enough that people don't use it by accident, maybe it wouldn't be a problem.

Since this goes down to Direct2D and the Fall Creator's Update is already around the corner, adding something like this would probably take until mid next year or so if it were accepted for consideration?

**Comment by shawnhar** [comment]
I don't think there is much chance of getting more support for straight alpha formats in Direct2D image effects, sorry.

However, if you are mostly doing non-graphical number crunching type work, this may not be necessarily.  The difference between straight and premulitplied alpha is only significant for effects that interpret the data as color values (eg. saturation, the various photo adjust type filters like exposure and highlights/shadows, etc.)   The more numerical operations (color matrix, table lookups, convolve filters) fundamentally just operate on numerical values, and don't really care what these numbers represent.

For instance if you use a ColorMatrixEffect with AlphaMode set to premultiplied, that just applies the matrix to the input data as-is.  If you have non-premultiplited data in your source (but tell the ColorMatrixEffect it is premultiplied) you get a matrix applied to non-premultiplied data with no extra conversions.

**Comment by CMay** [comment]
So am I just mistaken about how premultiplied assets work?

My understanding is that if you're using a premultiplied texture format, then the values stored in the R, G and B components are multiplied by the A component which evenly reduces the luminosity as the opacity decreases.  This solves a number of color blending issues, but is not a lossless process.  A side benefit is that if your opacity is less than 255, none of the R G B values can ever be 255.  You essentially reduce the available value range for the other components relative to the alpha.  This becomes efficient for storing values when your alpha is below 128, because you can save bits knowing you only have to store lower values.

If you pass that premultiplied texture into a shader with no other linked shaders, then by default the texel reads will return the premultiplied values from the texture.  As a result, if you only care about values closer to the originals, you have to unpremultiply and may not even get the original values unless you apply some additional constraints to the values you use.

However, it sounds like you are saying that there is no inherent requirement that the values in these premultiplied textures actually be premultiplied.

**Question:** The documentation says that if you load a bitmap, it is automatically converted to a premultiplied format.  The CanvasBitmap load options do have some overloads for setting the alpha mode, but it's not really clear what it does for these different modes if it thinks there's a mismatch.  I tried looking at the Win2D implementation, but any conversion must be happening in the Direct2D codebase and not in Win2D's.

**Question:** If I'm interpreting what you're saying correctly I could write to a format that Win2D assumes is premultiplied to avoid Win2D's automatic conversion and still use the full value range for all 4 components, then simply lie about it being premultiplied?  The consequence would be odd results if I tried to use that texture with Win2D methods that expect premultiplied input, I guess.  That would be fine.

**Question:** If that would work, then what formats does Win2D accept abnormal premultiplied data from?  The only explicit mention I could find in the documentation was BC1-3 support and how to convert your bitmaps to premultiplied DDS files.  While BC3/DXT5 is great, I think it's too limited for what I want.  I suppose I might need to manually load my bitmaps then feed the right bytes into CanvasBitmaps that have their alpha mode set to premultiplied?

**Question:** If the CanvasBitmap PixelColor methods convert colors from straight to premultiplied, is there a way to bypass that conversion or would I need to use the PixelBytes methods?

I appreciate you taking the time.

**Comment by shawnhar** [comment]
> So am I just mistaken about how premultiplied assets work?

You aren't quite mistaken, but I think you are assuming there is more going on than there really is.

At the graphics hardware and D3D levels, there is no such concept as straight vs. premultiplied alpha.  There are just numbers, which are stored in textures, sampled by shaders, manipulated by math, and written to output surfaces.  It is entirely up to you to determine what these numbers mean, and then write your shaders to apply the appropriate kind of computations to them.

This changes at the D2D level, because D2D provides its own shaders which implement common rendering algorithms.  These shaders need to make some assumptions about what format their input and output data is in, hence why D2D image formats include the concept of an alpha format alongside D3D level concepts such as bit depth and number of color channels.  Almost everywhere in D2D, the choice is to support premultiplied alpha only, so the vast majority of things just read data from a texture, do math on it assuming the data is premultiplied, and write the result to an output which they also assume is premultiplied.  If you call one of these APIs with a bitmap that has some other alpha format, they will fail with a not supported error.

A small number of D2D APIs, on the other hand, include support for multiple alpha formats.  These will not fail when passed bitmaps that specify use of non-premultiplied alpha, but instead will dynamically select a different implementation path that makes different assumptions about how the data needs to be manipulated.

All of that boils down to, there's no rule that the data you put in a D2D bitmap actually has to be premultiplied.  As long as you don't tell D2D to apply any alpha format conversions to the data (eg. by setting ColorMatrixEffect.AlphaMode to something other than its default value), you can put arbitrary data using whatever numerical encoding you like in a bitmap, run whatever D2D effects you like over it, get the result back in a D2D rendertarget, and then do whatever you like with that result.

If what you do with the result is to DrawImage it onto a CanvasControl, it had better be in a premultiplied format, since that is what DrawImage and CanvasControl will assume.  And if the way you process it is eg. to run a HighlightsAndShadowsEffect over it, that data had better be premultiplied, since that effect will produce garbage if fed any other kind of data.  But as long as you use only effects that have more narrowly defined numerical operations (eg. matrix transform, arithmetic composite, convolve, table lookup) as opposed to being specifically color based operations, then it is all just math being applied to numbers, and math is math regardless of how you choose to interpret the numbers that go into and come out of it.

> If you pass that premultiplied texture into a shader with no other linked shaders, then by default the texel reads will return the premultiplied values from the texture.

Slight correction: the texel reads always just return whatever values are stored in that texture.  Ther is never any automatic conversion at this point - it's up to the shader to premultiply or unpremultiply if that is what it wants to do.  In D2D, pretty much all the shaders assume the data is already premultiplied, and they want it to be premultiplied, so they just proceed to do whatever it is they do without any extra format conversions.

> Question: The documentation says that if you load a bitmap, it is automatically converted to a premultiplied format.

Correct.  Operations such as CanvasBitmap.LoadAsync and SaveAsync will always decode and encode data from an image codec into premultiplied format D2D bitmaps.  If you want to load an image file with a different alpha format, you'll have to do that some other way.

> Question: If I'm interpreting what you're saying correctly I could write to a format that Win2D assumes is premultiplied to avoid Win2D's automatic conversion and still use the full value range for all 4 components, then simply lie about it being premultiplied? The consequence would be odd results if I tried to use that texture with Win2D methods that expect premultiplied input, I guess. That would be fine.

Exactly.

> Question: If the CanvasBitmap PixelColor methods convert colors from straight to premultiplied

SetPixelColors and GetPixelColors don't do any alpha conversion - they just copy the bit values directly to or from the bitmap.

**Comment by CMay** [comment]
Thanks for the rundown.  I was already aware of the way some of that works, but this does help to crystallize it for me.

> Slight correction: the texel reads always just return whatever values are stored in that texture.

Yeah, I didn't mean to imply that the hardware does something different there, just that if you're not linking in a shader that modifies the input before your shader gets it, then you'll end up with the  premultiplied values.

> If you want to load an image file with a different alpha format, you'll have to do that some other way.

Thanks.  I could just use a 3rd party image reader and then feed those bytes in, but it may also be an opportunity to experiment with other ways to store my data.

I'm not sure if Win2D's async loading is doing anything clever inside the async CreateResources calls, but I imagine if I create a new async method that creates a CanvasBitmap and streams the bytes in, Win2D will track the CanvasBitmap being newed up and get it copied to the GPU once the async CreateResources does finally return.  I may give this a go sometime next week.

> SetPixelColors and GetPixelColors don't do any alpha conversion - they just copy the bit values directly to or from the bitmap.

Ah, thought I had read it somewhere in the documentation.  That's good to know. :)
