### ISSUE TITLE
Fast way to draw into or copy into BMP565 image

### ISSUE THREAD

**Issue by pleaseking** [Microsoft/Win2D#57]
This is not a proper issue but more like seeking advice: is there any fast way to draw into a BMP565 bitmap buffer (DirectX pixel format is DXGI_FORMAT_B5G6R5_UNORM but it does not seems supported). Any clues or pointers? 
If drawing is not possible, what about at least accelerated copying?

**Comment by clandrew** [comment]
This format restriction, unfortunately, comes from Direct2D, as opposed to Win2D itself. Direct2D imposes restrictions on what formats can be used bitmaps, and this format is not allowed with *any* of its APIs.

If your app is C++, it may be possible to achieve fast copying using Direct3D only. It depends on the scenario.

I'm curious, what type of scenario you are working with requires this format?

**Comment by pleaseking** [comment]
Well we just have a game-like UI engine that works in this format internally (heritage from Windows Mobile and other platforms). We plan to move to RGBA which is half-done and needed anyway, but I was looking for a quick fix to enable at least things like native font rendering.
Yes our app is in C++, so I could give Direct3D a try - any links/pointers on how to do that? Thanks!

**Comment by shawnhar** [comment]
Direct3D resource copy operations don't do format conversion, so the usual approach for such things is to draw into a rendertarget:

1) Bind rendertarget of the desired output format
2) Bind texture of the source format
3) Draw a quad covering the rendertarget, using a pixel shader that samples from the source texture

Win2D provides interop so you can get from a CanvasBitmap to a D3D11 surface for use in this operation, but setting everything up (creating shaders etc.) to draw the quad will be quite a bit of work due to the low level nature of the D3D API.

**Comment by shawnhar** [comment]
I'm closing this issue as we do not plan to make any changes in Win2D as a result of it.  Feel free to reactivate if you have further questions.
