### ISSUE TITLE
Is there a loss of precision in CanvasDrawingSession.Transform ?

### ISSUE THREAD

**Issue by aybe** [Microsoft/Win2D#578]
I have come across an interesting transform problem, where scaling is incorrect when applied through `CanvasDrawingSession.Transform`.

Here are some pictures:

**Applying scaling in `CanvasDrawingSession.Transform` (wrong):**

![2017-11-08 01_53_36-waveform uwp](https://user-images.githubusercontent.com/1537591/32526054-be640c9c-c427-11e7-9675-4f97ac968a33.png)

**Applying scaling in `CanvasGeometry.Transform` (correct):**

![2017-11-08 01_53_54-waveform uwp](https://user-images.githubusercontent.com/1537591/32526055-be7cdc7c-c427-11e7-88b7-04b9cb678959.png)

**A reference image from Wavelab for comparison:**

![2017-11-08 01_53_56-forme - sondag _ - wavelab - forme - sondag wav _ c__users_aybe_music](https://user-images.githubusercontent.com/1537591/32526056-be91d852-c427-11e7-8592-73c88b0cc4b6.png)

And the code, narrowed done to the problem :

```
// peak values range from -1.0f to +1.0f

var builder = new CanvasPathBuilder(sender);

...

var scale = Matrix3x2.CreateScale(1, -1.0f * channelHeight * 0.5f);

var path = CanvasGeometry.CreatePath(builder);
// when applying here, drawing is correct
// path = path.Transform(scale);

s.Transform =
    // when applying here, drawing is not correct
	// scale *
	Matrix3x2.CreateTranslation(0, c * channelHeight + channelHeight * 0.5f)
	;

s.DrawGeometry(path, Vector2.Zero, Colors.DeepSkyBlue);
```

I could be wrong but it seems like there is some precision/trimming/whatever happening somewhere when applying the scaling through `CanvasDrawingSession.Transform`.

Thanks for your help !

**Comment by shawnhar** [comment]
At first glance that looks not so much a precision issue as just a completely different scale.  Are you sure the same transform is being applied in both places?

Another possibility is that, since it looks like you have very high density of lines in your geometry, you may be running up against aliasing issues.  Direct2D is good at antialiasing the edges of complex shapes, but in this case I'm guessing you have a lot of lines moving back and forth by large amounts vertically, but perhaps less than one pixel horizontally?  That's a very difficult case for geometric antialiasing and is liable to run into all kinds of Nyquist limits.  If this is the problem, reducing the horizontal frequency of your data (so that each x step is >= 1 pixel) would help a lot.

**Comment by aybe** [comment]
Sorry, that's my fault actually, I misunderstood how it works ... in my case I wanted to scale the Y values of the path, thinking it'd remain 1 pixel wide.

But what `CanvasDrawingSession.Transform` actually does is scaling the rendering which obviously makes sense !

A quick test that proves I misunderstood the usage of the transform:

Applying transform in `CanvasDrawingSession.Transform` scales the whole thing:
![2017-11-08 23_24_19-app1](https://user-images.githubusercontent.com/1537591/32578047-1aa4f890-c4dc-11e7-8ef9-c40048aa7c80.png)

Applying transform in `CanvasGeometry.Transform`, what I was expecting:
![2017-11-08 23_23_40-app1](https://user-images.githubusercontent.com/1537591/32578046-1a86e990-c4dc-11e7-954e-f3700bb33683.png)

Closing the issue, thank you !
