### ISSUE TITLE
Clear area in RegionsInvalidated

### ISSUE THREAD

**Issue by Petititi** [Microsoft/Win2D#586]
Hi everyone, happy New Year!

I'm wondering if it's possible to deactivate the `clear` preceding every call to `RegionsInvalidated`? Sometime I can't draw the area right now and need to ask again to redraw the region later. Any idea how we can do that?

Thanks!

**Comment by shawnhar** [comment]
You can ask for a region to be redrawn at any time by calling CanvasVirtualControl.Invalidate.

I'm not sure what you mean by deactivating a clear, though?  The RegionsInvalidated event tells you that the control wants to display a part of the image which is not currently available to it.  It's entirely up to you what you draw in response to this event - for instance if you aren't able to draw the correct image yet, you could just clear to transparent or a solid color, or draw a quick placeholder etc.  But the control has to display /something/.  If you completely ignore the RegionsInvalidated event and don't give it anything at all, it will default to whatever the ClearColor is set to.

**Comment by Petititi** [comment]
Hi Shawnhar!
I'm indeed not very clear :-) I indeed use `CanvasVirtualControl.Invalidate(Rect)` to specifically redraw part of the image, but as this mechanism is asynchrone, between this call and the `RegionsInvalidated`, our application needs to "pause" rendering. But unfortunatly, it's too late, the region is already cleared by win2D, so content will disappear.
If Win2D could have a property which let user clear the area before doing the draw itself, this would be very helpfull. This could be for example done when ClearColor is `null`?

**Comment by shawnhar** [comment]
Unfortunately the underlying virtual control mechanism used by Win2D does not provide any way to cancel an invalidation request.  When you tell the control to invalidate a region, it throws away whatever pixel data might have previously been drawn there.  This leaves it in the same state as if a never-before-visible area of the control had just scrolled into view.  Once this happens there is no reasonable way to cancel the invalidate, because the previous data is already gone!  You could choose not to draw anything, but this would result in not displaying anything (i.e. clearing to transparent), rather than displaying the old control contents from before the invalidate.

I guess you could store a copy of the previous image in a rendertarget of your own, and use that to restore the virtual control contents as needed?  But then you're not really using the virtual aspect of the control, eg. would have to manage all your own rendertarget memory and decide how long to hang onto temporaries etc.
