### ISSUE TITLE
Unable to get opacity masks to work ...

### ISSUE THREAD

**Issue by Tom-Cuthill** [Microsoft/Win2D#588]
Despite my best efforts I am not able to get OpacityBrushes working with CanvasDrawingSession.FillGeometry(
	CanvasGeometry geometry,
	Vector2 offset,
	ICanvasBrush brush,
	ICanvasBrush opacityBrush
);

I want to create a transparent buffered edge around some text, and to use the opacityBrush to enforce the buffer on a filled geometry.    Here is stripped back example showing my problem (obviously this is not how you'd render a transparent hole in a circle, but it illustrates my problem).

![image](https://user-images.githubusercontent.com/24502866/35192794-948a53b8-fed3-11e7-85ce-820c7a200f5a.png)

The only factor affecting whether the red bubble is drawn is colour the mask is cleared with.  It doesn't matter what is drawn in the mask, regardless of its opacity.

I'm really stumped with this.  What am I missing?

Cheers,
Tom Cuthill

**Comment by shawnhar** [comment]
Opacity masks are based on color, not alpha.  Black = transparent, while white = fully opaque.  While drawing the opacity mask image, you should use entirely opaque colors, with the greyscale brightness determining how opaque you want the final operation to be once the mask is applied.

**Comment by Tom-Cuthill** [comment]
Hi Shawn,

Changing to opague colours using black and white to control opacity still produces the same results.
![image](https://user-images.githubusercontent.com/24502866/35209159-1640440e-ff87-11e7-9981-e33d02b5bf08.png)

Your suggestion also appears to contradict the doco on the CanvasDrawingSession.FillGeometry page.  Here is what it says:

Transparent portions of the opacity mask brush indicate the areas where the contents of the geometry will be transparent, while opaque portions of the mask indicate where the geometry is visible. **The RGB color of the opacity mask is ignored.**

Either way I don't seem to be able to control the opacity.

Any ideas?

Cheers,
Tom

**Comment by shawnhar** [comment]
> Your suggestion also appears to contradict the doco on the CanvasDrawingSession.FillGeometry page

Gah, my apologies!  I could have sworn I remembered how this works, but apparently not :-)

One problem in this drawing code is that your two brush images are sized 100x100 and not translated, so these brushes will only cover the region (0,0) to (100,100).  Anything outside that will get the clamped border of your images, due to use of CanvasEdgeBehavior.Clamp.

But when you draw the geometry, you are translating it by (400,100).  This means it will be sampling entirely from outside the area covered by the brush.

Try drawing your geometry inside the (0,0) to (100,100) region, or setting a transform on your brushes to move them to the same area that the geometry is being drawn to.

**Comment by Tom-Cuthill** [comment]
That's got it!  I assumed that the translation in position would be applied AFTER the opacity was applied.

All good, thanks kindly for the help!
Tom
