### ISSUE TITLE
Explaining the opacity mask

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/Win2D#61]
In the documentation for the various CanvasDrawingSession.FillGeometry methods that take an opacity mask it may be worth pointing to https://msdn.microsoft.com/en-us/library/windows/desktop/ee329947.aspx and mentioning that "the transparent portions of the mask indicate the areas where the underlying image is hidden, whereas the opaque portions of the mask indicate where the masked object is visible".

**Comment by shawnhar** [comment]
Thanks for the suggestion!

When you were looking for this information, did you find the CanvasActiveLayer documentation (http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasActiveLayer.htm) or were you just looking at the pages for the different overloads of the CreateLayer methods?

At the moment we use CanvasActiveLayer as a central place to document layers (although there could definitely be more detail in there).  This is convenient because it gives us just one place to put that info, rather than having to repeat the same text in many different places, but I worry that people might not actually find it when looking at the page for one of the CreateLayer overloads.

So I'm curious whether you found that page or not?

**Comment by dumbledad** [comment]
No - I did not find that. Stupidly I never thought to look at layers at all! I found 'opacity' in CanvasDrawingSession.FillGeometry, realised I did not know how to specify the mask (I assumed white = on and black = off) so I looked in the source code and then in the Direct2D documentation.

**Comment by shawnhar** [comment]
Aha!  And this is exactly why it's so valuable for us to get this sort of real feedback from customers.  I never even thought of that, but of course you are quite right - the docs for FillGeometry and FillRectangle shoud link to CreateLayer, and vice versa, so that once somebody finds any one of these opacity-related methods, they can easily find the complete set and understand all the available options.

Many thanks for pointing this out!

**Comment by clandrew** [comment]
This has been addressed with the latest release, version 0.0.17.
