### ISSUE TITLE
Linker error when invoking CanvasDevice::Trim method with C++/WinRT

### ISSUE THREAD

**Issue by anup-das** [Microsoft/Win2D#614]
Visual Studio 2017 15.7.3
Windows 10 SDK (10.0.17134.0)
C++/WinRT VSIX version 1.0.180505.2
Win2D NuGet version 1.23.0

I have successfully used Win2D nuget package in my  C++/WinRT app and everything works fine in terms of functionality.  The only problem is when i call CanvasDevice::Trim method I get a linker error. I do NOT use CanvasControl in my XAML page so I need to invoke this method manually. 

error LNK2019: unresolved external symbol "public: void __thiscall winrt::impl::consume_Windows_Graphics_DirectX_Direct3D11_IDirect3DDevice<struct winrt::Microsoft::Graphics::Canvas::ICanvasDevice>::Trim(void)const " (?Trim@?$consume_Windows_Graphics_DirectX_Direct3D11_IDirect3DDevice@UICanvasDevice@Canvas@Graphics@Microsoft@winrt@@@impl@winrt@@QBEXXZ)

**Comment by kennykerr** [comment]
The Trim method is defined by an interface in the Windows.Graphics.DirectX.Direct3D11 namespace. Therefore you must include the corresponding namespace header to compile:

```C++
#include "winrt/Windows.Graphics.DirectX.Direct3D11.h"
```

C++/WinRT  doesn’t automatically include such dependent namespaces since that would end up pulling large numbers of headers that are seldom used and build time would suffer.

**Comment by anup-das** [comment]
That was quick!  Issue resolved. 
I am a software developer with over 20+ years of experience mostly in windows kernel programming. 
So far I am very impressed with C++/WinRT.  I have seen many libraries, run-times, frameworks etc and i am not easily impressed.  Thank you Kenny for this wonderful creation and to MSFT to embrace it.
