### ISSUE TITLE
Where should questions go?

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/Win2D#62]
I just posed a Win2D question on stackoverflow [How to get the width and height of a Win2D CanvasBitmap during CreateResources?](http://stackoverflow.com/q/29702638/575530). There was no Win2D tag. Where would you like programming questions posted (i.e. not bugs, not suggestions, but "How do I do X in Win2D" questions)?

**Comment by damyanp** [comment]
Posting here is fine:  in many cases questions like these indicate that something is missing from the documentation - in this case the CanvasBitmap documentation for GetBounds() should have a link to the Bounds and Size properties on CanvasBitmap.  We'll get that fixed!  Thanks for drawing our attention to it.

**Comment by shawnhar** [comment]
Note that github issues can be labelled, so if you feel bad about opening a "how do I do X" type issue in the same place that bug reports go, you can tag it as a question.

It's totally fine if you don't bother to label your issues, though - I usually add tags to issues that are missing them to keep things straight in my own head, and don't mind doing that at all.

This is a great place to ask questions because it makes sure the Win2D dev team will see them, keeps a clear list of what issues are still active vs. which have been resolved, and the history of all past issues is available for other people to read and learn from in future.

**Comment by clandrew** [comment]
This has been addressed with documentation changes in the latest release, version 0.0.17.
