### ISSUE TITLE
performance Improvement

### ISSUE THREAD

**Issue by usurper12** [Microsoft/Win2D#629]
Hi i have a simple task of drawing a rectangle around a drawing. the drawing is made on a canvas which is hardware accelerated and made using core DirectX APIs . i am trying to create a bounding box around this drawing and applying PAN gestures. i am successfully able to achieve this but i see a lag in WIN2D rendered rectangle when translate is performed. the drawing is slightly faster than win2d rect. i am a newbie here can i some how improve performce. 
i am adding gestures to the View and as soon as windows issues a gesture i apply the same transform to transformView and canvas(on which  drawing is made), the end result is fine but it feels like rectangle drawn using Win2D is "following" the canvas drawing.
can i do any performance improvements here? i dont think i can use CanvasCachedGeometry here since Rectangle will be translated/rotated and scaled. 

    public sealed partial class TransformView : UserControl
    {
        private Rect rect;
        private Rect rect_new;
        CanvasSwapChain swapChain;
        CanvasDevice device;
        CanvasDrawingSession ds;
        public TransformView()
        {
            this.InitializeComponent();
            device = new CanvasDevice();
            swapChain = new CanvasSwapChain(device, (float)Window.Current.Bounds.Width, (float)Window.Current.Bounds.Height, 96);
            //canvasSwapChainPanel is added in XAML
            canvasSwapChainPanel.SwapChain = swapChain;
        }
        
        public void SetRect(Rect Rect)
        {
            rect = Rect;
            rect_new = rect;
            Invalidate();
        }

        public void Invalidate()
        {
            using (ds = canvasSwapChainPanel.SwapChain.CreateDrawingSession(Colors.Transparent))
            {
                ds.Antialiasing = CanvasAntialiasing.Aliased;
                ds.DrawRectangle(rect_new, Colors.Blue);
            }
            ds.Dispose();
            canvasSwapChainPanel.SwapChain.Present();
        }

        public void SetTransform(Matrix3x2 trans)
        {
            rect_new.X = trans.M11 * rect.X + trans.M21 * rect.Y + trans.M31;
            rect_new.Y = trans.M12 * rect.X + trans.M22 * rect.Y + trans.M32;

            Invalidate();
        }
      }
    }

**Comment by shawnhar** [comment]
You are never going to be able to make these things update exactly together, because there is no synchronization between updates to the XAML visual tree and the Win2D swapchain.   Actually, one of the main reasons for using a swapchain is to avoid that kind of synchronization, so that you can have eg. a game animating smoothly at different rate from XAML UI rendering.

You may find a regular CanvasControl does better, as that renders at the same time and on the same thread as XAML UI.   Or if I misunderstood and the thing you are trying to match Win2D with is not XAML UI, you should move your rectangle drawing to happen in the same place/time as however that is being drawn.

**Comment by usurper12** [comment]
thanks Shawn, i was able to resolve my issue by drawing at the same time. thanks again, much appreciated !!.
