### ISSUE TITLE
How to draw transparant ink

### ISSUE THREAD

**Issue by ssrakesh** [Microsoft/Win2D#632]
we currently use DrawAsHighlighter, but the effect is not similar to WPF.
for example , If I draw a red line (using DrawInk) and on top of that a yellow highlighter is drawn then yellow should be transparent on the intersection with red line. But here there is no transparency.
I also tried with setting the alpha channel of the color, But there is no visual difference.
How to achieve this in win2d?

**Comment by shawnhar** [comment]
Please describe more about how and where you are drawing the highlighter ink.  Onto what kind of surface, and over what background?

Usually problems of this nature are due to people drawing highlighter ink onto its own surface, and then relying on XAML composition to blend the surface containing ink data over the top of some other background.  That does not work because highlighter ink uses a min blend mode, not the source-over blend used by XAML layer composition.  So you have to have both background and highlighter ink drawn at the same time into the same surface - they can't be drawn separately and then composed later.

**Comment by shawnhar** [comment]
Closing old issue due to lack of followup.
