### ISSUE TITLE
Canvas Brush and Resource Creator.

### ISSUE THREAD

**Issue by royben** [Microsoft/Win2D#634]
Hi,

Why is it necessary to provide a resource creator when instantiating a new canvas brush?
There are situations where I need to create a brush in a view model and don't have access to the resource creator..

**Comment by clandrew** [comment]
Because Win2D is a GPU-accelerated API, most resources can't be global- they are tied to a GPU device and this is reflected in the API. Brushes are one such example; the behavior of a brush is affected by which GPU device it's attached to.

Is there a reason you can't use [CanvasDevice.GetSharedDevice](https://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasDevice_GetSharedDevice.htm)?

**Comment by royben** [comment]
Basically I am rendering my content to a CanvasRenderTarget (offscreen). If i can define the brush using shared device and use it within my drawing session that will be great. I will try. Thanks!

**Comment by clandrew** [comment]
No problem.
If you're creating the brush from within a drawing session, you can also use the drawing session itself as a resource creator.
