### ISSUE TITLE
Wrong display for GridView/ListView items containing CanvasControl.

### ISSUE THREAD

**Issue by jeromebjerome** [microsoft/Win2D#699]
05/14/19
Hello,
Please, see attached material:
1-Complete scenario description
2-Complete (small) UWP Win10 C++ project to reproduce the issue.
Thanks/
jerome.
[Hello.docx](https://github.com/microsoft/Win2D/files/3176657/Hello.docx)
[GridBug.zip](https://github.com/microsoft/Win2D/files/3176659/GridBug.zip)

**Comment by shawnhar** [comment]
This is due to a bug in your custom control.  The matrix property setter on your grid control does not invalidate the CanvasControl, so Win2D does not know to redraw when that property value changes.  This will happen during scrolling whenever the XAML grid reuses a child list item instance with a different data binding.

**Comment by jeromebjerome** [comment]
Did not know that.
This is great; It works perfectly now.
Thanks for your help.
