### ISSUE TITLE
any point in caching when using win2d?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#702]
Hi guys,

I will soon start to port my app to win2d (using xaml islands).
In my app, I do a lot of animations, and wherever possible, I use caching. The simplest example is if I need to crop a bitmap, then zoom it, I cache the cropped bitmap, and then apply a scaling to it.

My question is - do I need to try to do the same when using win2d, or should I not care?
I've looked around for tips on optimizing win2d performance, but there's almost nothing.

**What things are worth caching when using win2d?**

**Comment by shawnhar** [comment]
This is very much an "it depends" situation.  If something is expensive to draw, then caching that result can be a big performance win.  But if it was cheap to draw, caching will just waste memory and potentially even slow things down because now you are populating the cache and then rendering cached content to the final location, vs. just drawing directly to that final location.

Same thing applies whether using Win2D or not.  For instance with your simplest example of caching a cropped bitmap, have you profiled that to see if it's actually a performance improvement?  Cropping and then scaling a bitmap is a trivially cheap GPU operation, so I wonder if you're actually getting any benefit from the cache there.

**Comment by jtorjo** [comment]
Hi Shawn,

Sorry for the late reply.
That was probably a bad example :) My app draws a lot of images, masks, shapes, text (some of them having shaders) and animating them all at once. Certain animations (rotation + movement + shader  arguments change) are insanely time consuming at this time (using WPF), 

What I sort of wanted to know is , when porting the code, just to simply re-draw everything on each OnDraw() call, or plan for caching from the get-go.


Best,
John

**Comment by shawnhar** [comment]
Afraid this is still very much a try it and see situation, as the value of caching completely depends on the details of what you are drawing and what its update patterns are.

Note that since Win2D is an immediate mode API, caching at the XAML level may not be particularly useful.  You can also just control your Win2D drawing logic to not bother redrawing except when you have an important change to be made.

**Comment by jtorjo** [comment]
Got it thanks, I will just adjust as I go.
