### ISSUE TITLE
Customized drawing (on-demand), avoiding control's handlers.

### ISSUE THREAD

**Issue by rauliordache** [microsoft/Win2D#706]
Hello everyone,

[INTRO]
Using Win2D in order to draw a "real-time" representation of a parameter received from a device (a plethysmogram). So, we are listening (subscribing) for an event (let's say ParamUpdate) which is raised when we are receiving a new value (where "new" could be also an unchanged value - but this was done via modifing the OnPropertyChanged behavior).

The manufacturer says that we are receiving 250 packets/sec, which is an hypothetical 4ms for each packet, if distributed equally. But I don't want to rely on this. (a.k.a TimeSpanning of (0,0,0,4) in a CanvasAnimatedControl approach).

Having a real printing-on-screen speed of 25mm/sec (1mm = 3.77 pixels), on an 1080p width means 2900 "lines" (or points attached to a Polyline) - the main reason of moving my drawing logic from UWP Canvases to Win2D (lagging after rendering 600-700 pixels/around half of the screen's width). Also, didn't want to "solve" the problem in a different manier (that could be easier).
 
[QUESTIONS]
Ok, here I will describe some scenarios:

1. Using CanvasControl:
We need to subscribe to Draw event, which clears the content of the control before every draw. This is unacceptable, since we need to draw a real-time "line".

So a strategy like
---> ParamUpdate ----> <create new coordinates> && DrawLine() -----> CanvasControl.Invalidate() ----> Draw event: DrawingSession... ---> ParamUpdate ----> ..... is not suitable.
Saving the "line"/"path"/a geometry it's also costly and unnecessary.

2. Using CanvasAnimatedControl:
- we could set a timespan of 4ms, and then Update handler will update the new coordinate to be drawn. But, as I said in the beginning, I want to avoid this - It's not "ethically correct" to suppose that we are receiving EACH packet after 4ms (the manufacturer just says 250packets/sec) - moreover, I don't want to rely on this!
- saving the new parameter in an SVG Document it's also contraproductive: We are drawing N points, and before the next raise of Draw we are deleting everything just in order to add a new Point in the Polyline?! We cannot inhibit the ClearColor() call before each Draw...

So, I want to rely ONLY on the ParamUpdate event handler:

3. Using the CanvasControl, using a custom DrawingSession(not from Draw's event args) which will NOT be disposed/cleared (maybe only after reaching the Canvas' width), and forcing a Flush() after each new ParamUpdate

I have tried something like this:

CanvasCommandList ccl;
CanvasAnimatedControl CanvasContainer;
//...//
CanvasContainer.CreateResources += (sender, args) =>
{
ccl = new CanvasCommandList(sender);              
};

private void OnParamUpdateHandler(object sender, EventArgs e)
{
// The logic of param modding //
	using (var clds = ccl.CreateDrawingSession())
	{	
                clds.Units = CanvasUnits.Pixels;
                clds.DrawLine(new System.Numerics.Vector2(oldX, oldY), new System.Numerics.Vector2(X, Y), Colors.GreenYellow);
                clds.Flush();
	}
}

But didn't worked. 

All in all, I need something "more customizable" like:
- drawing without clearing the content (not a gaming FPS manier) and without a save-and-load approach (for example caching a geometry, saving as SVG doc, etc.) 
- manually clearing the content (for example, calling ClearColor() on CanvasControl only when the "line" is a the beginning)
- a "continuously" DrawingSession. 

Any ideas?
The last solution seems to be the most appropriate, but probably I am missing something...

Thanks!

**Comment by damyanp** [comment]
At first glance this is how I'd recommend approaching this, but there may be some details of your setup I'm missing.  It's worth noting that the monitor's refresh rate is more likely to be around 16ms, so unless you are using some specialized hardware you're unlikely to get to a point where the update exactly matches your data source in real-time (4ms is about 250hz).  Is latency important to you? For example, does it matter if it takes 32ms for a data point to actually appear on the screen? For now I'm going to assume not.

Basic idea:
* use a CanvasAnimatedControl with IsPaused=true
* store a list of data points.  You'll need to protect these with a lock since you'll be adding entries to it from one thread and reading from it from another.
* in OnParamUpdateHandler, append to this list and call "Invalidate" on the CanvasAnimatedControl
* in CanvasAnimatedControl's draw handler redraw the entire list of points for each draw.

Win2D will coalesce multiple Invalidates if they happen before the Draw is ready.  I'd expect this to get to a steady state where your update handler calls Invalidate() approximately 4 times for each Draw.

I would be surprised if a setup like this is unable to keep up with the data.  Redrawing a multi-point line in Win2D should be much faster than updating one using XAML/UWP, so I would recommend at this point trying it and measuring. If this is still not fast enough the next thing to consider would be to use a CanvasRenderTarget as something that can persist between draws, but I don't think that this should be necessary in this case.

**Comment by rauliordache** [comment]
Dear Damyan,

Thank you for your fast answer. I will take into account your solution!

Latency is very important for me, because we are taking about a Medical program, thus, a real-time ("as much as possible") monitor. After hours of running, there (could) appear a delay of 1-2s, which is unacceptable. So, we need to avoid this.

I know the meaning of "real-time" when we are talking about computing. "Real-time" means the maximum latency allowed.

Using the debugger, I can see that I receive a package every 5ms-10ms. 

I will try your solution first. Can you tell me if moving the computing to C++/WinRT, and using the API in my UWP C# App could be faster than Win2D (in my very particular case of needing a real-time software)?

**Comment by damyanp** [comment]
Are you using specialized hardware to display the data?  Or is this displayed on a standard computer monitor / laptop screen?

Is the issue with it becoming very slow after running for lots of hours due to the size of the data?  I was wondering what the design would be here - presumably you'll eventually run out of space on the screen?  What should happen then?

You'll want to modify your Draw function to only try and draw points that are on the screen to alleviate this.

My expectation is that you can do all of this in C#.  If you find you are having performance problems then I'd recommend using a profiling tool to determine where the bottlenecks are and see if there are any algorithmic optimizations I can make.  These are more likely to provide big wins than porting the same algorithm to C++.

**Comment by rauliordache** [comment]
1. No specialized hw to display data. Standard monitor/laptop and tablets
2. Yes, it is an issue if becomes slowly after hours of running. I just want to render the actual data on screen - when reaching the Canvas' width, again, from the beginning. So I do not need to save the data (in this manner). I will store the data in Cloud (but this is another discussion). The canvas will show only the actual data (~ 11 seconds of recording on a 1080p width screen res, then, again).

For me, it's enough to draw a "line" on the screen (without storing any points saved). At the end of the screen's width, I will do a Clear() and start again.


This is why I asked:
- can I force drawing a line on the screen without subscring to Draw event? (just using a custom CanvasDrawingSession) ? 
receiving the new param ----> getting the new coordonitate ----> CanvasDrawingSession.DrawLine(old,new,Color) ---> CanvasDrawingSession.Flush() - to force drawing on device ?

**Comment by damyanp** [comment]
In that case I think the approach I suggested will work for you.

You have a couple of options when you've got enough points in your list:

* empty the list and start a new one (this would like clearing)
* delete entries from the beginning of the list to "make room" for the ones at the end (this will give you a scrolling line)

I'd expect you'd be able to keep up with this, but there are various things that could be done to improve performance if this is an issue.

Also, I'd note that having a separate data store from the control means you can resize the control without losing all the data.

**Comment by rauliordache** [comment]
Wonderful idea !

> In that case I think the approach I suggested will work for you.
>     * delete entries from the beginning of the list to "make room" for the ones at the end (this will give you a scrolling line)
>

I will try this. Tomorrow I will compute. 
Thanks! I will come back as soon as possible.


Thanks!

**Comment by damyanp** [comment]
No worries, I hope this work for you.

You might want to have a look at the "SpriteBatch Performance" and "Animated Control" examples in Win2D Example Gallery for examples of line graphs.
