### ISSUE TITLE
XAML Control names

### ISSUE THREAD

**Issue by suprak** [Microsoft/Win2D#71]
Why are the control names suffixed with "Control"? Seems redundant.
The naming doesn't follow the rest of the XAML control names.

I would expect the name to be 'Win2DCanvas' or (since maybe Win2D is redundant given the required namespace), simply 'Canvas'.

**Comment by clandrew** [comment]
That's a very fair point. Canvas is a prefix, attached to all Win2D types. Fun fact, the prefix wasn't always Canvas- you can see this in our public revision history here: 7a77d4db389c07a403378dbc40efc3e1cfa1e1b8.

It would have been nice to avoid the prefix entirely, but this (or some name modification) was necessary to deliver this API. Win2D can't have types (like XAML 'ImageBrush') that have the exact same name as certain other types built into the platform, even if they're in different namespaces. We chose Canvas because it reflects the fact that this is for 2D drawing, and using it as a prefix would group the types together in Intellisense and improve discoverability. 

Given that Canvas is a prefix, it follows that the controls would have some unique identifier of their own. The 'static' one, CanvasControl, came first- and CanvasAnimatedControl was written second.
