### ISSUE TITLE
No Key event

### ISSUE THREAD

**Issue by Odonno** [Microsoft/Win2D#73]
Currently, I am working on a Windows 10 Universal project.

In many games, we need to manage touch and key events. Here, I use PointerPressed/Released to manage touch events but KeyDown/KeyUp does not work within the CanvasControl...

I use Visual Studio 2015 RC and Win2D 0.0.17.

Hope you can fix it.

**Comment by clandrew** [comment]
CanvasControl should not be doing anything in particular to inhibit keyboard input, but in XAML keyboard events are only raised if the control has focus, and there may be something preventing that from happening. What happens if you set TabStop=true to the CanvasControl when the page is loaded? Or, if you move further up the tree, and set the keyboard events on Window.Current.CoreWindow?

**Comment by Odonno** [comment]
I tried to put the KeyDown event on the Grid root tree but it does exactly the same, thinking that CanvasControl got focus and it failed to support keyboard events.

Using Window.Current.CoreWindow fixed the bug.

Thank you !

**Comment by SneWs** [comment]
The way to solve this correctly currently is to tap into CoreWindow.KeyUp|KeyDown. 

You get the window via Window.Current.CoreWindow.
