### ISSUE TITLE
"Class not registered" exception on CanvasDevice when using Win2D with Console App

### ISSUE THREAD

**Issue by datvm** [microsoft/Win2D#735]
I need `Windows.Media.Editing` APIs (for video composition) on my Console script so I used `Microsoft.Windows.SDK.Contracts` package and so far it was good. The problem was, when I try creating MediaClip from Image file, it stops working (no exception, it just run indefinitely at `RenderToFileAsync`.

Therefore I try another approach with Win2D, however, anytime I try using `CanvasDevice` (for example `var canvas = new CanvasDevice()`), I meet this exception:

> COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

> Requested Windows Runtime type 'Microsoft.Graphics.Canvas.CanvasDevice' is not registered.

![image](https://user-images.githubusercontent.com/6388546/69953262-75104900-152b-11ea-9414-c9287a9ba920.png)

Anyway I can use/create a Surface and use Win2D on it from a Console app (.NET Framework 4.7.2)?

Update: I tried moving the project to .NET Core 3.0, not working still, will try with a WPF project on .NET Core 3.0

**Comment by lhak** [comment]
I do not know if win2d works in a console app. However, in order to use any winrt component (like win2d), it has to be registered for the application. This will happen automatically if you package the app into a msix package. Alternatively, recent Windows 10 versions allow to register the component in the app.manifest file. I think the following article describes this well:

https://blogs.windows.com/windowsdeveloper/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/
