### ISSUE TITLE
using GPU

### ISSUE THREAD

**Issue by brunotrevisan** [microsoft/Win2D#743]
Are you trying to include GPU 3D acceleration in my program, but it always seems to run on the CPU, or GPU Support Win2d?

My Code: 

CanvasBitmap^ BitmapMap::CreateMappableBitmap(CanvasDrawingSession^ drawingSession, unsigned int width, unsigned int height)
{
	ComPtr<ID3D11Device> d3dDevice(D3D11Interop::GetD3D11DevicePtr(drawingSession));

	D3D11_TEXTURE2D_DESC texDesc = { 0 };
	texDesc.Width = width;
	texDesc.Height = height;
	texDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
	texDesc.MipLevels = 1;
	texDesc.ArraySize = 1;
	texDesc.SampleDesc.Count = 1;
	texDesc.SampleDesc.Quality = 0;
	texDesc.Usage = D3D11_USAGE_DYNAMIC;
	texDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
	texDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
	texDesc.MiscFlags = 0;

	ComPtr<ID3D11Texture2D> d3dTexture;
	__abi_ThrowIfFailed(d3dDevice->CreateTexture2D(&texDesc, nullptr, d3dTexture.GetAddressOf()));

	ComPtr<IDXGISurface> d3dSurface;
	__abi_ThrowIfFailed(d3dTexture.As(&d3dSurface));

	auto winRTSurface = CreateDirect3DSurface(d3dSurface.Get());
	auto output = CanvasBitmap::CreateFromDirect3D11Surface(drawingSession, winRTSurface,90);
	return output;
}

in CreateFromDirect3D11Surface is running by CPU and not by GPU

**Comment by shawnhar** [comment]
Sorry, I don't understand this question.  Win2D is a helper layer on top of Direct2D, which in turn is a layer on top of Direct3D.   Direct3D rendering almost always runs on the GPU, except in the specific case where you have selected the WARP software rasterizer.

**Comment by brunotrevisan** [comment]
and how would I do to create a CanvasBitmap rendered by GPU, I'm trying for days but without success I don't know where I'm wrong you said but I didn't understand could point me the error? sorry my english i'm brazilian

**Comment by shawnhar** [comment]
See https://microsoft.github.io/Win2D/html/Offscreen.htm

**Comment by brunotrevisan** [comment]
Mas assim eu nao cria um Map Bitmap e preciso dele

**Comment by brunotrevisan** [comment]
![image](https://user-images.githubusercontent.com/27830830/72224438-67ea6f00-3559-11ea-9eeb-d1cb22572e4f.png)


Did not work
My routine

//Create RenderTarget;
 CanvasRenderTarget offscreen = new CanvasRenderTarget(drawingSession.Device, size, size, 96);
  RenderTarget = offscreen;

//Draw Picture Frame
  RenderTarget.SetPixelBytes(data.ToArray(),0,0,(int)width, (int)height);


Do not use the gpu the resources go all to CPU, any solution?

**Comment by shawnhar** [comment]
You are not doing any GPU rendering work in the code you show here.  SetPixelBytes just copies an array of already-rendered pixel values from a CPU data structure into a GPU object.  This is just moving around existing data, rather than using the GPU to render new data (eg. via the various methods of CanvasDrawingSession).

**Comment by brunotrevisan** [comment]
The images come from an external dll that provides me only:
ReadOnlySpan <byte> data
uint width
uint height
uint pitch

So I created a canvasbitmap with these bytes to draw on the canvasAnimatedControl
CanvasDrawingSession.DrawImage Method (ICanvasImage)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Vector2)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Single, Single)
CanvasDrawingSession.DrawImage Method (CanvasBitmap, Rect)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Vector2, Rect)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Single, Single, Rect)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Rect, Rect)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Vector2, Rect, Single)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Single, Single, Rect, Single)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Rect, Rect, Single)
CanvasDrawingSession.DrawImage Method (ICanvasImage, Vector2, Rect, Single, CanvasImageInterpolation)

All DrawImage needs a CanvasBitmap and the canvas bitmap only has this SetPixelBytes function to create an image by bytes. Where am I wrong? I already read and reread the entire documentation of the link you provided me and this was the only way to work with bytes images

**Comment by brunotrevisan** [comment]
Sorry my english

**Comment by shawnhar** [comment]
I think you have an unrealistic expectation of what GPUs are good for.  The purpose of a GPU is to efficiently evaluate complex mathematics in order to create a new image, computing lighting, shadows, etc.  But if I understand right in your case, you already have an image that has been created via some other means, and are just trying to display it.  You can certainly do that using the Win2D API, but the work won't mostly be using the GPU because this is not the kind of work that GPUs are good at.

**Comment by brunotrevisan** [comment]
ok, and I need to keep 60fps in rendinization so there are several exchanges I tried with CanvasAnimatedControl and CanvasSwapPanel but both are slow to try using Angle + SwapPanel Thanks for the preview

**Comment by brunotrevisan** [comment]
is there a possibility to force hardware acceleration?

**Comment by shawnhar** [comment]
Win2D automatically uses hardware acceleration for drawing operations, but it sounds to me like your problem is how to efficiently transfer existing data, rather than how to draw something new.  Data transfer from a CPU array is fundamentally not a GPU hardware operation.   If copying the data is your performance bottleneck, I would back up and suggest investigating whether there is some way you can arrange for the incoming data to be provided already in GPU texture format.  If that's not possible, there's fundamentally no way around having to do an expensive data copy.

**Comment by brunotrevisan** [comment]
Na verdade ele me retorna como Intprt um ponteiro da bitmap, so que no Win2d existe uma maineira de criar esse bitmap com um Intprt? pq nesse momento estou fazendo dessa maneira   **payload = new ReadOnlySpan<byte>(data.ToPointer(), size);** 

então nao é possivel que minha dll externa que esteja sobrecarregando a CPU alguma coisa tem de errado e nao é a dll externa,  o Win2d existe uma API para criar CanvasBimap atraves de um Intptr?
