### ISSUE TITLE
CanvasDrawingSession.EffectTileSize throws exception

### ISSUE THREAD

**Issue by jtorjo** [microsoft/Win2D#745]
Settting CanvasDrawingSession.EffectTileSize too big will throw an exception. 
That is totally fine. The problem is that it gets thrown in who knows what thread, and basically crashes my app.

(correction - after looking, this happens on the UI thread, but it still crashes my app)

![image](https://user-images.githubusercontent.com/13891601/72001922-18e9c480-324f-11ea-91ef-9a3efac5366f.png)

Is there a way to know the max size I can set here?

**Comment by shawnhar** [comment]
You should be able to see exactly where this exception is thrown, and catch it if need be, if you turn on first-chance exception handling.  Otherwise you'll always just end up in this unhandled exception filter that's installed by the XAML app framework.

I'm curious why you are trying to change the tile size?  This property is included in Win2D mostly just for completeness, since it's part of the underlying D2D API as well.  I don't actually know any good reasons to want to change it, or for sure what the limit is :-)   My guess would be that making this smaller than the default might makes sense to reduce intermediate memory usage (at the cost of longer rendering time) but increasing it beyond the default is probably never a good idea.

**Comment by jtorjo** [comment]
I'll look into first-chance exception handling - clearly I'd like to catch it if possible.

As to changing the tile size -> I did mention a while ago that I have some pixel shaders that need the whole surface of the painted image (like, zoom blur)

Having said that, I'd definitely be happy to not use this, had there been a zoom blur included in the effects from D2D.

**Comment by shawnhar** [comment]
> I have some pixel shaders that need the whole surface of the painted image

That's not going to work for processing large images with the D2D effects system.  You'll need to find a way to rework these shaders so they can handle tiled processing.

**Comment by jtorjo** [comment]
> That's not going to work for processing large images with the D2D effects system. You'll need to find a way to rework these shaders so they can handle tiled processing.

Agreed. That's why i resize them beforehand, so that they match the EffectTileSize. I've somehow guessed that the max size of EffectTileSize seems to be the screen size divided by the monitor's dpi scaling

**Comment by shawnhar** [comment]
It's unlikely this would depend on the monitor resolution.  Wild guess - is the limit 2048?

**Comment by jtorjo** [comment]
Doesn't seem to be 2048. In my tests looks more like 1920 x 1080. I will test again
