### ISSUE TITLE
CompositeEffect upon DirectXPixelFormat.R32G32BA32Float fails every second attempt

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/Win2D#75]
I have one red surface, one blue surface, and I do a `CompositeEffect {Mode=Add}` on them. I repeat this test four times on the red+blue surfaces.

If the red and blue surfaces are in the default `DirectXPixelFormat.B8G8R8A8UIntNormalized`, then everything works fine as expected: I get the answer "magenta" four times.

But if the red and blue surfaces are in `DirectXPixelFormat.R32G32B32A32Float`, then the first time around gives magenta, the second time gives black, the third time gives magenta, and the fourth time gives black. This is bizarre!

Here's a minimal self-contained repro. Create a File>New>C#>UWP blank app, and use the following code for MainPage.xaml. Examine the "output" window of System.Diagnostics.Debug.WriteLine. I did the test, and got my crazy behavior, running on a SurfacePro1 with Win10 build 10074.

```cs
public sealed partial class MainPage : Page
{
	CanvasControl canvas1;

	public MainPage()
	{
		this.InitializeComponent();
		this.Content = canvas1 = new CanvasControl();
		canvas1.CreateResources += Canvas1_CreateResources;
	}

	private void Canvas1_CreateResources(CanvasControl sender, CanvasCreateResourcesEventArgs args)
	{
		var red_b8g8r8a8 = new byte[] { 0, 0, 51, 255 };
		var blue_b8g8r8a8 = new byte[] { 26, 0, 0, 255 };
		Test(DirectXPixelFormat.B8G8R8A8UIntNormalized, red_b8g8r8a8, blue_b8g8r8a8);
		// Result: magenta(alpha=1), magenta(alpha=1), magenta(alpha=1), magenta(alpha=1)
		// as expected

		var red_r32g32b32a32 = new List<byte>();
		red_r32g32b32a32.AddRange(BitConverter.GetBytes(0.8f));
		red_r32g32b32a32.AddRange(BitConverter.GetBytes(0f));
		red_r32g32b32a32.AddRange(BitConverter.GetBytes(0f));
		red_r32g32b32a32.AddRange(BitConverter.GetBytes(1f));
		var blue_r32g32b32a32 = new List<byte>();
		blue_r32g32b32a32.AddRange(BitConverter.GetBytes(0f));
		blue_r32g32b32a32.AddRange(BitConverter.GetBytes(0f));
		blue_r32g32b32a32.AddRange(BitConverter.GetBytes(0.3f));
		blue_r32g32b32a32.AddRange(BitConverter.GetBytes(1f));
		Test(DirectXPixelFormat.R32G32B32A32Float, red_r32g32b32a32.ToArray(), blue_r32g32b32a32.ToArray());
		// Result: magenta(alpha=2), black(alpha=0), magenta(alpha=2), black(alpha=0)
		// Expected: magenta, magenta, magenta, magenta

		Debug.WriteLine("done");
	}

	void Test(DirectXPixelFormat format, byte[] col1, byte[] col2)
	{
		var lhs = new CanvasRenderTarget(canvas1, 1, 1, 96.0f, format, CanvasAlphaMode.Ignore);
		var rhs = new CanvasRenderTarget(canvas1, 1, 1, 96.0f, format, CanvasAlphaMode.Ignore);
		var res = new CanvasRenderTarget(canvas1, 1, 1, 96.0f, DirectXPixelFormat.R32G32B32A32Float, CanvasAlphaMode.Ignore);
		var add = new CompositeEffect { Mode = CanvasComposite.Add };
		add.Sources.Add(lhs); add.Sources.Add(rhs);

		for (int i = 0; i < 4; i++)
		{
			lhs.SetPixelBytes(col1);
			rhs.SetPixelBytes(col2);
			using (var ds = res.CreateDrawingSession()) ds.DrawImage(add);
			var buf = res.GetPixelBytes();
			Debug.WriteLine($"R={BitConverter.ToSingle(buf, 0):0.0} G={BitConverter.ToSingle(buf, 4):0.0} B={BitConverter.ToSingle(buf, 8):0.0} A={BitConverter.ToSingle(buf, 12):0.0}");
		}
	}
}
```

**Comment by clandrew** [comment]
I reproed this issue, and appreciate having such a minimal repro. What seems to be going on here is that we're not clearing the render target before drawing, inside the 'var ds = res.CreateDrawingSession()'. 

CanvasRenderTarget will have the previous drawing session's content, or- for the first drawing session- undefined content, until it is cleared. Because of this, you'll get a different result frame-over-frame. For low-color, this may not matter. We can 'get lucky' with an already-cleared render target from the start, and drawing overtop it causes no change. For high-color, drawing overtop of the non-cleared content causes unexpected accumulative behavior with the default blend mode (source over).

**Comment by shawnhar** [comment]
A newly created rendertarget will be cleared to zeros, but subsequent draws to the same surface occur over the top of whatever values are already in it.

Working through the details to explain exactly why you're getting these values out the end:

* Additive composite of (0.8, 0, 0, 1) and (0, 0, 0.3, 1) produces (0.8, 0, 0.3, 2)
* When using 8 bit per channel format, the output color is clamped to 0-1 range, but when using 32 bit floats the alpha value retains its full range and = 2
* Win2D defaults to source-over blending: src + dest * (1 - src.alpha)
* First time through, dest is 0 so this just outputs src
* Next time around, src.alpha = 2, so 1 - src.alpha = -1, so this collapses to src - dest, and because dest contains a copy of src from the previous pass, that = 0

Options to fix it:

* Clear the rendertarget before drawing
* Set ds.Blend = CanvasBlend.Copy, to disable the (in this case unwanted) src-over blend operation

**Comment by shawnhar** [comment]
In case this gets lost in the details: the behavior you are seeing is actually by design.  It's a perhaps surprising result of applying blending operations when the incoming color values have alpha > 1.

**Comment by ljw1004** [comment]
I see. What I got from your explanation is that ds.DrawImage does a source-over draw of the result of the effect onto the drawing surface.

(Previously I hadn't understood this: I thought that ds.DrawImage always did a Copy).

I confirm that your suggested fix of "ds.Blend = CanvasCopy.Blend" makes the code work fine as expected. Thanks folks!

**Comment by 13thsymphony** [comment]
Lucian, do you mind sharing some details about what scenario you’re doing that needs FP render target support? This is an area of the API that is not frequency exercised and we’d love to understand how it is being used.

**Comment by ljw1004** [comment]
I'm a complete beginner, learning Win2d and GPU programming from scratch. I set myself the exercise of writing a GPU-accelerated Mandelbrot set viewer:
https://github.com/ljw1004/blog/tree/master/Win2d


(thanks to this thread, you can see the first glimmer of it working! you run it, and press the STEP button at the top left, and after 10 or so iterations you start to see the Mandelbrot set take shape...)

**Comment by shawnhar** [comment]
What a cool project!   That's really pushing image effects to their limit  :-)
