### ISSUE TITLE
How to retrieve an image of the drawn region in a CanvasVirtualControl?

### ISSUE THREAD

**Issue by daljit97** [microsoft/Win2D#766]
I am using `CanvasVirtualControl` for a large canvas in my application. Now I would like my app to able to create thumbnails of certain regions of the control and paint them using a `CanvasRenderTarget`. How can I achieve this? Currently I don't see anyway to do this.

**Comment by shawnhar** [comment]
Virtual controls are only useful for displaying to the screen.  There's no way to read back their contents because those contents aren't actually stored anywhere (hence the virtual nature of the control) but are only generated in the moment as needed by display scrolling.

Instead, you'll need to repeat your drawing code (reusing the same functions that draw to your virtual control whenever a new region is requested) to draw whatever regions you need directly into a rendertarget.

**Comment by daljit97** [comment]
@shawnhar but is there a way to retrieve what has already been drawn in memory?

**Comment by shawnhar** [comment]
No, because it's not necessarily actually stored anywhere in memory.  You need to draw again, directly into a rendertarget.
