### ISSUE TITLE
Can I raise the CreateResources event in my code?

### ISSUE THREAD

**Issue by t-sch** [Microsoft/Win2D#78]
Hi,
I'm having a scenarion where the resources can't be created on start of the app (because the user first has to select a file). I would like to trigger the CreateResources event after the user has selected a file.
Can this be done?
Cheers,
Thomas

**Comment by shawnhar** [comment]
You cannot manually trigger the CreateResources event, but you can load content in other places as needed.

This [blog post](http://blogs.msdn.com/b/win2d/archive/2015/01/29/loading-win2d-resources-from-outside-the-createresources-event.aspx) describes some of the nuances of how to handle things like lost device while doing so.

**Comment by t-sch** [comment]
Thanks for the very quick reply.
Do I understand it right that that is critical mostly for long-taking jobs like loading bitmaps?
I have to create some handfuls of brushes and did that in Draw before I was aware of CreateResources.

**Comment by shawnhar** [comment]
Using CreateResources has a couple of advantages:

1. It makes sure the resources are created just once and then reused, rather than a new copy being created during every Draw
2. It makes sure the resources get recreated if the GPU device gets reset

Creating resources inside every Draw is fine as long as they aren't too expensive.  It's more efficient to create them just once and reuse, but that may not matter if you're already getting good-enough perf.

If you make new temporary resources every time, it's a good idea to put this in a "using" statement to make sure they get cleaned up properly at the end of the operation that uses them.

Also beware of a pattern where you create resources inside the Draw handler, but then store them in a field and have subsequent Draw operations reuse that same resource if it has already been created. This can seem like a good idea, but it won't know to recreate the resource if the GPU is reset.  If you use this approach, you should also hook CreateResources and have it null out any fields that cache demand-created resources.
