### ISSUE TITLE
Question: CanvasVirtualControl usage

### ISSUE THREAD

**Issue by benstevens48** [microsoft/Win2D#784]
Sorry for asking a question, but I can't find the answer in the docs. I have a question about when using a CanvasVirtualControl rather than a CanvasControl is a good idea. All the docs (including DirectX) talk about this control (or the underlying VirtualSurfaceImageSource) being good to use if it covers a very large area. However, I have a different use case which it doesn't mention. I have a long scrolling panel in which I intend to put lots of CanvasVirtualControls. If each one retains the memory required to draw its surface, then too much memory will be used. However, from what I understand, the CanvasVirutalControl should overcome this problem because the CanvasVirutalControls that are scrolled off the screen can have their surface memory reused. Am I correct in this assumption? Is there any reason none of the docs talk about this scenario?

**Comment by damyanp** [comment]
I've not thought too much about this.  I think that this may work out for you, but if each individual control is a "reasonable" size then it might be more efficient to use some kind of [virtualization scheme](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/listview-and-gridview-data-optimization) so you can avoid the runtime cost of tracking all the controls that are off the screen.

**Comment by benstevens48** [comment]
OK, thanks, well it seems to be working - at least RegionsInvalidated is getting called when the control is scrolled back onto the screen after being offscreen for a while. I guess a virtualization scheme might be better, but it's pretty complicated to implement in my situation. In practice, the number of CanvasVirtualControls I have isn't going to be that large - max about 100, but if each is 1000*1000 pixels then that's 400MB of memory if each has its own surface, which is too much. So the virtualization provided by CanvasVirtualControl seems ideal for this scenario. I think this is maybe not an uncommon scenario, so is it perhaps worth adding it to the docs as a possible use case?

**Comment by shawnhar** [comment]
I'm a little wary of this just because it isn't the main scenario that the DComp virtualization technology (which Win2D sits on top of) was designed for.  There are a ton of magic numbers (aka 'policy decisions' :-) inside that implementation, adjusting things like cache sizes and eviction policies to balance memory usage against performance.  These were all tuned for the scenario of one big surface, only part of which was visible at a time.  I suspect it's more luck than anything if the behavior also correctly handles the scenario of many small surfaces, only a few of which are visible at a time.

At this point DComp is very mature and stable so I'm not overly worried about is implementation changing radically in future, but just be aware your use case is quite novel so there's a risk of unexpected corner case behaviors etc...

**Comment by benstevens48** [comment]
OK, thanks for that insider's insight. I'll keep using multiple CanvasVirtualControls unless it seems to cause a problem. (In reality what I described above was the absolute worst-case scenario and in fact I could probably get away with just using CanvasControl). I'll close this issue now.
