### ISSUE TITLE
D2D issue: D2DGetInputCoordinate should come with a warning or be fixed to work with CanvasVirtualBitmap

### ISSUE THREAD

**Issue by benstevens48** [microsoft/Win2D#792]
Sorry for posting another D2D issue, but I don't know where else I would post it.

I recently wanted to implement a custom vignette effect, so I decided to write a custom pixel shader (and use the very helpful PixelShaderEffect class). To do this I needed to know the relative position (x and y in the [0,1] interval) of the input pixel in the input (equivalently output). I found two D2D HLSL helper functions that seemed relevant - D2DGetInputCoordinate and D2DGetScenePosition. I was unable to determine from the docs what coordinate systems these used and whether or not they were normalized to [0,1]. After some experimentation I found that D2DGetScenePosition was not normalized, whereas D2DGetInputCoordinate was, so I decided to use that. Initially it looked like this worked but actually it didn't - because the position returned by this function resets on each of the internal tiles used by CanvasVirtualBitmap, so the vignette was starting again multiple times across the image. 

So I would like to suggest that there is a warning in the docs for D2DGetInputCoordinate about this behavior, and to be honest as far as I can see this behavior renders D2DGetInputCoordinate completely useless for general use, so perhaps it should be fixed to work with the internal tiling if that's possible.

Also, I have a couple of questions about D2DGetScenePosition, which I am now using. Is the coordinate space used by this the same as the coordinate space of the bounds I get when calling ICanvasImage.GetBounds(CanvasDevice) (assuming 96 DPI)? Secondly, is there a way to get the bounds of the input using shader code, or do I have to pass the bounds to the shader? At the moment I am passing the bounds, but it's slightly inconvenient.

**Comment by shawnhar** [comment]
Thanks, I will pass this along.

**Comment by MilesCohen-MS** [comment]
D2DGetInputCoordinate should return a normalized set of coordinates related to the input texture. I would expect that these coordinates are normalized to the specific tile of the texture that is being operated on, as it should be possible to sample the texture using the D2DSampleInput helper given this input.

D2DGetScenePosition should return the scene position. This method is more related to the output coordinate space, and I would not expect these coordinates to be normalized. If you want to sample from an input based on this position, D2DSampleInputAtPosition would be the right method to call. This helper method already normalizes the coordinate for you in order to translate it into the input space. If the scene position was only used in order to sample an input, I wouldn't expect that you would need to pass your own set of shader constants for the size of the input or output, as these helper methods should take care of that.

If I'm understanding the question right, it sounds like you were originally expecting that input coordinates and output coordinates should match up. But I don't think that is necessarily the case in general. The internal tiling that occurs is a good reason why spaces will often not match up.

Looking at Direct2D's implementation of the Vignette effect, it appears that we have a custom vertex shader which is used to pass more data to the pixel shader - helping the pixel shader orient itself. Win2D does not expose custom vertex shaders, so my guess is that you are trying to do the full effect here in the pixel shader. I do think that you will need to pass more constant data to the shader in order to do this, so that you will know how the scene position maps to the output space.

**Comment by benstevens48** [comment]
@MilesCohen-MS - thanks for the explanation. What I was missing was this statement from the [Custom effect docs](https://docs.microsoft.com/en-us/windows/win32/direct2d/custom-effects)

> Texel-space input: This parameter represents the current execution position in a particular input texture. A shader should not take any dependencies on how this value is calculated. It should only use it to sample the pixel shader's input

especially the part **It should only use it to sample the pixel shader's input**.

Maybe this could be added to the D2DGetInputCoordinate docs? But actually given this limitation, I can't really see any use for the D2DGetInputCoordinate function.

**Comment by MilesCohen-MS** [comment]
Thanks for the feedback here. We've updated the docs for D2DGetInputCoordinate.

**Comment by benstevens48** [comment]
Thanks!
