### ISSUE TITLE
UWP: Efficiently display SVGs generated with CanvasSvgDocument?

### ISSUE THREAD

**Issue by DilanBoskan** [microsoft/Win2D#826]
I am developing an application where I require to draw a dynamically adjustable grid. I started drawing this grid with the CanvasControl. However, the CanvasControl utilizes the GPU and therefore only has a, for my usecase, small max texture size. In addition, that max texture size may vary depending on the type of GPU. Ideally, instead of creating an incredibly large image to show the user, generating an SVG, and displaying that, would get rid of the whole problem.

Does Win2D have a feature which lets me display a CanvasSvgDocument on the front-end?

If not, can I utilize "ForceSoftwareRendering" for the generation of the Bitmap to achieve higher resolutions? I was looking at #38 but couldn't quite make out how to work with it from the discussion.

Other than that, thank you, Win2D developers, for this amazing library, I am awed otherwise at its ease of use.

**Comment by DilanBoskan** [comment]
I want to add, I attempted to display the Grid through the XAML Canvas, but when displaying plenty of Lines, the memory usage can reach up to 2 GB, when zoomed into the Canvas, and then crash the program.

**Comment by shawnhar** [comment]
Rather than rasterizing an incredibly large image and then zooming in to show just part of it, I'd suggest rethinking your approach so you only draw the portion that's visible at any one time, and redraw as zoom or pan changes.  There shouldn't be any need to create a CanvasControl larger than your output display, or to use excessive amounts of memory for something like this.

**Comment by DilanBoskan** [comment]
Thank you for the quick response.

I agree, this will probably be the approach to take. I just cannot seem to find events fired by the XAML ScrollViewer indicating an occurred pan or zoom.
Am I missing something, or, do you know of any open-source examples implementing this type of behaviour (rendering based on viewed area of ScrollViewer) in any sort?

**Comment by DilanBoskan** [comment]
@shawnhar I just need some direction, I do not ask for a detailed guide.

**Comment by shawnhar** [comment]
CanvasVirtualControl is a cache of rendered pixels, so when you zoom in on that you're just zooming in on whatever image has already been rendered.  You instead want to be re-rendering your content as the zoom changes.  Instead of applying XAML level transforms to your Win2D control, leave the Win2D control in the same place as far as XAML is concerned, and apply your transforms as part of the Win2D rendering within it.   That will require tracking zoom and pan yourself rather than having XAML do all this for you, afraid I don't know much about that side of things.

**Comment by damyanp** [comment]
[GestureRecognizer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.gesturerecognizer?view=winrt-19041) might be worth checking out to help with this.

**Comment by DilanBoskan** [comment]
Appreciate the help, thanks to both of you!
