### ISSUE TITLE
DrawingSession should be disposed?

### ISSUE THREAD

**Issue by suprak** [Microsoft/Win2D#83]
When handling the Draw event, some documentation suggests that we're expected to call dispose on the DrawingSession object.

Is that actually the case? Because if so, that sounds logically incorrect, since we as event handlers don't instantiate the DrawingSession, so it should not be ours to cleanup?

**Comment by damyanp** [comment]
You are correct: if you create the DrawingSession object yourself then you should dispose it when you have finished drawing.  In the case of the event handlers, Win2D has created the DrawingSession for you and so you don't need to call Dispose() yourself.

Can you point us towards the documentation that suggests otherwise so we can fix it please?

Thanks.
