### ISSUE TITLE
Interop code doesn't work from C++/WinRT app. Error: Cannot open include file: 'Microsoft.UI.Composition.h': No such file or directory

### ISSUE THREAD

**Issue by dmitry-egorov** [microsoft/Win2D#908]
I'm trying to get native ID2D1DeviceContext from CanvasDrawingSession, roughly following this example: https://microsoft.github.io/Win2D/WinUI3/html/Interop.htm

Unfortunately, this line doesn't work:
#include <Microsoft.Graphics.Canvas.h>
It errors out with "Cannot open include file: 'Microsoft.UI.Composition.h': No such file or directory".

"Microsoft.Graphics.Canvas.h" includes native "Microsoft.UI.Composition.h", but it seems like it's not part of Windows App SDK headers. Am I missing something?

**Comment by getrou** [comment]
I do not think you are missing something here, this appears to be a bug. I will investigate!

**Comment by getrou** [comment]
Ah, I see the issue. I believe you want

`#include <winrt/Microsoft.Graphics.Canvas.h>`

I will make a note to update the docs to reflect that difference from UWP!

**Comment by jdmansour** [comment]
I'm getting the same error message. However,
```
#include <winrt/Microsoft.Graphics.Canvas.h>
```
doesn't work because the header doesn't exist under `winrt/`. I have a Win32 project and have installed `Microsoft.Graphics.Win2D` 1.0.5.1 via NuGet.

Maybe I should add that this is not a WinAppSDK project, but I am following the example for Windows.UI.Composition [here](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-visual-layer-with-win32) and would like to add an effect visual, which seems to require Win2D (see [here](https://learn.microsoft.com/en-us/uwp/api/windows.ui.composition.compositioneffectbrush?view=winrt-22621)).

**Comment by brabebhin** [comment]
Docs are still not updated.
