### ISSUE TITLE
what is win2d ?is same to direct2d?

### ISSUE THREAD

**Issue by ljzj2** [Microsoft/Win2D#933]
If there is two way:use win2d and use P/Invoke in Direct2D api
which is more performance?

is win2d a c++ wrap  of direct2d?

**Comment by getrou** [comment]
Broadly speaking, Win2D is a WinRT wrapper around Direct2D, which makes it available in both C++ and C#. It doesn't contain _everything_ in D2D but it is generally much easier to learn. Win2D also has some popular WinUI wrapper controls to easily integrate with WinUI applications. It is available for either UWP or WinUI3/WinAppSDK applications.

Dropping down to the D2D layer can be more performant than Win2D if your scenario has special cases that Win2D doesn't specifically optimize for, but D2D can be more difficult to learn/design/write, so that's a trade-off you'll have to decide on.

**Comment by ljzj2** [comment]
@getrou  thank you and is it nice for develop 2d games in win2d?

**Comment by getrou** [comment]
Win2D is a graphics library, not a game engine. So while the CanvasAnimatedControl WinUI control has concepts like a game loop and input handling, it doesn't have more complete game engine features, like 2D physics for example. But for simple games not requiring those advanced features, yes it can be convenient!

**Comment by ljzj2** [comment]
@getrou  but what about the performance? what do you suggest me to use? P/Invoke or win2d I want to develop a simple game.

only want to use some colission of objects.

 and thank you for your job on it.

where to learn the win2d docs?


and I know that renderTarget is not available in microsoft store right? is win2d used it?

**Comment by ljzj2** [comment]
and `CanvasAnimatedControl ` is only available in uwp right? not available in WinUI3?

**Comment by getrou** [comment]
While I think that a hand-tailoring a D2D app for your game could result in a more performant application, I think the gains would likely be negligible (especially for a simple game), it would be many hours of work and overall I wouldn't recommend it.

You can check out the Win2D docs here:
https://microsoft.github.io/Win2D/html/Introduction.htm
We've also started porting some of the docs to MSLearn to make them more discoverable:
https://learn.microsoft.com/en-us/windows/apps/develop/win2d

Apologies, I don't understand your renderTarget question.

CanvasAnimatedControl is only in UWP, but that is changing! Expect a preview Win2D for WinUI3 build with CanvasAnimatedControl soon!
